<a href="https://colab.research.google.com/github/schrodinger2/theFrauds/blob/main/ML/preprocessing/comiset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys

# Install aria2c
!apt-get -y install aria2

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libaria2-0 libcares2
The following NEW packages will be installed:
  aria2 libaria2-0 libcares2
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,566 kB of archives.
After this operation, 5,692 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu noble/main amd64 libcares2 amd64 1.27.0-1.0ubuntu1 [73.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu noble/universe amd64 libaria2-0 amd64 1.37.0+debian-1build3 [1,105 kB]
Get:3 http://archive.ubuntu.com/ubuntu noble/universe amd64 aria2 amd64 1.37.0+debian-1build3 [387 kB]
Fetched 1,566 kB in 1s (1,371 kB/s)
Selecting previously unselected package libcares2:amd64.
(Reading database ... 122809 files and directories currently installed.)
Preparing to unpack .../libcares2_1.27.0-1.0ubuntu1_amd64.deb ...
Unpacking libcares2:amd64 (1.27.0-1.0ubuntu1) ...
Selecting previously unselected package libaria2-0:amd64.
Preparing to unpack .../libaria2-0_1.37.0+debian-1build3_amd64.deb ...
Unpacking libaria2-0:amd64 (1.37.0+debian-1build3) ...
Selecting previously unselected package aria2.
Preparing to unpack .../aria2_1.37.0+debian-1build3_amd64.deb ...
Unpacking aria2 (1.37.0+debian-1build3) ...
Setting up libcares2:amd64 (1.27.0-1.0ubuntu1) ...
Setting up libaria2-0:amd64 (1.37.0+debian-1build3) ...
Setting up aria2 (1.37.0+debian-1build3) ...
Processing triggers for man-db (2.12.0-4build2) ...
Processing triggers for libc-bin (2.39-0ubuntu8.9) ...
/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

In [ ]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.13/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.13/dist-packages (from kaggle) (6.4.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.13/dist-packages (from kaggle) (1.19.5)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.13/dist-packages (from kaggle) (0.1.37)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from kaggle) (26.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.13/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.13/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.13/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.13/dist-packages (from bleach->kaggle) (0.6.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (0.6.1)
Requirement already satisfied: nbformat in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (5.11.1)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.13/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->kaggle) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->kaggle) (3.19)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->kaggle) (2026.7.22)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (2.22.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.13/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.11.7)

In [ ]:
!aria2c -x 8 -s 8 -o Comiset23_Lab_Environment_Dataset.zip "https://zenodo.org/records/15375146/files/Comiset23_Lab_Environment_Dataset.zip?download=1"

09/22 22:52:43 [NOTICE] Downloading 1 item(s)

09/22 22:53:37 [NOTICE] Download complete: /content/Comiset23_Lab_Environment_Dataset.zip

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
cc57c1|OK  |    88MiB/s|/content/Comiset23_Lab_Environment_Dataset.zip

Status Legend:
(OK):download completed.

In [ ]:
import zipfile
import json
import os

ZIP_PATH = "/content/Comiset23_Lab_Environment_Dataset.zip"

# See what's inside the ZIP
with zipfile.ZipFile(ZIP_PATH, "r") as z:
    print("Files in ZIP:")
    for info in z.infolist():
        print(f"{info.filename} | compressed: {info.compress_size/1e9:.2f} GB | "
              f"uncompressed: {info.file_size/1e9:.2f} GB")

    # Pick the JSON file
    json_files = [x for x in z.namelist() if x.lower().endswith(".json")]
    print("\nJSON files:", json_files)

    json_name = json_files[0]

    # Read only the beginning — DO NOT extract the file
    with z.open(json_name) as f:
        for i in range(30):
            line = f.readline()
            if not line:
                break
            print(line[:1000].decode("utf-8", errors="replace"))

Files in ZIP:
dataset_comillas2.json | compressed: 4.91 GB | uncompressed: 159.73 GB

JSON files: ['dataset_comillas2.json']
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"8c0acd213cc3524fc717afbc33644d9c2eb6626c","_score":1,"_source":{"event_original_time":"2022-11-16T08:25:38.047Z","etl_processed_time":"2022-11-16T08:28:16.386Z","user_name":"system","PossibleCause":"Unknown","type":"wineventlog","process_id":888,"@timestamp":"2022-11-16T08:25:38.047Z","host_name":"desktop-4pvps6e.phoenix.local","level":"error","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","wmi-user_field_renames","wmi-all-extract_domain_and_user_name","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","winevent-user_name-is-machine-account","final-cleanup-message_field"],"task":"None","User":"nt authority\\system","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","thread_id
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"0d2a164f33fb2cd735fbeefacd8165feee47b8cc","_score":1,"_source":{"event_original_time":"2022-11-16T08:25:39.136Z","etl_processed_time":"2022-11-16T08:28:16.386Z","user_name":"system","PossibleCause":"Unknown","type":"wineventlog","process_id":888,"@timestamp":"2022-11-16T08:25:39.136Z","host_name":"desktop-4pvps6e.phoenix.local","level":"error","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","wmi-user_field_renames","wmi-all-extract_domain_and_user_name","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","winevent-user_name-is-machine-account","final-cleanup-message_field"],"task":"None","User":"nt authority\\system","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","thread_id
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"7db3aacc0f20ac35b4e6a1c6b20ba4b3697f75c8","_score":1,"_source":{"event_original_time":"2022-11-16T08:25:39.292Z","etl_processed_time":"2022-11-16T08:28:16.386Z","user_name":"system","PossibleCause":"Unknown","type":"wineventlog","process_id":888,"@timestamp":"2022-11-16T08:25:39.292Z","host_name":"desktop-4pvps6e.phoenix.local","level":"error","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","wmi-user_field_renames","wmi-all-extract_domain_and_user_name","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","winevent-user_name-is-machine-account","final-cleanup-message_field"],"task":"None","User":"nt authority\\system","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","thread_id
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"6d8e5cc3ec92af0da8b6b8e52d8a18bca7b82a05","_score":1,"_source":{"event_original_time":"2022-11-16T08:25:39.600Z","etl_processed_time":"2022-11-16T08:28:16.386Z","user_name":"system","PossibleCause":"Unknown","type":"wineventlog","process_id":888,"@timestamp":"2022-11-16T08:25:39.600Z","host_name":"desktop-4pvps6e.phoenix.local","level":"error","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","wmi-user_field_renames","wmi-all-extract_domain_and_user_name","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","winevent-user_name-is-machine-account","final-cleanup-message_field"],"task":"None","User":"nt authority\\system","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","thread_id
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"30265d28be5024061be36958e300d3d37ff2cda7","_score":1,"_source":{"event_original_time":"2022-11-16T08:22:44.173Z","etl_processed_time":"2022-11-16T08:28:16.386Z","user_name":"system","PossibleCause":"Unknown","type":"wineventlog","process_id":888,"@timestamp":"2022-11-16T08:22:44.173Z","host_name":"desktop-4pvps6e.phoenix.local","level":"error","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","wmi-user_field_renames","wmi-all-extract_domain_and_user_name","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","winevent-user_name-is-machine-account","final-cleanup-message_field"],"task":"None","User":"nt authority\\system","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","thread_id
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"dd1bded5e314c63e662a3935ca77d5be34c512fe","_score":1,"_source":{"event_original_time":"2022-11-16T08:25:39.310Z","etl_processed_time":"2022-11-16T08:28:16.360Z","user_name":"system","PossibleCause":"Unknown","type":"wineventlog","process_id":888,"@timestamp":"2022-11-16T08:25:39.310Z","host_name":"desktop-4pvps6e.phoenix.local","level":"error","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","wmi-user_field_renames","wmi-all-extract_domain_and_user_name","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","winevent-user_name-is-machine-account","final-cleanup-message_field"],"task":"None","User":"nt authority\\system","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","thread_id
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"12232bf144ab27dc0f82fa00636b4cb9af3da82d","_score":1,"_source":{"event_original_time":"2022-11-16T08:25:36.975Z","etl_processed_time":"2022-11-16T08:28:16.383Z","user_name":"system","PossibleCause":"Unknown","type":"wineventlog","process_id":888,"@timestamp":"2022-11-16T08:25:36.975Z","host_name":"desktop-4pvps6e.phoenix.local","level":"error","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","wmi-user_field_renames","wmi-all-extract_domain_and_user_name","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","winevent-user_name-is-machine-account","final-cleanup-message_field"],"task":"None","User":"nt authority\\system","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","thread_id
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"55eeba5cbe87d5d083ac309f1e66d95680c4f9f5","_score":1,"_source":{"event_original_time":"2022-11-16T08:25:39.269Z","etl_processed_time":"2022-11-16T08:28:16.383Z","user_name":"system","PossibleCause":"Unknown","type":"wineventlog","process_id":888,"@timestamp":"2022-11-16T08:25:39.269Z","host_name":"desktop-4pvps6e.phoenix.local","level":"error","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","wmi-user_field_renames","wmi-all-extract_domain_and_user_name","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","winevent-user_name-is-machine-account","final-cleanup-message_field"],"task":"None","User":"nt authority\\system","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","thread_id
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"3894f4f487a478341ff488efe75aad656e8c8cca","_score":1,"_source":{"event_original_time":"2022-11-16T08:25:39.575Z","etl_processed_time":"2022-11-16T08:28:16.383Z","user_name":"system","PossibleCause":"Unknown","type":"wineventlog","process_id":888,"@timestamp":"2022-11-16T08:25:39.575Z","host_name":"desktop-4pvps6e.phoenix.local","level":"error","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","wmi-user_field_renames","wmi-all-extract_domain_and_user_name","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","winevent-user_name-is-machine-account","final-cleanup-message_field"],"task":"None","User":"nt authority\\system","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","thread_id
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"f6e336281871aaf0383bc374053d7a166e888b2c","_score":1,"_source":{"event_original_time":"2022-11-16T08:17:00.093Z","etl_processed_time":"2022-11-16T08:28:16.386Z","type":"wineventlog","process_id":1152,"@timestamp":"2022-11-16T08:17:00.093Z","host_name":"desktop-4pvps6e.phoenix.local","level":"information","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","final-cleanup-message_field"],"task":"None","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","thread_id":1908,"@version":"1","z_elastic_ecs":{"agent":{},"event":{"created":"2022-11-16T08:28:14.345Z","code":"2010","action":"None","kind":"event","provider":"Microsoft-Windows-Win
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"0d3fbf2dfa434e3fe68af1e6aa8394552aaddf24","_score":1,"_source":{"@timestamp":"2022-11-16T08:22:22.639Z","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","thread_id":1684,"Current Signature Version":"1.379.432.0","@version":"1","Current Engine Version":"1.1.19800.4","event_id":"2000","Product Version":"4.8.10240.17394","record_number":16,"beat_version":"8.5.0","etl_version":"2020.04.19.01","Update Type Index":"2","event_original_time":"2022-11-16T08:22:22.639Z","etl_processed_time":"2022-11-16T08:28:16.386Z","type":"wineventlog","Previous Signature Version":"1.379.235.0","process_id":2328,"host_name":"desktop-4pvps6e.phoenix.local","Product Name":"%%827","SID":"S-1-5-18","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","152
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"bf6aebfdcb73ca347f60a315d1e140e122649893","_score":1,"_source":{"event_original_time":"2022-11-16T08:19:31.225Z","etl_processed_time":"2022-11-16T08:28:16.354Z","ProviderName":"StorageWMI","type":"wineventlog","process_id":3024,"@timestamp":"2022-11-16T08:19:31.225Z","host_name":"desktop-4pvps6e.phoenix.local","level":"information","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","wmi-user_field_renames","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","final-cleanup-message_field"],"HostProcess":"wmiprvse.exe","task":"None","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","ProviderPath":"%SystemRoot%\\System32\\storagewmi.dll","thread_id":4968,"@version":"1","z_elastic_ecs
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"86e037523c81a6f9366cef51e5a0f09edd16c68c","_score":1,"_source":{"event_original_time":"2022-11-16T08:18:33.460Z","etl_processed_time":"2022-11-16T08:28:16.386Z","ProviderName":"smbwmiv2","type":"wineventlog","process_id":3024,"@timestamp":"2022-11-16T08:18:33.460Z","host_name":"desktop-4pvps6e.phoenix.local","level":"information","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","wmi-user_field_renames","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","final-cleanup-message_field"],"HostProcess":"wmiprvse.exe","task":"None","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","ProviderPath":"%SystemRoot%\\System32\\smbwmiv2.dll","thread_id":3044,"@version":"1","z_elastic_ecs":{"
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"be4a671d94f603fc72b77c17e1038c02ff982c2a","_score":1,"_source":{"event_original_time":"2022-11-16T08:17:11.202Z","etl_processed_time":"2022-11-16T08:28:16.386Z","Reason":"5","type":"wineventlog","activity_id":"{61A55000-55E5-1017-0000-000000000000}","process_id":624,"@timestamp":"2022-11-16T08:17:11.202Z","host_name":"desktop-4pvps6e.phoenix.local","level":"information","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","final-cleanup-message_field"],"task":"None","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","thread_id":3152,"@version":"1","z_elastic_ecs":{"agent":{},"event":{"created":"2022-11-16T08:28:14.655Z","code":"40"
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"5cd232067d087d809eef4f9e2e8b70961a6a2d95","_score":1,"_source":{"event_original_time":"2022-11-16T08:17:15.517Z","etl_processed_time":"2022-11-16T08:28:16.386Z","param1":"10.0.10240.17394","type":"wineventlog","process_id":3592,"@timestamp":"2022-11-16T08:17:15.517Z","host_name":"desktop-4pvps6e.phoenix.local","level":"information","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","final-cleanup-message_field"],"task":"None","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","thread_id":3612,"z_elastic_ecs":{"agent":{},"event":{"created":"2022-11-16T08:28:14.785Z","code":"101","action":"None","kind":"event","provider":"Microsoft
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"80c950225289f28c07d1246d8af78cb51e95764c","_score":1,"_source":{"event_original_time":"2022-11-16T08:17:10.864Z","etl_processed_time":"2022-11-16T08:28:16.386Z","SessionID":"3","type":"wineventlog","activity_id":"{61A55000-55E5-1017-0000-000000000000}","process_id":624,"@timestamp":"2022-11-16T08:17:10.864Z","host_name":"desktop-4pvps6e.phoenix.local","level":"information","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","final-cleanup-message_field"],"task":"None","User":"desktop-4pvps6e\\michael","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","thread_id":528,"@version":"1","z_elastic_ecs":{"agent":{},"event":{"created":"2
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"bdab18430d3949312baa6556770cbb785aecb88f","_score":1,"_source":{"event_original_time":"2022-11-16T08:17:14.896Z","etl_processed_time":"2022-11-16T08:28:16.386Z","SessionID":"3","type":"wineventlog","activity_id":"{61A55000-55E5-1017-0000-000000000000}","process_id":624,"@timestamp":"2022-11-16T08:17:14.896Z","host_name":"desktop-4pvps6e.phoenix.local","level":"information","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","final-cleanup-message_field"],"task":"None","User":"desktop-4pvps6e\\michael","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","thread_id":528,"@version":"1","z_elastic_ecs":{"agent":{},"event":{"created":"2
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"7c42096079d77ab673037aa0854eda015a6f1dc5","_score":1,"_source":{"event_original_time":"2022-11-16T08:22:22.146Z","etl_processed_time":"2022-11-16T08:28:16.386Z","param1":"<none>","type":"wineventlog","process_id":3592,"@timestamp":"2022-11-16T08:22:22.146Z","host_name":"desktop-4pvps6e.phoenix.local","level":"information","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","final-cleanup-message_field"],"task":"None","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","thread_id":7468,"z_elastic_ecs":{"agent":{},"event":{"created":"2022-11-16T08:28:14.785Z","code":"100","action":"None","kind":"event","provider":"Microsoft-Client-Li
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"42be1229f2d0e7bf455d5010d7c06f0420b6c545","_score":1,"_source":{"event_original_time":"2022-11-16T08:22:22.199Z","etl_processed_time":"2022-11-16T08:28:16.386Z","param1":"10.0.10240.17394","type":"wineventlog","process_id":3592,"@timestamp":"2022-11-16T08:22:22.199Z","host_name":"desktop-4pvps6e.phoenix.local","level":"information","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","final-cleanup-message_field"],"task":"None","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","thread_id":3700,"z_elastic_ecs":{"agent":{},"event":{"created":"2022-11-16T08:28:14.785Z","code":"101","provider":"Microsoft-Client-Licensing-Platform","ki

In [ ]:
import zipfile
import json

ZIP_PATH = "/content/Comiset23_Lab_Environment_Dataset.zip"
JSON_NAME = "dataset_comillas2.json"

with zipfile.ZipFile(ZIP_PATH) as z:
    with z.open(JSON_NAME) as f:
        for i, line in enumerate(f):
            event = json.loads(line)

            if i < 5:
                print("\nEVENT", i)
                print("Top-level:", event.keys())
                print("_source keys:")
                print(list(event["_source"].keys()))

                # Search for anything mentioning attack / technique / MITRE
                matches = []
                def search_keys(obj, path=""):
                    if isinstance(obj, dict):
                        for k, v in obj.items():
                            p = f"{path}.{k}" if path else k
                            if any(x in k.lower() for x in
                                   ["attack", "technique", "tactic", "label",
                                    "malicious", "threat", "scenario"]):
                                matches.append((p, v))
                            search_keys(v, p)
                    elif isinstance(obj, list):
                        for j, v in enumerate(obj):
                            search_keys(v, f"{path}[{j}]")

                search_keys(event)
                print("Potential labels:")
                for x in matches:
                    print(x)

            if i >= 4:
                break

EVENT 0
Top-level: dict_keys(['_index', '_type', '_id', '_score', '_source'])
_source keys:
['event_original_time', 'etl_processed_time', 'user_name', 'PossibleCause', 'type', 'process_id', '@timestamp', 'host_name', 'level', 'etl_host_agent_type', 'etl_pipeline', 'task', 'User', 'etl_host_agent_ephemeral_uid', 'thread_id', 'user_domain', 'ClientMachine', '@version', 'Operation', 'z_elastic_ecs', 'xml_name', 'opcode', 'event_id', 'Component', 'ResultCode', 'log_name', 'ClientProcessId', 'record_number', 'event_original_message', 'provider_guid', 'beat_name', 'meta_user_name_is_machine', 'etl_host_agent_uid', 'source_name', 'etl_version', 'Id', 'beat_version']
Potential labels:

EVENT 1
Top-level: dict_keys(['_index', '_type', '_id', '_score', '_source'])
_source keys:
['event_original_time', 'etl_processed_time', 'user_name', 'PossibleCause', 'type', 'process_id', '@timestamp', 'host_name', 'level', 'etl_host_agent_type', 'etl_pipeline', 'task', 'User', 'etl_host_agent_ephemeral_uid', 'thread_id', 'user_domain', '@version', 'ClientMachine', 'Operation', 'z_elastic_ecs', 'xml_name', 'opcode', 'event_id', 'Component', 'ResultCode', 'log_name', 'ClientProcessId', 'record_number', 'event_original_message', 'provider_guid', 'beat_name', 'meta_user_name_is_machine', 'etl_host_agent_uid', 'source_name', 'etl_version', 'Id', 'beat_version']
Potential labels:

EVENT 2
Top-level: dict_keys(['_index', '_type', '_id', '_score', '_source'])
_source keys:
['event_original_time', 'etl_processed_time', 'user_name', 'PossibleCause', 'type', 'process_id', '@timestamp', 'host_name', 'level', 'etl_host_agent_type', 'etl_pipeline', 'task', 'User', 'etl_host_agent_ephemeral_uid', 'thread_id', 'user_domain', 'ClientMachine', '@version', 'Operation', 'z_elastic_ecs', 'xml_name', 'opcode', 'event_id', 'Component', 'ResultCode', 'log_name', 'ClientProcessId', 'record_number', 'event_original_message', 'provider_guid', 'beat_name', 'meta_user_name_is_machine', 'etl_host_agent_uid', 'source_name', 'etl_version', 'Id', 'beat_version']
Potential labels:

EVENT 3
Top-level: dict_keys(['_index', '_type', '_id', '_score', '_source'])
_source keys:
['event_original_time', 'etl_processed_time', 'user_name', 'PossibleCause', 'type', 'process_id', '@timestamp', 'host_name', 'level', 'etl_host_agent_type', 'etl_pipeline', 'task', 'User', 'etl_host_agent_ephemeral_uid', 'thread_id', 'user_domain', 'ClientMachine', '@version', 'Operation', 'z_elastic_ecs', 'xml_name', 'opcode', 'event_id', 'Component', 'ResultCode', 'log_name', 'ClientProcessId', 'record_number', 'event_original_message', 'provider_guid', 'beat_name', 'meta_user_name_is_machine', 'etl_host_agent_uid', 'source_name', 'etl_version', 'Id', 'beat_version']
Potential labels:

EVENT 4
Top-level: dict_keys(['_index', '_type', '_id', '_score', '_source'])
_source keys:
['event_original_time', 'etl_processed_time', 'user_name', 'PossibleCause', 'type', 'process_id', '@timestamp', 'host_name', 'level', 'etl_host_agent_type', 'etl_pipeline', 'task', 'User', 'etl_host_agent_ephemeral_uid', 'thread_id', 'user_domain', '@version', 'ClientMachine', 'Operation', 'z_elastic_ecs', 'xml_name', 'opcode', 'event_id', 'Component', 'ResultCode', 'log_name', 'ClientProcessId', 'record_number', 'event_original_message', 'provider_guid', 'beat_name', 'meta_user_name_is_machine', 'etl_host_agent_uid', 'source_name', 'etl_version', 'Id', 'beat_version']
Potential labels:

In [ ]:
import zipfile
import json

ZIP_PATH = "/content/Comiset23_Lab_Environment_Dataset.zip"
JSON_NAME = "dataset_comillas2.json"

keywords = [
    "mitre",
    "attack",
    "technique",
    "tactic",
    "T1059",
    "T1110",
    "T1003",
    "malicious",
]

found = 0

with zipfile.ZipFile(ZIP_PATH) as z:
    with z.open(JSON_NAME) as f:
        for i, line in enumerate(f):
            text = line.decode("utf-8", errors="ignore").lower()

            matches = [k for k in keywords if k.lower() in text]

            if matches:
                event = json.loads(line)

                print(f"\nEVENT #{i}")
                print("Matches:", matches)
                print(json.dumps(event, indent=2)[:5000])

                found += 1

                if found >= 10:
                    break

print(f"\nFound {found} matching events.")

EVENT #395
Matches: ['mitre']
{
  "_index": "logs-endpoint-winevent-additional-2022.11.16",
  "_type": "_doc",
  "_id": "3033dad108c838d9dae35443845f9c0650ad7e94",
  "_score": 1,
  "_source": {
    "event_original_time": "2022-11-16T08:23:47.200Z",
    "etl_processed_time": "2022-11-16T08:28:24.761Z",
    "Message": "SLS Configuration:  {\n     \"AADAuthority\" : \"https://login.windows.net/common\",\n     \"AADProviderClientId\" : \"268761a2-03f3-40df-8a8b-c3db24145b6b\",\n     \"AADProviderScope\" : \"www.microsoft.com::mbi_ssl\",\n     \"AADResource\" : \"https://onestore.microsoft.com\",\n     \"AlternateId\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}\",\n     \"AppsHomePage\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}&oemId={oemId}&scmId={scmId}&moId={moId}\",\n     \"BoomBoxSiteId\" : \"music.microsoft.com\",\n     \"BrowseCommandTargetByCategory\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/charts?{CommonParams}&listName=TopFree&category={CatId}&mediaType={MediaType}\",\n     \"BrowseCommandTargetBySubCategory\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/charts?{CommonParams}&listName=TopFree&category={CatId}&subCategory={SubCatId}&mediaType={MediaType}\",\n     \"BrowseCommandTargetByChart\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/charts?{CommonParams}&listName={ListId}&mediaType={MediaType}\",\n     \"BrowseCommandTargetByRelated\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/related?{CommonParams}&productId={ProductId}\",\n     \"BulkProductDetails\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/products?market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogIds={catalogIds}&catalogTicketKeys={catalogTicketKeys}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}&oemId={oemId}&scmId={scmId}&moId={moId}\",\n     \"CallerSpecificData\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/callerspecificdata/?market={marketCode}&locale={localeCode}&appversion={appVersion}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&oemId={oemId}&scmId={scmId}&moId={moId}\",\n     \"ChartCommandTarget\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/chartResults?{CommonParams}&itemType=Apps{=FilterQueryString}&oemId={oemId}&scmId={scmId}&moId={moId}\",\n     \"CollectionList\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/collectionlist?collectionid={Id}&{CommonParams}\",\n     \"CollectionDetails\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/pages/collection?collectionId={Id}&{CommonParams}&oemId={oemId}&scmId={scmId}&moId={moId}\",\n     \"ErrorInfo\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/errorinfo?context={errorContext}&code={errorCode}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}\",\n     \"GamesHomePage\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/gamesHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}&oemId={oemId}&scmId={scmId}&moId={moId}\",\n     \"GetAllEntitlements\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/entitlements?\",\n     \"GetProductReviews\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/ratings/product/{productId}?systemType={systemType}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&deviceFamilyFilter={deviceFamilyFilter}\",\n     \"GetRatingsSummary\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/ratings/summary/product/{productId}?systemType={systemType}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&deviceFamilyFilter={deviceFamilyFilter}\",\n     \"GetUserReview\" : \"https://storeedgefd.dsx.m

EVENT #2469
Matches: ['mitre']
{
  "_index": "logs-endpoint-winevent-additional-2022.11.16",
  "_type": "_doc",
  "_id": "92b48f7fa0b8485d18c61bd0cee2b8d990f3e80f",
  "_score": 1,
  "_source": {
    "event_original_time": "2022-11-16T12:19:40.949Z",
    "etl_processed_time": "2022-11-16T12:36:58.987Z",
    "Message": "SLS Configuration:  {\n     \"AADAuthority\" : \"https://login.windows.net/common\",\n     \"AADProviderClientId\" : \"268761a2-03f3-40df-8a8b-c3db24145b6b\",\n     \"AADProviderScope\" : \"www.microsoft.com::mbi_ssl\",\n     \"AADResource\" : \"https://onestore.microsoft.com\",\n     \"AlternateId\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}\",\n     \"AppsHomePage\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}&oemId={oemId}&scmId={scmId}&moId={moId}\",\n     \"BoomBoxSiteId\" : \"music.microsoft.com\",\n     \"BrowseCommandTargetByCategory\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/charts?{CommonParams}&listName=TopFree&category={CatId}&mediaType={MediaType}\",\n     \"BrowseCommandTargetBySubCategory\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/charts?{CommonParams}&listName=TopFree&category={CatId}&subCategory={SubCatId}&mediaType={MediaType}\",\n     \"BrowseCommandTargetByChart\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/charts?{CommonParams}&listName={ListId}&mediaType={MediaType}\",\n     \"BrowseCommandTargetByRelated\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/related?{CommonParams}&productId={ProductId}\",\n     \"BulkProductDetails\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/products?market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogIds={catalogIds}&catalogTicketKeys={catalogTicketKeys}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}&oemId={oemId}&scmId={scmId}&moId={moId}\",\n     \"CallerSpecificData\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/callerspecificdata/?market={marketCode}&locale={localeCode}&appversion={appVersion}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&oemId={oemId}&scmId={scmId}&moId={moId}\",\n     \"ChartCommandTarget\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/chartResults?{CommonParams}&itemType=Apps{=FilterQueryString}&oemId={oemId}&scmId={scmId}&moId={moId}\",\n     \"CollectionList\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/collectionlist?collectionid={Id}&{CommonParams}\",\n     \"CollectionDetails\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/pages/collection?collectionId={Id}&{CommonParams}&oemId={oemId}&scmId={scmId}&moId={moId}\",\n     \"ErrorInfo\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/errorinfo?context={errorContext}&code={errorCode}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}\",\n     \"GamesHomePage\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/gamesHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}&oemId={oemId}&scmId={scmId}&moId={moId}\",\n     \"GetAllEntitlements\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/entitlements?\",\n     \"GetProductReviews\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/ratings/product/{productId}?systemType={systemType}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&deviceFamilyFilter={deviceFamilyFilter}\",\n     \"GetRatingsSummary\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/ratings/summary/product/{productId}?systemType={systemType}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&deviceFamilyFilter={deviceFamilyFilter}\",\n     \"GetUserReview\" : \"https://storeedgefd.dsx.m

EVENT #2738
Matches: ['mitre']
{
  "_index": "logs-endpoint-winevent-additional-2022.11.16",
  "_type": "_doc",
  "_id": "d62ee2ab9a31b18176beca69c7b1bea8b3656360",
  "_score": 1,
  "_source": {
    "event_original_time": "2022-11-16T13:04:52.574Z",
    "etl_processed_time": "2022-11-16T12:55:49.159Z",
    "Message": "SLS Configuration:  {\n     \"AADAuthority\" : \"https://login.windows.net/common\",\n     \"AADProviderClientId\" : \"268761a2-03f3-40df-8a8b-c3db24145b6b\",\n     \"AADProviderScope\" : \"www.microsoft.com::mbi_ssl\",\n     \"AADResource\" : \"https://onestore.microsoft.com\",\n     \"AlternateId\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}\",\n     \"AppsHomePage\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}&oemId={oemId}&scmId={scmId}&moId={moId}\",\n     \"BoomBoxSiteId\" : \"music.microsoft.com\",\n     \"BrowseCommandTargetByCategory\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/charts?{CommonParams}&listName=TopFree&category={CatId}&mediaType={MediaType}\",\n     \"BrowseCommandTargetBySubCategory\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/charts?{CommonParams}&listName=TopFree&category={CatId}&subCategory={SubCatId}&mediaType={MediaType}\",\n     \"BrowseCommandTargetByChart\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/charts?{CommonParams}&listName={ListId}&mediaType={MediaType}\",\n     \"BrowseCommandTargetByRelated\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/related?{CommonParams}&productId={ProductId}\",\n     \"BulkProductDetails\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/products?market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogIds={catalogIds}&catalogTicketKeys={catalogTicketKeys}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}&oemId={oemId}&scmId={scmId}&moId={moId}\",\n     \"CallerSpecificData\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/callerspecificdata/?market={marketCode}&locale={localeCode}&appversion={appVersion}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&oemId={oemId}&scmId={scmId}&moId={moId}\",\n     \"ChartCommandTarget\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/chartResults?{CommonParams}&itemType=Apps{=FilterQueryString}&oemId={oemId}&scmId={scmId}&moId={moId}\",\n     \"CollectionList\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/collectionlist?collectionid={Id}&{CommonParams}\",\n     \"CollectionDetails\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/pages/collection?collectionId={Id}&{CommonParams}&oemId={oemId}&scmId={scmId}&moId={moId}\",\n     \"ErrorInfo\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/errorinfo?context={errorContext}&code={errorCode}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}\",\n     \"GamesHomePage\" : \"https://storeedgefd.dsx.mp.microsoft.com/pages/gamesHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}&oemId={oemId}&scmId={scmId}&moId={moId}\",\n     \"GetAllEntitlements\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/entitlements?\",\n     \"GetProductReviews\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/ratings/product/{productId}?systemType={systemType}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&deviceFamilyFilter={deviceFamilyFilter}\",\n     \"GetRatingsSummary\" : \"https://storeedgefd.dsx.mp.microsoft.com/channels/ratings/summary/product/{productId}?systemType={systemType}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&deviceFamilyFilter={deviceFamilyFilter}\",\n     \"GetUserReview\" : \"https://storeedgefd.dsx.m

EVENT #3831
Matches: ['mitre']
{
  "_index": "logs-endpoint-winevent-additional-2022.11.16",
  "_type": "_doc",
  "_id": "c204c27738b7b124b2b7091a24f80130676d11c3",
  "_score": 1,
  "_source": {
    "event_original_time": "2022-11-16T13:49:25.411Z",
    "etl_processed_time": "2022-11-16T13:40:40.402Z",

In [ ]:
import zipfile
import json

ZIP_PATH = "/content/Comiset23_Lab_Environment_Dataset.zip"

def find_mitre(obj, path=""):
    if isinstance(obj, dict):
        for k, v in obj.items():
            new_path = f"{path}.{k}" if path else k

            if any(x in str(k).lower() for x in
                   ["mitre", "attack", "technique", "tactic", "label"]):
                print("KEY:", new_path)
                print("VALUE:", repr(v)[:1000])

            find_mitre(v, new_path)

    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            find_mitre(v, f"{path}[{i}]")

with zipfile.ZipFile(ZIP_PATH) as z:
    json_name = [x for x in z.namelist()
                 if x.lower().endswith(".json")][0]

    with z.open(json_name) as f:
        # Assuming JSONL for now
        for i, line in enumerate(f):
            if i >= 10000:
                break

            event = json.loads(line)
            find_mitre(event)

In [ ]:
import zipfile
import json
import re

ZIP_PATH = "/content/Comiset23_Lab_Environment_Dataset.zip"

patterns = re.compile(
    r"(T\d{4}(?:\.\d{3})?|MITRE|ATT&CK|technique|tactic)",
    re.IGNORECASE
)

with zipfile.ZipFile(ZIP_PATH) as z:
    print(z.namelist())

    json_name = [x for x in z.namelist() if x.lower().endswith(".json")][0]

    with z.open(json_name) as f:
        for i, line in enumerate(f):
            if i >= 10000:
                break

            event = json.loads(line)

            def search_values(obj, path=""):
                if isinstance(obj, dict):
                    for k, v in obj.items():
                        search_values(v, f"{path}.{k}")
                elif isinstance(obj, list):
                    for j, v in enumerate(obj):
                        search_values(v, f"{path}[{j}]")
                elif isinstance(obj, str) and patterns.search(obj):
                    print("\nEVENT:", i)
                    print("PATH:", path)
                    print("MATCH:", patterns.findall(obj)[:20])
                    print("VALUE:", obj[:1000])

            search_values(event)

['dataset_comillas2.json']

EVENT: 25
PATH: ._source.DeviceInstanceId
MATCH: ['T3031']
VALUE: USB\VID_0781&PID_558C\MSFT30313931323739343031373435

EVENT: 25
PATH: ._source.event_original_message
MATCH: ['T3031']
VALUE: Device USB\VID_0781&PID_558C\MSFT30313931323739343031373435 was configured.

Driver Name: uaspstor.inf
Class Guid: {4D36E97B-E325-11CE-BFC1-08002BE10318}
Driver Date: 06/21/2006
Driver Version: 10.0.10240.16384
Driver Provider: Microsoft
Driver Section: UASPort_Install_Control
Driver Rank: 0xFF2000
Matching Device Id: USB\Class_08&SubClass_06&Prot_62
Outranked Drivers:
Device Updated: false

EVENT: 26
PATH: ._source.DeviceInstanceId
MATCH: ['T3031']
VALUE: USB\VID_0781&PID_558C\MSFT30313931323739343031373435

EVENT: 26
PATH: ._source.event_original_message
MATCH: ['T3031']
VALUE: Device USB\VID_0781&PID_558C\MSFT30313931323739343031373435 was started.

Driver Name: uaspstor.inf
Class Guid: {4D36E97B-E325-11CE-BFC1-08002BE10318}
Service: UASPStor
Lower Filters:
Upper Filters:

EVENT: 395
PATH: ._source.Message
MATCH: ['mitRe']
VALUE: SLS Configuration:  {
     "AADAuthority" : "https://login.windows.net/common",
     "AADProviderClientId" : "268761a2-03f3-40df-8a8b-c3db24145b6b",
     "AADProviderScope" : "www.microsoft.com::mbi_ssl",
     "AADResource" : "https://onestore.microsoft.com",
     "AlternateId" : "https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}",
     "AppsHomePage" : "https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={p

EVENT: 395
PATH: ._source.event_original_message
MATCH: ['mitRe']
VALUE: SLS Configuration:  {
     "AADAuthority" : "https://login.windows.net/common",
     "AADProviderClientId" : "268761a2-03f3-40df-8a8b-c3db24145b6b",
     "AADProviderScope" : "www.microsoft.com::mbi_ssl",
     "AADResource" : "https://onestore.microsoft.com",
     "AlternateId" : "https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}",
     "AppsHomePage" : "https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={p

EVENT: 2469
PATH: ._source.Message
MATCH: ['mitRe']
VALUE: SLS Configuration:  {
     "AADAuthority" : "https://login.windows.net/common",
     "AADProviderClientId" : "268761a2-03f3-40df-8a8b-c3db24145b6b",
     "AADProviderScope" : "www.microsoft.com::mbi_ssl",
     "AADResource" : "https://onestore.microsoft.com",
     "AlternateId" : "https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}",
     "AppsHomePage" : "https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={p

EVENT: 2469
PATH: ._source.event_original_message
MATCH: ['mitRe']
VALUE: SLS Configuration:  {
     "AADAuthority" : "https://login.windows.net/common",
     "AADProviderClientId" : "268761a2-03f3-40df-8a8b-c3db24145b6b",
     "AADProviderScope" : "www.microsoft.com::mbi_ssl",
     "AADResource" : "https://onestore.microsoft.com",
     "AlternateId" : "https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}",
     "AppsHomePage" : "https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={p

EVENT: 2738
PATH: ._source.Message
MATCH: ['mitRe']
VALUE: SLS Configuration:  {
     "AADAuthority" : "https://login.windows.net/common",
     "AADProviderClientId" : "268761a2-03f3-40df-8a8b-c3db24145b6b",
     "AADProviderScope" : "www.microsoft.com::mbi_ssl",
     "AADResource" : "https://onestore.microsoft.com",
     "AlternateId" : "https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}",
     "AppsHomePage" : "https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={p

EVENT: 2738
PATH: ._source.event_original_message
MATCH: ['mitRe']
VALUE: SLS Configuration:  {
     "AADAuthority" : "https://login.windows.net/common",
     "AADProviderClientId" : "268761a2-03f3-40df-8a8b-c3db24145b6b",
     "AADProviderScope" : "www.microsoft.com::mbi_ssl",
     "AADResource" : "https://onestore.microsoft.com",
     "AlternateId" : "https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}",
     "AppsHomePage" : "https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={p

EVENT: 3831
PATH: ._source.Message
MATCH: ['mitRe']
VALUE: SLS Configuration:  {
     "AADAuthority" : "https://login.windows.net/common",
     "AADProviderClientId" : "268761a2-03f3-40df-8a8b-c3db24145b6b",
     "AADProviderScope" : "www.microsoft.com::mbi_ssl",
     "AADResource" : "https://onestore.microsoft.com",
     "AlternateId" : "https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}",
     "AppsHomePage" : "https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={p

EVENT: 3831
PATH: ._source.event_original_message
MATCH: ['mitRe']
VALUE: SLS Configuration:  {
     "AADAuthority" : "https://login.windows.net/common",
     "AADProviderClientId" : "268761a2-03f3-40df-8a8b-c3db24145b6b",
     "AADProviderScope" : "www.microsoft.com::mbi_ssl",
     "AADResource" : "https://onestore.microsoft.com",
     "AlternateId" : "https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}",
     "AppsHomePage" : "https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={p

EVENT: 5056
PATH: ._source.Message
MATCH: ['mitRe']
VALUE: SLS Configuration:  {
     "AADAuthority" : "https://login.windows.net/common",
     "AADProviderClientId" : "268761a2-03f3-40df-8a8b-c3db24145b6b",
     "AADProviderScope" : "www.microsoft.com::mbi_ssl",
     "AADResource" : "https://onestore.microsoft.com",
     "AlternateId" : "https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}",
     "AppsHomePage" : "https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={p

EVENT: 5056
PATH: ._source.event_original_message
MATCH: ['mitRe']
VALUE: SLS Configuration:  {
     "AADAuthority" : "https://login.windows.net/common",
     "AADProviderClientId" : "268761a2-03f3-40df-8a8b-c3db24145b6b",
     "AADProviderScope" : "www.microsoft.com::mbi_ssl",
     "AADResource" : "https://onestore.microsoft.com",
     "AlternateId" : "https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}",
     "AppsHomePage" : "https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={p

EVENT: 7019
PATH: ._source.Message
MATCH: ['mitRe']
VALUE: SLS Configuration:  {
     "AADAuthority" : "https://login.windows.net/common",
     "AADProviderClientId" : "268761a2-03f3-40df-8a8b-c3db24145b6b",
     "AADProviderScope" : "www.microsoft.com::mbi_ssl",
     "AADResource" : "https://onestore.microsoft.com",
     "AlternateId" : "https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}",
     "AppsHomePage" : "https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={p

EVENT: 7019
PATH: ._source.event_original_message
MATCH: ['mitRe']
VALUE: SLS Configuration:  {
     "AADAuthority" : "https://login.windows.net/common",
     "AADProviderClientId" : "268761a2-03f3-40df-8a8b-c3db24145b6b",
     "AADProviderScope" : "www.microsoft.com::mbi_ssl",
     "AADResource" : "https://onestore.microsoft.com",
     "AlternateId" : "https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}",
     "AppsHomePage" : "https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={p

EVENT: 7541
PATH: ._source.Message
MATCH: ['mitRe']
VALUE: SLS Configuration:  {
     "AADAuthority" : "https://login.windows.net/common",
     "AADProviderClientId" : "268761a2-03f3-40df-8a8b-c3db24145b6b",
     "AADProviderScope" : "www.microsoft.com::mbi_ssl",
     "AADResource" : "https://onestore.microsoft.com",
     "AlternateId" : "https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}",
     "AppsHomePage" : "https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={p

EVENT: 7541
PATH: ._source.event_original_message
MATCH: ['mitRe']
VALUE: SLS Configuration:  {
     "AADAuthority" : "https://login.windows.net/common",
     "AADProviderClientId" : "268761a2-03f3-40df-8a8b-c3db24145b6b",
     "AADProviderScope" : "www.microsoft.com::mbi_ssl",
     "AADResource" : "https://onestore.microsoft.com",
     "AlternateId" : "https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}",
     "AppsHomePage" : "https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={p

EVENT: 9783
PATH: ._source.Message
MATCH: ['mitRe']
VALUE: SLS Configuration:  {
     "AADAuthority" : "https://login.windows.net/common",
     "AADProviderClientId" : "268761a2-03f3-40df-8a8b-c3db24145b6b",
     "AADProviderScope" : "www.microsoft.com::mbi_ssl",
     "AADResource" : "https://onestore.microsoft.com",
     "AlternateId" : "https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}",
     "AppsHomePage" : "https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={p

EVENT: 9783
PATH: ._source.event_original_message
MATCH: ['mitRe']
VALUE: SLS Configuration:  {
     "AADAuthority" : "https://login.windows.net/common",
     "AADProviderClientId" : "268761a2-03f3-40df-8a8b-c3db24145b6b",
     "AADProviderScope" : "www.microsoft.com::mbi_ssl",
     "AADResource" : "https://onestore.microsoft.com",
     "AlternateId" : "https://storeedgefd.dsx.mp.microsoft.com/channels/products/{productId}?idType={idType}&appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&hardware={hardware}&packageHardware={packageHardware}&deviceFamilyVersion={deviceFamilyVersion}&architecture={architecture}",
     "AppsHomePage" : "https://storeedgefd.dsx.mp.microsoft.com/pages/appsHome?appversion={appVersion}&market={marketCode}&locale={localeCode}&deviceType={deviceType}&deviceFamily={deviceFamily}&catalogLocales={catalogLocaleCodes}&musicMarket={musicMarketCode}&screenSize={screenSize}&hardware={hardware}&packageHardware={p

In [ ]:
import zipfile
import json
from collections import Counter

ZIP_PATH = "/content/Comiset23_Lab_Environment_Dataset.zip"

key_counts = Counter()

with zipfile.ZipFile(ZIP_PATH) as z:
    with z.open("dataset_comillas2.json") as f:
        for i, line in enumerate(f):
            if i >= 1000:
                break

            event = json.loads(line)

            if "_source" in event:
                key_counts.update(event["_source"].keys())

print("Most common fields:")
for key, count in key_counts.most_common():
    print(f"{key}: {count}")

Most common fields:
event_original_time: 1000
etl_processed_time: 1000
type: 1000
process_id: 1000
@timestamp: 1000
host_name: 1000
level: 1000
etl_host_agent_type: 1000
etl_pipeline: 1000
task: 1000
etl_host_agent_ephemeral_uid: 1000
thread_id: 1000
@version: 1000
z_elastic_ecs: 1000
event_id: 1000
log_name: 1000
record_number: 1000
event_original_message: 1000
provider_guid: 1000
beat_name: 1000
etl_host_agent_uid: 1000
source_name: 1000
etl_version: 1000
beat_version: 1000
opcode: 999
keywords: 735
Message: 466
Line Number: 466
Source: 466
Function: 466
activity_id: 230
Error Code: 207
TaskName: 197
version: 142
State Machine Name: 137
Thread ID: 137
State Machine: 137
Current State: 94
InstanceId: 85
Event Name: 84
TaskInstanceId: 66
UserContext: 65
EnginePID: 64
ActionName: 58
Id: 50
bytesTransferred: 49
bytesTransferredFromPeer: 49
ResultCode: 47
name: 36
url: 36
transferId: 36
fileLength: 36
bytesTotal: 36
fileTime: 36
User: 33
ProcessID: 31
xml_name: 28
serviceGuid: 28
Priority: 23
Path: 23
updateRevisionNumber: 20
updateGuid: 20
Operation: 18
bandwidthLimit: 18
hr: 18
PeerContextInfo: 18
ignoreBandwidthLimitsOnLan: 18
peerProtocolFlags: 18
AdditionalInfoHr: 18
UserName: 17
string2: 15
string: 15
fileCount: 15
jobOwner: 15
jobTitle: 15
jobId: 15
PossibleCause: 14
ClientMachine: 14
Component: 14
ClientProcessId: 14
Status: 14
New State: 14
user_name: 13
user_domain: 13
meta_user_name_is_machine: 13
Value: 12
DeviceInstanceId: 9
updateCount: 9
DriverName: 8
ClassGuid: 8
ProviderName: 7
HostProcess: 7
ProviderPath: 7
Code: 7
Name: 7
QueuedTaskInstanceId: 7
TaskEngineName: 7
HasFlowUrl: 6
Expires: 6
AuthRequired: 6
ResourceURI: 6
Created: 6
RequestStatus: 6
HasEndAuthUrl: 6
TokenType: 6
HasAuthUrl: 6
RunningTaskInstanceId: 6
param1: 4
DriverSection: 4
DriverRank: 4
DriverDate: 4
DriverProvider: 4
DriverInbox: 4
DriverVersion: 4
MatchingDeviceId: 4
DeviceUpdated: 4
Problem: 4
Module Name: 4
Build Name: 4
Process Name: 4
NameLength: 4
Details: 4
Flags: 4
AppID: 4
Reason: 3
SessionID: 3
ServiceName: 3
ServerName: 3
ServerNameLength: 3
InterfaceGuid: 2
InterfaceName: 2
NewProfile: 2
OldProfile: 2
Current Signature Version: 2
Current Engine Version: 2
Product Version: 2
Update Type Index: 2
Previous Signature Version: 2
Product Name: 2
SID: 2
Previous Engine Version: 2
Signature Type Index: 2
Domain: 2
Signature Type: 2
Update Type: 2
Session: 2
UserId: 2
LicenseId: 2
PackageName: 2
AssociateId: 2
IfIndex: 2
TransportNameLength: 2
DomainNameLength: 2
TransportName: 2
OperationDescription: 2
ErrorCode: 2
SettingValue: 2
Origin: 2
SettingValueSize: 2
SettingType: 2
SettingValueDisplay: 2
ModifyingUser: 2
LowestFreeSpaceInBytes: 1
IsBootVolume: 1
VolumeName: 1
HighestFreeSpaceInBytes: 1
VolumeGuid: 1
VolumeNameLength: 1
Address: 1
DomainName: 1
TransportFlags: 1
OperationElaspedTimeInMilliSeconds: 1
updateTitle: 1
ErrorDescription: 1
Command: 1
ThreadID: 1

In [ ]:
import zipfile
import json
from collections import Counter

ZIP_PATH = "/content/Comiset23_Lab_Environment_Dataset.zip"

counters = {
    "log_name": Counter(),
    "source_name": Counter(),
    "event_id": Counter(),
    "type": Counter(),
    "task": Counter(),
}

with zipfile.ZipFile(ZIP_PATH) as z:
    with z.open("dataset_comillas2.json") as f:
        for i, line in enumerate(f):
            if i >= 100_000:
                break

            e = json.loads(line)["_source"]

            for field, counter in counters.items():
                value = e.get(field)
                if value is not None:
                    counter[str(value)] += 1

for field, counter in counters.items():
    print(f"\n===== {field} =====")
    for value, count in counter.most_common(30):
        print(f"{count:7}  {value}")

===== log_name =====
  43232  Microsoft-Windows-Store/Operational
  13273  Microsoft-Windows-TaskScheduler/Operational
   6541  Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
   6051  Microsoft-Windows-Shell-Core/Operational
   5771  Microsoft-Windows-Windows Firewall With Advanced Security/Firewall
   4405  Microsoft-Windows-GroupPolicy/Operational
   3013  Microsoft-Windows-Kernel-PnP/Configuration
   2498  Microsoft-Windows-WMI-Activity/Operational
   2228  Microsoft-Windows-Bits-Client/Operational
   1546  Microsoft-Windows-WindowsUpdateClient/Operational
   1455  Microsoft-Windows-LiveId/Operational
   1268  Microsoft-Client-Licensing-Platform/Admin
    930  Microsoft-Windows-Winlogon/Operational
    835  Microsoft-Windows-SmbClient/Connectivity
    822  Microsoft-Windows-Shell-Core/AppDefaults
    782  Microsoft-Windows-TerminalServices-LocalSessionManager/Operational
    522  Microsoft-Windows-Storage-Storport/Health
    479  Microsoft-Windows-SMBServer/Operational
    458  Microsoft-Windows-SettingSync/Debug
    375  Microsoft-Windows-Storage-Storport/Operational
    326  Microsoft-Windows-TerminalServices-RemoteConnectionManager/Operational
    300  Microsoft-Windows-User Profile Service/Operational
    299  Microsoft-Windows-TaskScheduler/Maintenance
    255  Microsoft-Windows-User Device Registration/Admin
    252  Microsoft-Windows-Time-Service/Operational
    242  Microsoft-Windows-WinRM/Operational
    234  Microsoft-Windows-Windows Defender/Operational
    177  Microsoft-Windows-SmartCard-DeviceEnum/Operational
    143  Microsoft-Windows-RemoteDesktopServices-SessionServices/Operational
    134  Microsoft-Windows-TerminalServices-RemoteConnectionManager/Admin

===== source_name =====
  26223  Microsoft-Windows-Install-Agent
  16782  Microsoft-Windows-Store
  13572  Microsoft-Windows-TaskScheduler
   6873  Microsoft-Windows-Shell-Core
   6541  Microsoft-Windows-RemoteDesktopServices-RdpCoreTS
   5771  Microsoft-Windows-Windows Firewall With Advanced Security
   4405  Microsoft-Windows-GroupPolicy
   3021  Microsoft-Windows-Kernel-PnP
   2498  Microsoft-Windows-WMI-Activity
   2228  Microsoft-Windows-Bits-Client
   1546  Microsoft-Windows-WindowsUpdateClient
   1455  Microsoft-Windows-LiveId
   1268  Microsoft-Client-Licensing-Platform
    930  Microsoft-Windows-Winlogon
    897  Microsoft-Windows-StorPort
    847  Microsoft-Windows-SMBClient
    782  Microsoft-Windows-TerminalServices-LocalSessionManager
    479  Microsoft-Windows-SMBServer
    460  Microsoft-Windows-TerminalServices-RemoteConnectionManager
    368  Microsoft-Windows-SettingSync
    353  Microsoft-Windows-Windows Defender
    291  Microsoft-Windows-User Profiles Service
    255  Microsoft-Windows-User Device Registration
    252  Microsoft-Windows-Time-Service
    242  Microsoft-Windows-WinRM
    194  Windows-ApplicationModel-Store-SDK
    177  Microsoft-Windows-SmartCard-DeviceEnum
    172  Microsoft-Windows-Ntfs
    143  Microsoft-Windows-RemoteDesktopServices-SessionServices
     94  Microsoft-Windows-CloudStore

===== event_id =====
  21514  2006
  10342  8001
   3476  2005
   3276  2004
   2160  100
   1953  200
   1882  102
   1832  148
   1828  2007
   1819  8011
   1763  62171
   1762  62170
   1683  140
   1668  201
   1641  129
   1611  5858
   1584  8002
   1415  2002
   1317  40
   1197  410
   1091  8012
   1046  132
   1022  400
    950  5320
    911  62144
    831  5857
    814  62443
    783  8010
    763  72
    568  59

===== type =====
 100000  wineventlog

===== task =====
  24897  None
  24623  Service
  11928  LM
   6541  RemoteFX module
   4639  LM State Machine
   3525  LogonPerformance_TaskRunTime
   1954  Task Started
   1953  Action started
   1683  Task registration updated
   1668  Action completed
   1668  Task completed
   1546  Windows Update Agent
   1520  Created Task Process
   1508  Agent
    911  TileManagement_PackageInfo_InstallStateChange
    894  Port
    880  CallSubscriber
    814  AppDefaults_Info
    438  Explorer_ExecutingFromRunKey
    413  Shell32_AppResolverCache_AddShortcut
    294  Task triggered on logon
    289  Launch request ignored, instance already running
    277  Maintenance state has changed
    264  Missed task started
    255  Launch request queued
    245  Shell32_AppResolver_Scan
    239  SrvEndpointAdded
    238  Explorer_EnumeratingRunKey
    215  LM Module Loaded
    214  WLID Service Operation

In [ ]:
import zipfile

ZIP_PATH = "/content/Comiset23_Lab_Environment_Dataset.zip"

with zipfile.ZipFile(ZIP_PATH) as z:
    with z.open("dataset_comillas2.json") as f:
        first = f.readline()
        print("FIRST LINE:")
        print(first[:3000].decode("utf-8", errors="replace"))

        # Jump near the end of the compressed stream
        f.seek(0, 2)
        print("\nEND POSITION:", f.tell())

FIRST LINE:
{"_index":"logs-endpoint-winevent-additional-2022.11.16","_type":"_doc","_id":"8c0acd213cc3524fc717afbc33644d9c2eb6626c","_score":1,"_source":{"event_original_time":"2022-11-16T08:25:38.047Z","etl_processed_time":"2022-11-16T08:28:16.386Z","user_name":"system","PossibleCause":"Unknown","type":"wineventlog","process_id":888,"@timestamp":"2022-11-16T08:25:38.047Z","host_name":"desktop-4pvps6e.phoenix.local","level":"error","etl_host_agent_type":"winlogbeat","etl_pipeline":["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","wmi-user_field_renames","wmi-all-extract_domain_and_user_name","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","winevent-user_name-is-machine-account","final-cleanup-message_field"],"task":"None","User":"nt authority\\system","etl_host_agent_ephemeral_uid":"f7b6d19e-5167-4483-b795-09a22efb4701","thread_id":1672,"user_domain":"nt authority","ClientMachine":"DESKTOP-4PVPS6E","@version":"1","Operation":"Start IWbemServices::ExecQuery - root\\CIMV2 : SELECT uuid FROM win32_computersystemproduct ","z_elastic_ecs":{"agent":{},"event":{"created":"2022-11-16T08:28:14.318Z","code":"5858","provider":"Microsoft-Windows-WMI-Activity","kind":"event","action":"None"},"host":{},"ecs":{"version":"8.0.0"},"log":{},"winlog":{"process":{"thread":{}}},"user":{"type":"User","domain":"NT AUTHORITY","name":"SYSTEM","identifier":"S-1-5-18"}},"xml_name":"Operation_ClientFailure","opcode":"Info","event_id":"5858","Component":"Unknown","ResultCode":"0x80041032","log_name":"Microsoft-Windows-WMI-Activity/Operational","ClientProcessId":"4264","record_number":594,"event_original_message":"Id = {00000000-0000-0000-0000-000000000000}; ClientMachine = DESKTOP-4PVPS6E; User = NT AUTHORITY\\SYSTEM; ClientProcessId = 4264; Component = Unknown; Operation = Start IWbemServices::ExecQuery - root\\CIMV2 : SELECT uuid FROM win32_computersystemproduct ; ResultCode = 0x80041032; PossibleCause = Unknown","provider_guid":"1418EF04-B0B4-4623-BF7E-D74AB47BBDAA","beat_name":"DESKTOP-4PVPS6E","meta_user_name_is_machine":"false","etl_host_agent_uid":"f99bee41-708a-4aa2-ad36-b5a565e36b68","source_name":"Microsoft-Windows-WMI-Activity","etl_version":"2020.04.19.01","Id":"{00000000-0000-0000-0000-000000000000}","beat_version":"8.5.0"}}


END POSITION: 159730026735

In [ ]:
import zipfile, json, re

ZIP_PATH = "/content/Comiset23_Lab_Environment_Dataset.zip"
pattern = re.compile(r'\bT\d{4}(?:\.\d{3})?\b')

with zipfile.ZipFile(ZIP_PATH) as z:
    with z.open("dataset_comillas2.json") as f:
        for i, line in enumerate(f):
            event = json.loads(line)

            matches = []

            def scan(x, path=""):
                if isinstance(x, dict):
                    for k, v in x.items():
                        scan(v, path + "." + k)
                elif isinstance(x, list):
                    for j, v in enumerate(x):
                        scan(v, path + f"[{j}]")
                elif isinstance(x, str):
                    for m in pattern.findall(x):
                        matches.append((m, path))

            scan(event)

            # Ignore IDs embedded in USB/device identifiers
            real = [(m, p) for m, p in matches
                    if "DeviceInstanceId" not in p]

            if real:
                print("\nEVENT", i)
                print(real[:20])
                print(json.dumps(event["_source"], indent=2)[:5000])
                break

EVENT 431058
[('T1553.004', '._source.RuleName'), ('T1553.004', '._source.event_original_message'), ('T1553.004', '._source.rule_technique_id')]
{
  "event_original_time": "2022-11-16T19:59:51.007Z",
  "etl_processed_time": "2022-11-16T20:00:30.683Z",
  "user_name": "louis",
  "process_guid": "4FD6B357-412E-6375-CA00-000000002900",
  "type": "wineventlog",
  "version": 2,
  "rule_technique_name": "Install Root Certificate",
  "process_id": "1120",
  "@timestamp": "2022-11-16T19:59:51.007Z",
  "host_name": "desktop-4pvps6e.phoenix.local",
  "process_path": "c:\\users\\louis\\appdata\\local\\microsoft\\onedrive\\onedrive.exe",
  "level": "information",
  "etl_host_agent_type": "winlogbeat",
  "etl_pipeline": [
    "all-filter-0098",
    "all-add_processed_timestamp",
    "fingerprint-winlogbeats7",
    "winlogbeat_7_and_above-field_nest_cleanup",
    "winlogbeat_7_and_above-field_cleanups",
    "1500",
    "1522",
    "winevent-sysmon-all-1531",
    "sysmon-all-extract_domain_and_user_name",
    "general_rename-various_global_options",
    "general_rename-ProcessGuid",
    "general_rename-ProcessId",
    "general_rename-Image",
    "split-process_path-grok-process_name",
    "provider_guid-cleanup",
    "process_guid-cleanup",
    "winevent-hostname-cleanup",
    "winevent-user_name-is-machine-account",
    "final-cleanup-message_field"
  ],
  "task": "Registry object added or deleted (rule: RegistryEvent)",
  "etl_host_agent_ephemeral_uid": "ecc16bcb-39c4-4de0-b10a-ed3c7d9bf3c3",
  "thread_id": 3440,
  "user_domain": "desktop-4pvps6e",
  "@version": "1",
  "z_elastic_ecs": {
    "agent": {},
    "event": {
      "created": "2022-11-16T20:00:28.186Z",
      "code": "12",
      "action": "Registry object added or deleted (rule: RegistryEvent)",
      "kind": "event",
      "provider": "Microsoft-Windows-Sysmon"
    },
    "host": {},
    "ecs": {
      "version": "8.0.0"
    },
    "log": {},
    "winlog": {
      "process": {
        "thread": {}
      }
    },
    "user": {
      "type": "User",
      "domain": "NT AUTHORITY",
      "identifier": "S-1-5-18",
      "name": "SYSTEM"
    }
  },
  "EventType": "CreateKey",
  "TargetObject": "HKU\\S-1-5-21-1311114680-1922563338-3976463898-1001\\SOFTWARE\\Microsoft\\SystemCertificates\\Root\\Certificates",
  "RuleName": "technique_id=T1553.004,technique_name=Install Root Certificate",
  "event_recorded_time": "2022-11-16T19:59:51.444Z",
  "opcode": "Info",
  "event_id": "12",
  "event_timezone": "UTC",
  "log_name": "Microsoft-Windows-Sysmon/Operational",
  "meta_user_name_is_machine": "false",
  "record_number": 348655,
  "event_original_message": "Registry object added or deleted:\nRuleName: technique_id=T1553.004,technique_name=Install Root Certificate\nEventType: CreateKey\nUtcTime: 2022-11-16 19:59:51.007\nProcessGuid: {4FD6B357-412E-6375-CA00-000000002900}\nProcessId: 1120\nImage: C:\\Users\\Louis\\AppData\\Local\\Microsoft\\OneDrive\\OneDrive.exe\nTargetObject: HKU\\S-1-5-21-1311114680-1922563338-3976463898-1001\\SOFTWARE\\Microsoft\\SystemCertificates\\Root\\Certificates\nUser: DESKTOP-4PVPS6E\\Louis",
  "provider_guid": "5770385F-C22A-43E0-BF4C-06F5698FFBD9",
  "beat_name": "DESKTOP-4PVPS6E",
  "user_account": "desktop-4pvps6e\\louis",
  "etl_host_agent_uid": "f99bee41-708a-4aa2-ad36-b5a565e36b68",
  "source_name": "Microsoft-Windows-Sysmon",
  "process_name": "onedrive.exe",
  "etl_version": "2020.04.19.01",
  "beat_version": "8.5.0",
  "rule_technique_id": "T1553.004"
}

In [ ]:
import zipfile
import json
import gzip
import time

ZIP_PATH = "/content/Comiset23_Lab_Environment_Dataset.zip"
OUTPUT_PATH = "/content/comiset_lab_subset.jsonl.gz"

benign_seen = 0
benign_kept = 0
malicious_kept = 0
total_seen = 0

start = time.time()

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    with z.open("dataset_comillas2.json", "r") as src, \
         gzip.open(OUTPUT_PATH, "wt", encoding="utf-8") as dst:

        for line in src:
            total_seen += 1

            event = json.loads(line)
            source = event.get("_source", {})

            # ATT&CK-labeled = malicious
            technique = source.get("rule_technique_id")

            if technique:
                # Keep ALL malicious events
                dst.write(json.dumps(event, separators=(",", ":")) + "\n")
                malicious_kept += 1

            else:
                # Keep exactly ~50% of benign events
                if benign_seen % 2 == 0:
                    dst.write(json.dumps(event, separators=(",", ":")) + "\n")
                    benign_kept += 1

                benign_seen += 1

            if total_seen % 1_000_000 == 0:
                elapsed = time.time() - start
                print(
                    f"{total_seen:,} processed | "
                    f"{benign_kept:,} benign kept | "
                    f"{malicious_kept:,} malicious kept | "
                    f"{elapsed/60:.1f} min"
                )

print("\nDONE")
print(f"Total processed:     {total_seen:,}")
print(f"Benign kept:         {benign_kept:,}")
print(f"Malicious kept:      {malicious_kept:,}")
print(f"Total output events: {benign_kept + malicious_kept:,}")
print(f"Output:              {OUTPUT_PATH}")

1,000,000 processed | 498,420 benign kept | 3,161 malicious kept | 1.7 min
2,000,000 processed | 994,400 benign kept | 11,201 malicious kept | 3.4 min
3,000,000 processed | 1,481,439 benign kept | 37,123 malicious kept | 5.3 min
4,000,000 processed | 1,933,776 benign kept | 132,449 malicious kept | 7.4 min
5,000,000 processed | 2,403,718 benign kept | 192,565 malicious kept | 9.2 min
6,000,000 processed | 2,870,279 benign kept | 259,442 malicious kept | 11.0 min
7,000,000 processed | 3,361,948 benign kept | 276,105 malicious kept | 12.8 min
8,000,000 processed | 3,779,826 benign kept | 440,349 malicious kept | 14.9 min
9,000,000 processed | 4,246,065 benign kept | 507,871 malicious kept | 16.9 min
10,000,000 processed | 4,739,282 benign kept | 521,436 malicious kept | 18.6 min
11,000,000 processed | 5,234,089 benign kept | 531,822 malicious kept | 20.5 min
12,000,000 processed | 5,716,221 benign kept | 567,558 malicious kept | 22.2 min
13,000,000 processed | 6,188,806 benign kept | 622,388 malicious kept | 24.2 min
14,000,000 processed | 6,666,538 benign kept | 666,925 malicious kept | 26.1 min
15,000,000 processed | 7,144,645 benign kept | 710,710 malicious kept | 27.9 min
16,000,000 processed | 7,639,450 benign kept | 721,100 malicious kept | 29.5 min
17,000,000 processed | 8,108,400 benign kept | 783,200 malicious kept | 31.4 min
18,000,000 processed | 8,599,381 benign kept | 801,238 malicious kept | 33.2 min
19,000,000 processed | 9,092,802 benign kept | 814,397 malicious kept | 35.0 min
20,000,000 processed | 9,586,594 benign kept | 826,813 malicious kept | 36.8 min
21,000,000 processed | 10,078,852 benign kept | 842,296 malicious kept | 38.6 min
22,000,000 processed | 10,570,219 benign kept | 859,563 malicious kept | 40.3 min
23,000,000 processed | 11,053,813 benign kept | 892,374 malicious kept | 42.1 min
24,000,000 processed | 11,548,594 benign kept | 902,813 malicious kept | 43.8 min
25,000,000 processed | 12,035,950 benign kept | 928,101 malicious kept | 45.6 min
26,000,000 processed | 12,531,976 benign kept | 936,049 malicious kept | 47.5 min
27,000,000 processed | 13,002,086 benign kept | 995,829 malicious kept | 49.4 min
28,000,000 processed | 13,487,491 benign kept | 1,025,018 malicious kept | 51.0 min
29,000,000 processed | 13,939,768 benign kept | 1,120,464 malicious kept | 52.9 min
30,000,000 processed | 14,405,327 benign kept | 1,189,346 malicious kept | 54.6 min
31,000,000 processed | 14,835,487 benign kept | 1,329,027 malicious kept | 56.4 min
32,000,000 processed | 15,291,772 benign kept | 1,416,456 malicious kept | 58.2 min
33,000,000 processed | 15,758,454 benign kept | 1,483,093 malicious kept | 59.9 min
34,000,000 processed | 16,253,229 benign kept | 1,493,542 malicious kept | 61.6 min
35,000,000 processed | 16,748,839 benign kept | 1,502,323 malicious kept | 63.5 min
36,000,000 processed | 17,239,302 benign kept | 1,521,397 malicious kept | 65.3 min
37,000,000 processed | 17,731,931 benign kept | 1,536,139 malicious kept | 67.0 min
38,000,000 processed | 18,228,043 benign kept | 1,543,914 malicious kept | 68.8 min
39,000,000 processed | 18,723,382 benign kept | 1,553,237 malicious kept | 70.5 min
40,000,000 processed | 19,217,917 benign kept | 1,564,167 malicious kept | 72.2 min
41,000,000 processed | 19,711,044 benign kept | 1,577,912 malicious kept | 73.9 min
42,000,000 processed | 20,203,356 benign kept | 1,593,289 malicious kept | 75.7 min
43,000,000 processed | 20,697,463 benign kept | 1,605,075 malicious kept | 77.5 min
44,000,000 processed | 21,192,349 benign kept | 1,615,302 malicious kept | 79.1 min
45,000,000 processed | 21,684,707 benign kept | 1,630,586 malicious kept | 80.8 min
46,000,000 processed | 22,176,248 benign kept | 1,647,505 malicious kept | 82.6 min
47,000,000 processed | 22,666,568 benign kept | 1,666,864 malicious kept | 84.4 min
48,000,000 processed | 23,160,125 benign kept | 1,679,750 malicious kept | 86.1 min
49,000,000 processed | 23,652,180 benign kept | 1,695,641 malicious kept | 87.8 min

DONE
Total processed:     49,914,325
Benign kept:         24,100,308
Malicious kept:      1,713,709
Total output events: 25,814,017
Output:              /content/comiset_lab_subset.jsonl.gz

In [ ]:
import os

size_gb = os.path.getsize("/content/comiset_lab_subset.jsonl.gz") / (1024**3)
print(f"{size_gb:.2f} GB")

2.60 GB

In [ ]:
import os

os.environ["KAGGLE_API_TOKEN"] = "KGAT_dc4d5b3156c7d8449d6ea40c1a53b0e9"

In [ ]:

!pip install -q kaggle

!kaggle datasets init -p /content

You must authenticate before you can call the Kaggle API.
Follow the instructions to authenticate at: https://github.com/Kaggle/kaggle-cli/blob/main/docs/README.md#authentication

In [ ]:
import json

path = "/content/dataset-metadata.json"

metadata = {
    "title": "COMISET Lab 50% Benign Subset",
    "id": "saifthesaif/comiset-lab-50-benign-subset",
    "licenses": [{"name": "CC0-1.0"}],
    "resources": [
        {
            "path": "comiset_lab_subset.jsonl.gz"
        }
    ]
}

with open(path, "w") as f:
    json.dump(metadata, f, indent=2)

In [ ]:
c!pip install -U kagglehub

Requirement already satisfied: kagglehub in /usr/local/lib/python3.13/dist-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in /usr/local/lib/python3.13/dist-packages (from kagglehub) (0.1.37)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from kagglehub) (26.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->kagglehub) (2026.7.22)

In [ ]:
#farha , download the kaggle dataset using this cell
import kagglehub

path = kagglehub.dataset_download(
    "saifthesaif/comiset-lab-50-benign-subset"
)

print(path)

Downloading to /root/.cache/kagglehub/datasets/saifthesaif/comiset-lab-50-benign-subset/6.archive...

100%|██████████| 978M/978M [00:26<00:00, 38.9MB/s]

Extracting files...

/root/.cache/kagglehub/datasets/saifthesaif/comiset-lab-50-benign-subset/versions/6

In [ ]:
!cp -r "/root/.cache/kagglehub/datasets/saifthesaif/comiset-lab-50-benign-subset/versions/6" "/content"

In [ ]:

import os
import subprocess

DATASET = "saifthesaif/comiset-lab-50-benign-subset"
OUT = "/content/comiset_parquet"

os.makedirs(OUT, exist_ok=True)

for i in range(228,517):
    filename = f"comiset_parquet/part-{i:05d}.parquet"

    print(f"\n[{i+1}/517] Downloading {filename}")

    result = subprocess.run([
        "kaggle", "datasets", "download",
        "-d", DATASET,
        "-f", filename,
        "-p", OUT
    ])

    if result.returncode != 0:
        print(f"FAILED: {filename}")
        break

print("\nFinished.")

[229/517] Downloading comiset_parquet/part-00228.parquet

[230/517] Downloading comiset_parquet/part-00229.parquet

[231/517] Downloading comiset_parquet/part-00230.parquet

[232/517] Downloading comiset_parquet/part-00231.parquet

[233/517] Downloading comiset_parquet/part-00232.parquet

[234/517] Downloading comiset_parquet/part-00233.parquet

[235/517] Downloading comiset_parquet/part-00234.parquet

[236/517] Downloading comiset_parquet/part-00235.parquet

[237/517] Downloading comiset_parquet/part-00236.parquet

[238/517] Downloading comiset_parquet/part-00237.parquet

[239/517] Downloading comiset_parquet/part-00238.parquet

[240/517] Downloading comiset_parquet/part-00239.parquet

[241/517] Downloading comiset_parquet/part-00240.parquet

[242/517] Downloading comiset_parquet/part-00241.parquet

[243/517] Downloading comiset_parquet/part-00242.parquet

[244/517] Downloading comiset_parquet/part-00243.parquet

[245/517] Downloading comiset_parquet/part-00244.parquet

[246/517] Downloading comiset_parquet/part-00245.parquet

[247/517] Downloading comiset_parquet/part-00246.parquet

[248/517] Downloading comiset_parquet/part-00247.parquet

[249/517] Downloading comiset_parquet/part-00248.parquet

[250/517] Downloading comiset_parquet/part-00249.parquet

[251/517] Downloading comiset_parquet/part-00250.parquet

[252/517] Downloading comiset_parquet/part-00251.parquet

[253/517] Downloading comiset_parquet/part-00252.parquet

[254/517] Downloading comiset_parquet/part-00253.parquet

[255/517] Downloading comiset_parquet/part-00254.parquet

[256/517] Downloading comiset_parquet/part-00255.parquet

[257/517] Downloading comiset_parquet/part-00256.parquet

[258/517] Downloading comiset_parquet/part-00257.parquet

[259/517] Downloading comiset_parquet/part-00258.parquet

[260/517] Downloading comiset_parquet/part-00259.parquet

[261/517] Downloading comiset_parquet/part-00260.parquet

[262/517] Downloading comiset_parquet/part-00261.parquet

[263/517] Downloading comiset_parquet/part-00262.parquet

[264/517] Downloading comiset_parquet/part-00263.parquet

[265/517] Downloading comiset_parquet/part-00264.parquet

[266/517] Downloading comiset_parquet/part-00265.parquet

[267/517] Downloading comiset_parquet/part-00266.parquet

[268/517] Downloading comiset_parquet/part-00267.parquet

[269/517] Downloading comiset_parquet/part-00268.parquet

[270/517] Downloading comiset_parquet/part-00269.parquet

[271/517] Downloading comiset_parquet/part-00270.parquet

[272/517] Downloading comiset_parquet/part-00271.parquet

[273/517] Downloading comiset_parquet/part-00272.parquet

[274/517] Downloading comiset_parquet/part-00273.parquet

[275/517] Downloading comiset_parquet/part-00274.parquet

[276/517] Downloading comiset_parquet/part-00275.parquet

[277/517] Downloading comiset_parquet/part-00276.parquet

[278/517] Downloading comiset_parquet/part-00277.parquet

[279/517] Downloading comiset_parquet/part-00278.parquet

[280/517] Downloading comiset_parquet/part-00279.parquet

[281/517] Downloading comiset_parquet/part-00280.parquet

[282/517] Downloading comiset_parquet/part-00281.parquet

[283/517] Downloading comiset_parquet/part-00282.parquet

[284/517] Downloading comiset_parquet/part-00283.parquet

[285/517] Downloading comiset_parquet/part-00284.parquet

[286/517] Downloading comiset_parquet/part-00285.parquet

[287/517] Downloading comiset_parquet/part-00286.parquet

[288/517] Downloading comiset_parquet/part-00287.parquet

[289/517] Downloading comiset_parquet/part-00288.parquet

[290/517] Downloading comiset_parquet/part-00289.parquet

[291/517] Downloading comiset_parquet/part-00290.parquet

[292/517] Downloading comiset_parquet/part-00291.parquet

[293/517] Downloading comiset_parquet/part-00292.parquet

[294/517] Downloading comiset_parquet/part-00293.parquet

[295/517] Downloading comiset_parquet/part-00294.parquet

[296/517] Downloading comiset_parquet/part-00295.parquet

[297/517] Downloading comiset_parquet/part-00296.parquet

[298/517] Downloading comiset_parquet/part-00297.parquet

[299/517] Downloading comiset_parquet/part-00298.parquet

[300/517] Downloading comiset_parquet/part-00299.parquet

[301/517] Downloading comiset_parquet/part-00300.parquet

[302/517] Downloading comiset_parquet/part-00301.parquet

[303/517] Downloading comiset_parquet/part-00302.parquet

[304/517] Downloading comiset_parquet/part-00303.parquet

[305/517] Downloading comiset_parquet/part-00304.parquet

[306/517] Downloading comiset_parquet/part-00305.parquet

[307/517] Downloading comiset_parquet/part-00306.parquet

[308/517] Downloading comiset_parquet/part-00307.parquet

[309/517] Downloading comiset_parquet/part-00308.parquet

[310/517] Downloading comiset_parquet/part-00309.parquet

[311/517] Downloading comiset_parquet/part-00310.parquet

[312/517] Downloading comiset_parquet/part-00311.parquet

[313/517] Downloading comiset_parquet/part-00312.parquet

[314/517] Downloading comiset_parquet/part-00313.parquet

[315/517] Downloading comiset_parquet/part-00314.parquet

[316/517] Downloading comiset_parquet/part-00315.parquet

[317/517] Downloading comiset_parquet/part-00316.parquet

[318/517] Downloading comiset_parquet/part-00317.parquet

[319/517] Downloading comiset_parquet/part-00318.parquet

[320/517] Downloading comiset_parquet/part-00319.parquet

[321/517] Downloading comiset_parquet/part-00320.parquet

[322/517] Downloading comiset_parquet/part-00321.parquet

[323/517] Downloading comiset_parquet/part-00322.parquet

[324/517] Downloading comiset_parquet/part-00323.parquet

[325/517] Downloading comiset_parquet/part-00324.parquet

[326/517] Downloading comiset_parquet/part-00325.parquet

[327/517] Downloading comiset_parquet/part-00326.parquet

[328/517] Downloading comiset_parquet/part-00327.parquet

[329/517] Downloading comiset_parquet/part-00328.parquet

[330/517] Downloading comiset_parquet/part-00329.parquet

[331/517] Downloading comiset_parquet/part-00330.parquet

[332/517] Downloading comiset_parquet/part-00331.parquet

[333/517] Downloading comiset_parquet/part-00332.parquet

[334/517] Downloading comiset_parquet/part-00333.parquet

[335/517] Downloading comiset_parquet/part-00334.parquet

[336/517] Downloading comiset_parquet/part-00335.parquet

[337/517] Downloading comiset_parquet/part-00336.parquet

[338/517] Downloading comiset_parquet/part-00337.parquet

[339/517] Downloading comiset_parquet/part-00338.parquet

[340/517] Downloading comiset_parquet/part-00339.parquet

[341/517] Downloading comiset_parquet/part-00340.parquet

[342/517] Downloading comiset_parquet/part-00341.parquet

[343/517] Downloading comiset_parquet/part-00342.parquet

[344/517] Downloading comiset_parquet/part-00343.parquet

[345/517] Downloading comiset_parquet/part-00344.parquet

[346/517] Downloading comiset_parquet/part-00345.parquet

[347/517] Downloading comiset_parquet/part-00346.parquet

[348/517] Downloading comiset_parquet/part-00347.parquet

[349/517] Downloading comiset_parquet/part-00348.parquet

[350/517] Downloading comiset_parquet/part-00349.parquet

[351/517] Downloading comiset_parquet/part-00350.parquet

[352/517] Downloading comiset_parquet/part-00351.parquet

[353/517] Downloading comiset_parquet/part-00352.parquet

[354/517] Downloading comiset_parquet/part-00353.parquet

[355/517] Downloading comiset_parquet/part-00354.parquet

[356/517] Downloading comiset_parquet/part-00355.parquet

[357/517] Downloading comiset_parquet/part-00356.parquet

[358/517] Downloading comiset_parquet/part-00357.parquet

[359/517] Downloading comiset_parquet/part-00358.parquet

[360/517] Downloading comiset_parquet/part-00359.parquet

[361/517] Downloading comiset_parquet/part-00360.parquet

[362/517] Downloading comiset_parquet/part-00361.parquet

[363/517] Downloading comiset_parquet/part-00362.parquet

[364/517] Downloading comiset_parquet/part-00363.parquet

[365/517] Downloading comiset_parquet/part-00364.parquet

[366/517] Downloading comiset_parquet/part-00365.parquet

[367/517] Downloading comiset_parquet/part-00366.parquet

[368/517] Downloading comiset_parquet/part-00367.parquet

[369/517] Downloading comiset_parquet/part-00368.parquet

[370/517] Downloading comiset_parquet/part-00369.parquet

[371/517] Downloading comiset_parquet/part-00370.parquet

[372/517] Downloading comiset_parquet/part-00371.parquet

[373/517] Downloading comiset_parquet/part-00372.parquet

[374/517] Downloading comiset_parquet/part-00373.parquet

[375/517] Downloading comiset_parquet/part-00374.parquet

[376/517] Downloading comiset_parquet/part-00375.parquet

[377/517] Downloading comiset_parquet/part-00376.parquet

[378/517] Downloading comiset_parquet/part-00377.parquet

[379/517] Downloading comiset_parquet/part-00378.parquet

[380/517] Downloading comiset_parquet/part-00379.parquet

[381/517] Downloading comiset_parquet/part-00380.parquet

[382/517] Downloading comiset_parquet/part-00381.parquet

[383/517] Downloading comiset_parquet/part-00382.parquet

[384/517] Downloading comiset_parquet/part-00383.parquet

[385/517] Downloading comiset_parquet/part-00384.parquet

[386/517] Downloading comiset_parquet/part-00385.parquet

[387/517] Downloading comiset_parquet/part-00386.parquet

[388/517] Downloading comiset_parquet/part-00387.parquet

[389/517] Downloading comiset_parquet/part-00388.parquet

[390/517] Downloading comiset_parquet/part-00389.parquet

[391/517] Downloading comiset_parquet/part-00390.parquet

[392/517] Downloading comiset_parquet/part-00391.parquet

[393/517] Downloading comiset_parquet/part-00392.parquet

[394/517] Downloading comiset_parquet/part-00393.parquet

[395/517] Downloading comiset_parquet/part-00394.parquet

[396/517] Downloading comiset_parquet/part-00395.parquet

[397/517] Downloading comiset_parquet/part-00396.parquet

[398/517] Downloading comiset_parquet/part-00397.parquet

[399/517] Downloading comiset_parquet/part-00398.parquet

[400/517] Downloading comiset_parquet/part-00399.parquet

[401/517] Downloading comiset_parquet/part-00400.parquet

[402/517] Downloading comiset_parquet/part-00401.parquet

[403/517] Downloading comiset_parquet/part-00402.parquet

[404/517] Downloading comiset_parquet/part-00403.parquet

[405/517] Downloading comiset_parquet/part-00404.parquet

[406/517] Downloading comiset_parquet/part-00405.parquet

[407/517] Downloading comiset_parquet/part-00406.parquet

[408/517] Downloading comiset_parquet/part-00407.parquet

[409/517] Downloading comiset_parquet/part-00408.parquet

[410/517] Downloading comiset_parquet/part-00409.parquet

[411/517] Downloading comiset_parquet/part-00410.parquet

[412/517] Downloading comiset_parquet/part-00411.parquet

[413/517] Downloading comiset_parquet/part-00412.parquet

[414/517] Downloading comiset_parquet/part-00413.parquet

[415/517] Downloading comiset_parquet/part-00414.parquet

[416/517] Downloading comiset_parquet/part-00415.parquet

[417/517] Downloading comiset_parquet/part-00416.parquet

[418/517] Downloading comiset_parquet/part-00417.parquet

[419/517] Downloading comiset_parquet/part-00418.parquet

[420/517] Downloading comiset_parquet/part-00419.parquet

[421/517] Downloading comiset_parquet/part-00420.parquet

[422/517] Downloading comiset_parquet/part-00421.parquet

[423/517] Downloading comiset_parquet/part-00422.parquet

[424/517] Downloading comiset_parquet/part-00423.parquet

[425/517] Downloading comiset_parquet/part-00424.parquet

[426/517] Downloading comiset_parquet/part-00425.parquet

[427/517] Downloading comiset_parquet/part-00426.parquet

[428/517] Downloading comiset_parquet/part-00427.parquet

[429/517] Downloading comiset_parquet/part-00428.parquet

[430/517] Downloading comiset_parquet/part-00429.parquet

[431/517] Downloading comiset_parquet/part-00430.parquet

[432/517] Downloading comiset_parquet/part-00431.parquet

[433/517] Downloading comiset_parquet/part-00432.parquet

[434/517] Downloading comiset_parquet/part-00433.parquet

[435/517] Downloading comiset_parquet/part-00434.parquet

[436/517] Downloading comiset_parquet/part-00435.parquet

[437/517] Downloading comiset_parquet/part-00436.parquet

[438/517] Downloading comiset_parquet/part-00437.parquet

[439/517] Downloading comiset_parquet/part-00438.parquet

[440/517] Downloading comiset_parquet/part-00439.parquet

[441/517] Downloading comiset_parquet/part-00440.parquet

[442/517] Downloading comiset_parquet/part-00441.parquet

[443/517] Downloading comiset_parquet/part-00442.parquet

[444/517] Downloading comiset_parquet/part-00443.parquet

[445/517] Downloading comiset_parquet/part-00444.parquet

[446/517] Downloading comiset_parquet/part-00445.parquet

[447/517] Downloading comiset_parquet/part-00446.parquet

[448/517] Downloading comiset_parquet/part-00447.parquet

[449/517] Downloading comiset_parquet/part-00448.parquet

[450/517] Downloading comiset_parquet/part-00449.parquet

[451/517] Downloading comiset_parquet/part-00450.parquet

[452/517] Downloading comiset_parquet/part-00451.parquet

[453/517] Downloading comiset_parquet/part-00452.parquet

[454/517] Downloading comiset_parquet/part-00453.parquet

[455/517] Downloading comiset_parquet/part-00454.parquet

[456/517] Downloading comiset_parquet/part-00455.parquet

[457/517] Downloading comiset_parquet/part-00456.parquet

[458/517] Downloading comiset_parquet/part-00457.parquet

[459/517] Downloading comiset_parquet/part-00458.parquet

[460/517] Downloading comiset_parquet/part-00459.parquet

[461/517] Downloading comiset_parquet/part-00460.parquet

[462/517] Downloading comiset_parquet/part-00461.parquet

[463/517] Downloading comiset_parquet/part-00462.parquet

[464/517] Downloading comiset_parquet/part-00463.parquet

[465/517] Downloading comiset_parquet/part-00464.parquet

[466/517] Downloading comiset_parquet/part-00465.parquet

[467/517] Downloading comiset_parquet/part-00466.parquet

[468/517] Downloading comiset_parquet/part-00467.parquet

[469/517] Downloading comiset_parquet/part-00468.parquet

[470/517] Downloading comiset_parquet/part-00469.parquet

[471/517] Downloading comiset_parquet/part-00470.parquet

[472/517] Downloading comiset_parquet/part-00471.parquet

[473/517] Downloading comiset_parquet/part-00472.parquet

[474/517] Downloading comiset_parquet/part-00473.parquet

[475/517] Downloading comiset_parquet/part-00474.parquet

[476/517] Downloading comiset_parquet/part-00475.parquet

[477/517] Downloading comiset_parquet/part-00476.parquet

[478/517] Downloading comiset_parquet/part-00477.parquet

[479/517] Downloading comiset_parquet/part-00478.parquet

[480/517] Downloading comiset_parquet/part-00479.parquet

[481/517] Downloading comiset_parquet/part-00480.parquet

[482/517] Downloading comiset_parquet/part-00481.parquet

[483/517] Downloading comiset_parquet/part-00482.parquet

[484/517] Downloading comiset_parquet/part-00483.parquet

[485/517] Downloading comiset_parquet/part-00484.parquet

[486/517] Downloading comiset_parquet/part-00485.parquet

[487/517] Downloading comiset_parquet/part-00486.parquet

[488/517] Downloading comiset_parquet/part-00487.parquet

[489/517] Downloading comiset_parquet/part-00488.parquet

[490/517] Downloading comiset_parquet/part-00489.parquet

[491/517] Downloading comiset_parquet/part-00490.parquet

[492/517] Downloading comiset_parquet/part-00491.parquet

[493/517] Downloading comiset_parquet/part-00492.parquet

[494/517] Downloading comiset_parquet/part-00493.parquet

[495/517] Downloading comiset_parquet/part-00494.parquet

[496/517] Downloading comiset_parquet/part-00495.parquet

[497/517] Downloading comiset_parquet/part-00496.parquet

[498/517] Downloading comiset_parquet/part-00497.parquet

[499/517] Downloading comiset_parquet/part-00498.parquet

[500/517] Downloading comiset_parquet/part-00499.parquet

[501/517] Downloading comiset_parquet/part-00500.parquet

[502/517] Downloading comiset_parquet/part-00501.parquet

[503/517] Downloading comiset_parquet/part-00502.parquet

[504/517] Downloading comiset_parquet/part-00503.parquet

[505/517] Downloading comiset_parquet/part-00504.parquet

[506/517] Downloading comiset_parquet/part-00505.parquet

[507/517] Downloading comiset_parquet/part-00506.parquet

[508/517] Downloading comiset_parquet/part-00507.parquet

[509/517] Downloading comiset_parquet/part-00508.parquet

[510/517] Downloading comiset_parquet/part-00509.parquet

[511/517] Downloading comiset_parquet/part-00510.parquet

[512/517] Downloading comiset_parquet/part-00511.parquet

[513/517] Downloading comiset_parquet/part-00512.parquet

[514/517] Downloading comiset_parquet/part-00513.parquet

[515/517] Downloading comiset_parquet/part-00514.parquet

[516/517] Downloading comiset_parquet/part-00515.parquet

[517/517] Downloading comiset_parquet/part-00516.parquet

Finished.

==========================================================================================================================================================================================================================================================================================================================================================

In [ ]:
import gzip
import json
from collections import Counter

PATH = "/content/comiset_lab_subset.jsonl.gz"
N = 1000_000

key_counts = Counter()

with gzip.open(PATH, "rt", encoding="utf-8") as f:
    for i, line in enumerate(f):
        if i >= N:
            break

        event = json.loads(line)
        key_counts.update(event["_source"].keys())

print(f"{len(key_counts)} unique keys\n")
j = 0
for key, count in key_counts.most_common():
    j += 1
    percentage = count / N * 100
    print(f"{j} {percentage:6.2f}%  {count:5,}  {key}")

1097 unique keys

1 100.00%  1,000,000  event_original_time
2 100.00%  1,000,000  type
3 100.00%  1,000,000  @timestamp
4 100.00%  1,000,000  host_name
5 100.00%  1,000,000  level
6 100.00%  1,000,000  etl_host_agent_type
7 100.00%  1,000,000  etl_pipeline
8 100.00%  1,000,000  etl_host_agent_ephemeral_uid
9 100.00%  1,000,000  @version
10 100.00%  1,000,000  z_elastic_ecs
11 100.00%  1,000,000  event_id
12 100.00%  1,000,000  log_name
13 100.00%  1,000,000  record_number
14 100.00%  1,000,000  beat_name
15 100.00%  1,000,000  etl_host_agent_uid
16 100.00%  1,000,000  source_name
17 100.00%  1,000,000  beat_version
18 100.00%  999,994  task
19  99.98%  999,828  etl_processed_time
20  99.98%  999,828  event_original_message
21  99.98%  999,828  etl_version
22  99.89%  998,930  opcode
23  99.40%  994,044  provider_guid
24  98.96%  989,597  process_id
25  98.96%  989,597  thread_id
26  80.91%  809,148  process_path
27  80.91%  809,148  process_name
28  80.47%  804,747  version
29  79.27%  792,663  RuleName
30  78.45%  784,483  event_recorded_time
31  78.45%  784,483  event_timezone
32  78.43%  784,274  process_guid
33  63.51%  635,080  user_name
34  63.51%  635,080  user_domain
35  63.51%  635,080  meta_user_name_is_machine
36  61.24%  612,355  user_account
37  60.53%  605,348  EventType
38  60.20%  602,035  TargetObject
39  17.19%  171,946  target_process_name
40  17.19%  171,946  target_process_path
41  17.19%  171,946  target_process_id
42  17.19%  171,919  SourceUser
43  17.19%  171,919  target_process_guid
44  17.19%  171,919  TargetUser
45  17.16%  171,605  CallTrace
46  17.16%  171,605  SourceThreadId
47  17.16%  171,605  GrantedAccess
48  16.19%  161,918  keywords
49   7.11%  71,147  Message
50   7.05%  70,546  Line Number
51   6.83%  68,326  Source
52   6.82%  68,207  Function
53   4.81%  48,062  activity_id
54   4.70%  47,042  Error Code
55   3.07%  30,699  TaskName
56   2.51%  25,058  process_id_orig
57   2.48%  24,804  CorrelationVector
58   2.16%  21,557  user_sid
59   2.16%  21,557  user_logon_id
60   2.05%  20,521  object_server
61   2.05%  20,520  object_type
62   2.05%  20,505  object_handle_id
63   2.05%  20,504  object_name
64   2.05%  20,500  object_new_sd
65   1.86%  18,564  ProductId
66   1.55%  15,492  object_old_sd
67   1.31%  13,070  SubjectLogonId
68   1.31%  13,070  SubjectUserSid
69   1.21%  12,106  SubjectDomainName
70   1.21%  12,106  SubjectUserName
71   1.11%  11,109  rule_technique_name
72   1.11%  11,068  rule_technique_id
73   0.96%  9,562  State Machine Name
74   0.96%  9,562  Thread ID
75   0.96%  9,562  State Machine
76   0.92%  9,239  InstanceId
77   0.90%  8,987  param1
78   0.85%  8,455  logon_type
79   0.84%  8,448  TaskInstanceId
80   0.84%  8,396  ModifyingUser
81   0.82%  8,194  ModifyingApplication
82   0.82%  8,183  RuleId
83   0.82%  8,181  TargetUserName
84   0.82%  8,162  TargetDomainName
85   0.81%  8,090  param2
86   0.80%  8,042  Details
87   0.80%  7,992  Current State
88   0.74%  7,375  UserContext
89   0.70%  7,041  EnginePID
90   0.67%  6,689  ActionName
91   0.58%  5,837  Flags
92   0.58%  5,833  ResultCode
93   0.58%  5,768  xml_name
94   0.54%  5,397  Event Name
95   0.53%  5,291  Protocol
96   0.50%  4,979  UserName
97   0.50%  4,965  param3
98   0.48%  4,837  Origin
99   0.48%  4,793  TargetFilename
100   0.47%  4,730  Action
101   0.47%  4,722  SchemaVersion
102   0.47%  4,721  Profiles
103   0.47%  4,719  Active
104   0.47%  4,719  LocalOnlyMapped
105   0.47%  4,719  Direction
106   0.47%  4,719  SecurityOptions
107   0.47%  4,719  RemoteAddresses
108   0.47%  4,719  RuleStatus
109   0.47%  4,719  EdgeTraversal
110   0.47%  4,719  LooseSourceMapped
111   0.47%  4,719  LocalAddresses
112   0.47%  4,665  EmbeddedContext
113   0.42%  4,203  TargetUserSid
114   0.42%  4,189  LogonGuid
115   0.42%  4,180  TargetLogonId
116   0.40%  3,992  param4
117   0.40%  3,986  Id
118   0.39%  3,912  param5
119   0.39%  3,902  param6
120   0.39%  3,880  ClientProcessId
121   0.39%  3,869  ProcessID
122   0.38%  3,776  Status
123   0.37%  3,668  DeviceInstanceId
124   0.36%  3,628  file_creation_time
125   0.36%  3,564  TargetSid
126   0.35%  3,540  CallerProcessName
127   0.35%  3,540  CallerProcessId
128   0.33%  3,313  PipeName
129   0.32%  3,173  TunnelID
130   0.31%  3,083  ErrorCode
131   0.30%  3,048  ClassGuid
132   0.30%  3,046  KeyLength
133   0.30%  3,046  LogonProcessName
134   0.30%  3,023  TargetLinkedLogonId
135   0.30%  3,023  ImpersonationLevel
136   0.30%  3,023  VirtualAccount
137   0.30%  3,023  ElevatedToken
138   0.30%  3,017  ChannelName
139   0.30%  2,973  AuthenticationPackageName
140   0.30%  2,958  Path
141   0.29%  2,907  hash_imphash
142   0.29%  2,907  hash_md5
143   0.29%  2,907  hash_sha256
144   0.29%  2,907  hash_sha1
145   0.28%  2,828  Priority
146   0.27%  2,714  DriverName
147   0.26%  2,606  PrivilegeList
148   0.26%  2,552  User
149   0.25%  2,531  updateRevisionNumber
150   0.25%  2,531  updateGuid
151   0.25%  2,454  Operation
152   0.25%  2,451  serviceGuid
153   0.22%  2,222  Name
154   0.22%  2,215  New State
155   0.22%  2,201  PossibleCause
156   0.22%  2,199  bytesTransferred
157   0.22%  2,199  bytesTransferredFromPeer
158   0.22%  2,162  IsMachine
159   0.21%  2,141  ClientMachine
160   0.21%  2,116  Component
161   0.21%  2,089  Type
162   0.19%  1,859  InfoDescription
163   0.18%  1,808  z_logstash_pipeline
164   0.18%  1,779  ProcessCreationTime
165   0.18%  1,777  ReturnCode
166   0.18%  1,753  name
167   0.18%  1,753  url
168   0.18%  1,753  transferId
169   0.18%  1,753  fileLength
170   0.18%  1,753  bytesTotal
171   0.18%  1,753  fileTime
172   0.17%  1,725  CountOfCredentialsReturned
173   0.17%  1,723  TargetName
174   0.17%  1,723  ReadOperation
175   0.16%  1,566  Value
176   0.15%  1,536  Description
177   0.15%  1,536  Product
178   0.15%  1,536  Company
179   0.15%  1,536  OriginalFileName
180   0.15%  1,536  FileVersion
181   0.15%  1,493  PortNumber
182   0.15%  1,493  AdapterGuid
183   0.15%  1,493  MiniportName
184   0.15%  1,479  Problem
185   0.14%  1,440  NameLength
186   0.14%  1,399  PathID
187   0.14%  1,399  TargetID
188   0.14%  1,399  LUN
189   0.13%  1,342  Event
190   0.13%  1,335  ClassDeviceGuid
191   0.13%  1,299  SubscriberName
192   0.13%  1,271  BootDevice
193   0.13%  1,268  src_ip_addr
194   0.13%  1,268  src_ip_type
195   0.13%  1,268  src_is_ipv6
196   0.13%  1,268  src_ip_public
197   0.13%  1,268  src_ip_rfc
198   0.13%  1,268  src_ip_version
199   0.13%  1,261  PackageFamilyName
200   0.12%  1,243  Signature
201   0.12%  1,242  ImageLoaded
202   0.12%  1,242  SignatureStatus
203   0.12%  1,242  Signed
204   0.12%  1,235  InstallState
205   0.12%  1,220  LicenseId
206   0.12%  1,170  OperationDescription
207   0.12%  1,168  DriverSection
208   0.12%  1,168  DriverRank
209   0.12%  1,168  DriverDate
210   0.12%  1,168  DriverProvider
211   0.12%  1,168  DriverInbox
212   0.12%  1,168  DriverVersion
213   0.12%  1,168  MatchingDeviceId
214   0.12%  1,168  DeviceUpdated
215   0.12%  1,165  IsExecutable
216   0.11%  1,131  Archived
217   0.11%  1,129  PackageName
218   0.11%  1,128  process_parent_name
219   0.11%  1,128  process_parent_path
220   0.11%  1,094  ParentDeviceInstanceId
221   0.10%  1,030  key_name
222   0.10%  1,030  key_algorithm_name
223   0.10%  1,030  key_type
224   0.10%  1,030  key_provider_name
225   0.10%  1,030  key_operation
226   0.10%  1,030  key_return_code
227   0.10%  1,013  Code
228   0.10%  1,008  ProviderName
229   0.10%  1,008  HostProcess
230   0.10%  1,008  ProviderPath
231   0.10%    992  jobId
232   0.10%    969  Parameter1Value
233   0.10%    969  MiniportEventId
234   0.10%    969  Parameter1Name
235   0.10%    969  Parameter2Name
236   0.10%    969  MiniportEventDescription
237   0.10%    969  Parameter2Value
238   0.09%    940  AssociateId
239   0.09%    937  Parameter4Name
240   0.09%    937  Parameter3Name
241   0.09%    937  Parameter3Value
242   0.09%    937  Parameter4Value
243   0.09%    916  IfIndex
244   0.09%    910  Info
245   0.09%    898  ServiceName
246   0.09%    886  UserId
247   0.09%    884  Parameter8Name
248   0.09%    884  Parameter8Value
249   0.09%    884  Parameter6Name
250   0.09%    884  Parameter5Name
251   0.09%    884  Parameter6Value
252   0.09%    884  Parameter7Value
253   0.09%    884  Parameter7Name
254   0.09%    884  Parameter5Value
255   0.09%    883  ServerName
256   0.08%    840  bandwidthLimit
257   0.08%    840  hr
258   0.08%    840  PeerContextInfo
259   0.08%    840  ignoreBandwidthLimitsOnLan
260   0.08%    840  peerProtocolFlags
261   0.08%    840  AdditionalInfoHr
262   0.08%    825  Command
263   0.08%    809  jobTitle
264   0.08%    808  jobOwner
265   0.08%    801  MethodName
266   0.08%    789  IsBackgroundProcessing
267   0.08%    789  IsAsyncProcessing
268   0.08%    788  ScriptBlockText
269   0.08%    788  MessageTotal
270   0.08%    788  MessageNumber
271   0.08%    788  ScriptBlockId
272   0.08%    775  src_original_value
273   0.07%    734  ServerNameLength
274   0.07%    722  TokenElevationType
275   0.07%    722  MandatoryLabel
276   0.07%    684  fileCount
277   0.07%    683  hc_stateid
278   0.07%    666  TargetInfo
279   0.07%    666  TargetLogonGuid
280   0.07%    666  TargetServerName
281   0.06%    616  Process Name
282   0.06%    616  IpPort
283   0.06%    594  SessionID
284   0.06%    585  SessionId
285   0.06%    582  OperationElaspedTimeInMilliSeconds
286   0.06%    574  LogonId
287   0.05%    542  IsServiceRestart
288   0.05%    542  ReasonCode
289   0.05%    541  Reason
290   0.05%    540  AppID
291   0.05%    534  QueuedTaskInstanceId
292   0.05%    524  TransportNameLength
293   0.05%    524  DomainNameLength
294   0.05%    524  TransportName
295   0.05%    523  param7
296   0.05%    519  SessionTimeElapsedInMilliseconds
297   0.05%    504  Product Name
298   0.05%    500  process_parent_id
299   0.05%    500  IntegrityLevel
300   0.05%    500  TerminalSessionId
301   0.05%    500  ParentUser
302   0.05%    500  CommandLine
303   0.05%    500  process_parent_guid
304   0.05%    500  ParentCommandLine
305   0.05%    500  CurrentDirectory
306   0.05%    498  WinlogonReturnTimeElapsedInMilliseconds
307   0.05%    497  Workstation
308   0.05%    486  Module Name
309   0.05%    486  Build Name
310   0.05%    486  DestinationHostname
311   0.05%    486  SourceHostname
312   0.05%    486  Initiated
313   0.05%    486  dst_ip_addr
314   0.05%    486  SourcePort
315   0.05%    486  SourceIsIpv6
316   0.05%    486  dst_is_ipv6
317   0.05%    486  dst_ip_rfc
318   0.05%    486  dst_ip_public
319   0.05%    486  DestinationPortName
320   0.05%    486  DestinationIsIpv6
321   0.05%    486  DestinationPort
322   0.05%    486  dst_ip_version
323   0.05%    486  SourcePortName
324   0.05%    486  dst_ip_type
325   0.05%    480  NotificationType
326   0.05%    473  PrincipalSamName
327   0.05%    470  string2
328   0.05%    470  string
329   0.05%    465  HasFlowUrl
330   0.05%    465  Expires
331   0.05%    465  AuthRequired
332   0.05%    465  ResourceURI
333   0.05%    465  Created
334   0.05%    465  RequestStatus
335   0.05%    465  HasEndAuthUrl
336   0.05%    465  TokenType
337   0.05%    465  HasAuthUrl
338   0.05%    465  TickCount
339   0.05%    462  VendorId
340   0.05%    453  InterfaceGuid
341   0.05%    453  InterfaceName
342   0.05%    453  NewProfile
343   0.05%    453  OldProfile
344   0.04%    435  LastRunDateTime
345   0.04%    422  param8
346   0.04%    418  updateTitle
347   0.04%    405  Product Version
348   0.04%    404  Session
349   0.04%    401  LastDeviceInstanceId
350   0.04%    401  MigrationRank
351   0.04%    401  Present
352   0.04%    397  DomainName
353   0.04%    397  TransportFlags
354   0.04%    390  BusType
355   0.04%    385  Namespace
356   0.04%    384  process_creation_time
357   0.04%    380  Version
358   0.04%    377  key_file_path
359   0.04%    369  CustomLevel
360   0.03%    338  Provider
361   0.03%    337  KeyName
362   0.03%    336  updateCount
363   0.03%    314  StartModule
364   0.03%    314  StartFunction
365   0.03%    314  StartAddress
366   0.03%    314  NewThreadId
367   0.03%    312  ConnectionName
368   0.03%    307  tags
369   0.03%    305  File Name
370   0.03%    302  IsMachineBoot
371   0.03%    301  Address
372   0.03%    300  HRESULT
373   0.03%    297  PID
374   0.03%    293  param9
375   0.03%    288  GpsvcInitTimeElapsedInMilliseconds
376   0.03%    279  OperationParameter1
377   0.03%    275  not_ip_src
378   0.03%    275  ClientAddressLength
379   0.03%    271  SerialNumber
380   0.03%    267  Member Name
381   0.03%    266  Capability
382   0.03%    266  InterfaceIndex
383   0.03%    266  NetName
384   0.03%    266  ChangeType
385   0.03%    266  NetNameLength
386   0.03%    266  LinkSpeed
387   0.03%    255  PolicyApplicationMode
388   0.02%    245  Port
389   0.02%    241  TaskEngineName
390   0.02%    240  IsDomainJoined
391   0.02%    240  ReasonForSyncProcessing
392   0.02%    240  PolicyActivityId
393   0.02%    237  processId
394   0.02%    237  ClientProcessStartKey
395   0.02%    234  param10
396   0.02%    233  PolicyElaspedTimeInSeconds
397   0.02%    233  IsConnectivityFailure
398   0.02%    229  param11
399   0.02%    220  listenerName
400   0.02%    213  Hash
401   0.02%    212  OutrankedDrivers
402   0.02%    212  Contents
403   0.02%    211  ErrorDescription
404   0.02%    211  param19
405   0.02%    211  param20
406   0.02%    211  param21
407   0.02%    207  SystemUptime_s
408   0.02%    199  param16
409   0.02%    192  File
410   0.02%    187  WaitDuration_ms
411   0.02%    187  QueueDepth
412   0.02%    187  IoSize
413   0.02%    187  LBA
414   0.02%    187  RequestDuration_ms
415   0.02%    186  ApplicationPath
416   0.02%    183  isRoaming
417   0.02%    183  jobName
418   0.02%    182  Binary
419   0.02%    181  VolumeName
420   0.02%    181  VolumeNameLength
421   0.02%    181  QueryResults
422   0.02%    181  QueryName
423   0.02%    181  QueryStatus
424   0.02%    177  SID
425   0.02%    177  Domain
426   0.02%    174  param17
427   0.02%    169  WorkstationName
428   0.02%    162  IdleSeconds2
429   0.02%    162  IdleSeconds1
430   0.02%    162  IdleSeconds
431   0.02%    159  TransportProtocolName
432   0.02%    159  ConnType
433   0.02%    159  port_src
434   0.02%    158  FunctionName
435   0.02%    158  ReasonString
436   0.02%    156  TransportType
437   0.02%    153  param12
438   0.02%    151  DebugOutput
439   0.01%    148  InstanceID
440   0.01%    148  ScsiStatus
441   0.01%    148  SrbStatus
442   0.01%    148  SenseKey
443   0.01%    148  AddSenseQ
444   0.01%    148  AddSense
445   0.01%    148  TargetOutboundUserName
446   0.01%    148  TargetOutboundDomainName
447   0.01%    144  operationName
448   0.01%    144  AdapterSerialNumber
449   0.01%    143  Param1
450   0.01%    142  Key
451   0.01%    138  State
452   0.01%    137  IsBootVolume
453   0.01%    132  Error Description
454   0.01%    131  binaryDataSize
455   0.01%    131  binaryData
456   0.01%    130  Severity ID
457   0.01%    130  Action Name
458   0.01%    130  Type ID
459   0.01%    130  Origin ID
460   0.01%    130  Category ID
461   0.01%    130  Detection ID
462   0.01%    130  Source Name
463   0.01%    130  Engine Version
464   0.01%    130  Category Name
465   0.01%    130  Severity Name
466   0.01%    130  Additional Actions ID
467   0.01%    130  Status Code
468   0.01%    130  Origin Name
469   0.01%    130  Threat ID
470   0.01%    130  Execution Name
471   0.01%    130  Source ID
472   0.01%    130  Pre Execution Status
473   0.01%    130  Type Name
474   0.01%    130  Detection Time
475   0.01%    130  Additional Actions String
476   0.01%    130  Threat Name
477   0.01%    130  Action ID
478   0.01%    130  Execution ID
479   0.01%    130  Post Clean Status
480   0.01%    130  FWLink
481   0.01%    129  Configuration
482   0.01%    124  ExitCode
483   0.01%    121  TimeProviders
484   0.01%    119  AddressLength
485   0.01%    118  SettingValue
486   0.01%    118  SettingValueSize
487   0.01%    118  SettingType
488   0.01%    118  DescriptionString
489   0.01%    116  SettingValueDisplay
490   0.01%    114  Scenario
491   0.01%    114  LowestFreeSpaceInBytes
492   0.01%    114  HighestFreeSpaceInBytes
493   0.01%    114  VolumeGuid
494   0.01%    113  Query
495   0.01%    112  RemoteName
496   0.01%    112  LocalName
497   0.01%    110  ConnectionType
498   0.01%    108  ExtraInfo
499   0.01%    107  MinorType
500   0.01%    107  MajorType
501   0.01%    107  StatusCode
502   0.01%    102  RunningTaskInstanceId
503   0.01%    102  InstancePath
504   0.01%     99  Engine version
505   0.01%     99  Platform version
506   0.01%     96  LoggingMode
507   0.01%     96  SessionName
508   0.01%     96  param23
509   0.01%     95  PreviousTime
510   0.01%     95  NewTime
511   0.01%     94  HierarchicalResetSuccessCount
512   0.01%     94  LastError_Command
513   0.01%     94  LastError_SrbStatus
514   0.01%     94  LastError_SenseKey
515   0.01%     94  TotalDeviceFailureErrors
516   0.01%     94  UniqueErrorLogArrayLength
517   0.01%     94  TotalErrors
518   0.01%     94  LastError_QueueDepth
519   0.01%     94  SampledErrorLogArrayLength
520   0.01%     94  TotalReadWriteErrors
521   0.01%     94  LastError_AddSenseQ
522   0.01%     94  LastError_ScsiStatus
523   0.01%     94  LastError_RequestDuration_ms
524   0.01%     94  TimeoutsInMiniport
525   0.01%     94  UniqueErrorLogArray
526   0.01%     94  TotalImpendingDeviceFailureErrors
527   0.01%     94  LastError_AddSense
528   0.01%     94  LastError_WaitDuration_ms
529   0.01%     94  LastError_LBA
530   0.01%     94  LastError_IoSize
531   0.01%     94  MaxUnmapLatency_100ns
532   0.01%     94  BucketIoFailed7
533   0.01%     94  TotalDeviceQueueIoCount
534   0.01%     94  BucketIoSuccess2
535   0.01%     94  MaxDeviceQueueIoWaitDuration_100ns
536   0.01%     94  BucketIoSuccess7
537   0.01%     94  BucketIoLatency7_100ns
538   0.01%     94  DeviceQueueIoWaitExceededTimeoutCount
539   0.01%     94  BucketIoLatency9_100ns
540   0.01%     94  BucketIoFailed2
541   0.01%     94  BucketIoFailed5
542   0.01%     94  MaxFlushLatency_100ns
543   0.01%     94  MaxOutstandingCount
544   0.01%     94  BucketIoSuccess10
545   0.01%     94  BucketIoFailed4
546   0.01%     94  TotalIoCount
547   0.01%     94  BucketIoLatency3_100ns
548   0.01%     94  BucketIoSuccess8
549   0.01%     94  BucketIoFailed11
550   0.01%     94  MaxReadWriteLatency_100ns
551   0.01%     94  HighLatencyIoCount
552   0.01%     94  BucketIoLatency11_100ns
553   0.01%     94  BucketIoLatency8_100ns
554   0.01%     94  BucketIoLatency6_100ns
555   0.01%     94  BucketIoSuccess12
556   0.01%     94  DeviceQueueIoUntaggedCommandOutstandingCount
557   0.01%     94  BucketIoFailed1
558   0.01%     94  BucketIoSuccess5
559   0.01%     94  BucketIoSuccess3
560   0.01%     94  BucketIoFailed9
561   0.01%     94  BucketIoFailed6
562   0.01%     94  BucketIoLatency12_100ns
563   0.01%     94  FirmwareRevision
564   0.01%     94  BucketIoSuccess9
565   0.01%     94  DeviceQueueIoBusyCount
566   0.01%     94  IoLatencyBuckets
567   0.01%     94  DeviceQueueIoPausedForUntaggedCount
568   0.01%     94  BucketIoLatency1_100ns
569   0.01%     94  BucketIoLatency2_100ns
570   0.01%     94  BucketIoLatency4_100ns
571   0.01%     94  BucketIoSuccess11
572   0.01%     94  TotalDeviceQueueIoWaitDuration_100ns
573   0.01%     94  BucketIoFailed10
574   0.01%     94  TotalWriteBytes
575   0.01%     94  BucketIoSuccess4
576   0.01%     94  MaxDeviceQueueCount
577   0.01%     94  BucketIoLatency10_100ns
578   0.01%     94  BucketIoLatency5_100ns
579   0.01%     94  TotalReadBytes
580   0.01%     94  BucketIoFailed12
581   0.01%     94  BucketIoFailed3
582   0.01%     94  BucketIoFailed8
583   0.01%     94  BucketIoSuccess1
584   0.01%     94  IoTimeout_s
585   0.01%     94  DeviceQueueIoPausedCount

In [ ]:
import gzip
import json
from collections import Counter, defaultdict

PATH = "/content/comiset_lab_subset.jsonl.gz"

N = 1000_000  # increase later if needed

benign_counts = Counter()
malicious_counts = Counter()

benign_total = 0
malicious_total = 0

with gzip.open(PATH, "rt", encoding="utf-8") as f:
    for i, line in enumerate(f):
        if i >= N:
            break

        event = json.loads(line)
        source = event["_source"]

        # Dataset label
        malicious = bool(source.get("rule_technique_id"))

        target = malicious_counts if malicious else benign_counts

        for key in source:
            target[key] += 1

        if malicious:
            malicious_total += 1
        else:
            benign_total += 1

print(f"Events analyzed: {benign_total + malicious_total:,}")
print(f"Benign:          {benign_total:,}")
print(f"Malicious:       {malicious_total:,}")

# Compare field presence
all_keys = set(benign_counts) | set(malicious_counts)

results = []

for key in all_keys:
    b = benign_counts[key]
    m = malicious_counts[key]

    b_pct = 100 * b / benign_total if benign_total else 0
    m_pct = 100 * m / malicious_total if malicious_total else 0

    results.append((key, b_pct, m_pct, m_pct - b_pct))

# Most characteristic of malicious events
results.sort(key=lambda x: x[3], reverse=True)

print("\nFields much more common in MALICIOUS events:")
print(f"{'Field':45} {'Benign %':>10} {'Malicious %':>12} {'Difference':>12}")
print("-" * 82)

for key, b_pct, m_pct, diff in results[:100]:
    print(f"{key[:45]:45} {b_pct:9.2f}% {m_pct:11.2f}% {diff:+11.2f}%")

Events analyzed: 1,000,000
Benign:          988,932
Malicious:       11,068

Fields much more common in MALICIOUS events:
Field                                           Benign %  Malicious %   Difference
----------------------------------------------------------------------------------
rule_technique_id                                  0.00%      100.00%     +100.00%
rule_technique_name                                0.00%       99.93%      +99.92%
user_account                                      60.85%       95.37%      +34.51%
user_domain                                       63.15%       95.37%      +32.21%
user_name                                         63.15%       95.37%      +32.21%
meta_user_name_is_machine                         63.15%       95.37%      +32.21%
Details                                            0.45%       32.08%      +31.63%
file_creation_time                                 0.08%       25.47%      +25.39%
TargetFilename                                     0.20%       25.47%      +25.27%
process_guid                                      78.19%      100.00%      +21.81%
event_recorded_time                               78.21%      100.00%      +21.79%
event_timezone                                    78.21%      100.00%      +21.79%
RuleName                                          79.03%      100.00%      +20.97%
version                                           80.26%      100.00%      +19.74%
process_path                                      80.70%      100.00%      +19.30%
process_name                                      80.70%      100.00%      +19.30%
FileVersion                                        0.04%       10.23%      +10.19%
Company                                            0.04%       10.23%      +10.19%
Description                                        0.04%       10.23%      +10.19%
OriginalFileName                                   0.04%       10.23%      +10.19%
Product                                            0.04%       10.23%      +10.19%
hash_sha1                                          0.18%       10.23%      +10.05%
hash_sha256                                        0.18%       10.23%      +10.05%
hash_imphash                                       0.18%       10.23%      +10.05%
hash_md5                                           0.18%       10.23%      +10.05%
SignatureStatus                                    0.03%        8.80%       +8.77%
Signed                                             0.03%        8.80%       +8.77%
ImageLoaded                                        0.03%        8.80%       +8.77%
Signature                                          0.03%        8.80%       +8.77%
dst_is_ipv6                                        0.02%        2.98%       +2.97%
SourceHostname                                     0.02%        2.98%       +2.97%
SourcePortName                                     0.02%        2.98%       +2.97%
dst_ip_version                                     0.02%        2.98%       +2.97%
DestinationHostname                                0.02%        2.98%       +2.97%
dst_ip_rfc                                         0.02%        2.98%       +2.97%
dst_ip_public                                      0.02%        2.98%       +2.97%
Initiated                                          0.02%        2.98%       +2.97%
SourceIsIpv6                                       0.02%        2.98%       +2.97%
dst_ip_addr                                        0.02%        2.98%       +2.97%
DestinationIsIpv6                                  0.02%        2.98%       +2.97%
DestinationPort                                    0.02%        2.98%       +2.97%
DestinationPortName                                0.02%        2.98%       +2.97%
SourcePort                                         0.02%        2.98%       +2.97%
dst_ip_type                                        0.02%        2.98%       +2.97%
src_ip_public                                      0.09%        2.98%       +2.89%
src_ip_version                                     0.09%        2.98%       +2.89%
src_is_ipv6                                        0.09%        2.98%       +2.89%
src_ip_rfc                                         0.09%        2.98%       +2.89%
src_ip_addr                                        0.09%        2.98%       +2.89%
src_ip_type                                        0.09%        2.98%       +2.89%
StartFunction                                      0.00%        2.84%       +2.84%
StartAddress                                       0.00%        2.84%       +2.84%
StartModule                                        0.00%        2.84%       +2.84%
NewThreadId                                        0.00%        2.84%       +2.84%
Protocol                                           0.50%        2.98%       +2.48%
CurrentDirectory                                   0.03%        1.43%       +1.39%
CommandLine                                        0.03%        1.43%       +1.39%
TerminalSessionId                                  0.03%        1.43%       +1.39%
process_parent_guid                                0.03%        1.43%       +1.39%
ParentUser                                         0.03%        1.43%       +1.39%
ParentCommandLine                                  0.03%        1.43%       +1.39%
process_parent_id                                  0.03%        1.43%       +1.39%
IntegrityLevel                                     0.03%        1.43%       +1.39%
LogonId                                            0.04%        1.43%       +1.39%
process_parent_name                                0.10%        1.43%       +1.33%
process_parent_path                                0.10%        1.43%       +1.33%
Contents                                           0.01%        1.29%       +1.29%
Hash                                               0.01%        1.29%       +1.28%
process_id                                        98.95%      100.00%       +1.05%
thread_id                                         98.95%      100.00%       +1.05%
LogonGuid                                          0.41%        1.43%       +1.02%
provider_guid                                     99.40%      100.00%       +0.60%
meta_dst_ip_geo                                    0.00%        0.12%       +0.12%
opcode                                            99.89%      100.00%       +0.11%
etl_version                                       99.98%      100.00%       +0.02%
etl_processed_time                                99.98%      100.00%       +0.02%
event_original_message                            99.98%      100.00%       +0.02%
task                                             100.00%      100.00%       +0.00%
beat_name                                        100.00%      100.00%       +0.00%
event_original_time                              100.00%      100.00%       +0.00%
etl_host_agent_type                              100.00%      100.00%       +0.00%
source_name                                      100.00%      100.00%       +0.00%
event_id                                         100.00%      100.00%       +0.00%
log_name                                         100.00%      100.00%       +0.00%
beat_version                                     100.00%      100.00%       +0.00%
etl_pipeline                                     100.00%      100.00%       +0.00%
@timestamp                                       100.00%      100.00%       +0.00%
host_name                                        100.00%      100.00%       +0.00%
etl_host_agent_uid                               100.00%      100.00%       +0.00%
type                                             100.00%      100.00%       +0.00%
@version                                         100.00%      100.00%       +0.00%
etl_host_agent_ephemeral_uid                     100.00%      100.00%       +0.00%
level                                            100.00%      100.00%       +0.00%
record_number                                    100.00%      100.00%       +0.00%
z_elastic_ecs                                    100.00%      100.00%       +0.00%
InterferingImageName                               0.00%        0.00%       -0.00%
number                                             0.00%        0.00%       -0.00%
PublisherName                                      0.00%        0.00%       -0.00%
ProtocolHostProcessID                              0.00%        0.00%       -0.00%
ProcessStartKey                                    0.00%        0.00%       -0.00%

=======================================================================================================================================================================================================

**download the set from kaggle:**

In [ ]:
!pip install -q -U kagglehub

In [ ]:
import kagglehub

path = kagglehub.dataset_download(
    "saifthesaif/comiset-lab-50-benign-subset"
)

print(path)

KaggleApiHTTPError: 404 Client Error.

Resource not found at URL: https://kaggle.com/datasets/saifthesaif/comiset-lab-50-benign-subset/versions/2
Please make sure you specified the correct resource identifiers.

In [ ]:
l!kaggle datasets files saifthesaif/comiset-lab-50-benign-subset

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Next Page Token = CfDJ8LXGgraiXMNClPzcySXY5U7Nsn4tkufc6zgQ0FgN5_lCRlN-lsrrwjJs1L6SUHd2F52uJ_RUumUDj_Uj0p8cdnB1FP05xyHNLeepD8jpqXxeZ4kOZUel5vUOl_hoPtAhqG9DMi6n7-ozZFq0tmewNZI1u08UvAoRvfS0UA
name                                       size  creationDate
----------------------------------  -----------  --------------------------
comiset_lab_cleaned.jsonl           76125436188  2026-09-26 00:41:53.798000
comiset_parquet/part-00000.parquet      2599803  2026-09-25 23:44:19.561000
comiset_parquet/part-00001.parquet      2579253  2026-09-25 23:44:19.622000
comiset_parquet/part-00002.parquet      2291040  2026-09-25 23:44:19.836000
comiset_parquet/part-00003.parquet      6218759  2026-09-25 23:44:21.166000
comiset_parquet/part-00004.parquet      1883988  2026-09-25 23:44:21.113000
comiset_parquet/part-00005.parquet      1869881  2026-09-25 23:44:19.798000
comiset_parquet/part-00006.parquet      1854570  2026-09-25 23:44:19.806000
comiset_parquet/part-00007.parquet      2089217  2026-09-25 23:44:19.987000
comiset_parquet/part-00008.parquet      1879040  2026-09-25 23:44:21.072000
comiset_parquet/part-00009.parquet      1845391  2026-09-25 23:44:19.935000
comiset_parquet/part-00010.parquet      1908269  2026-09-25 23:44:21.083000
comiset_parquet/part-00011.parquet      1922778  2026-09-25 23:44:21.053000
comiset_parquet/part-00012.parquet      2023496  2026-09-25 23:44:21.078000
comiset_parquet/part-00013.parquet      1900918  2026-09-25 23:44:21.088000
comiset_parquet/part-00014.parquet      1872372  2026-09-25 23:44:21.137000
comiset_parquet/part-00015.parquet      1945635  2026-09-25 23:44:21.076000
comiset_parquet/part-00016.parquet      1908748  2026-09-25 23:44:21.075000
comiset_parquet/part-00017.parquet      1889960  2026-09-25 23:44:21.074000
comiset_parquet/part-00018.parquet      1986801  2026-09-25 23:44:21.314000

In [ ]:
import json
from collections import Counter

PATH = "/content/dataset/comiset_lab_subset.jsonl"

N = 1_000_000  # increase later if needed

benign_counts = Counter()
malicious_counts = Counter()

benign_total = 0
malicious_total = 0

with open(PATH, "r", encoding="utf-8") as f:
    for i, line in enumerate(f):
        if i >= N:
            break

        event = json.loads(line)
        source = event["_source"]

        # Dataset label
        malicious = bool(source.get("rule_technique_id"))

        target = malicious_counts if malicious else benign_counts

        for key in source:
            target[key] += 1

        if malicious:
            malicious_total += 1
        else:
            benign_total += 1

print(f"Events analyzed: {benign_total + malicious_total:,}")
print(f"Benign:          {benign_total:,}")
print(f"Malicious:       {malicious_total:,}")

# Compare field presence
all_keys = set(benign_counts) | set(malicious_counts)

results = []

for key in all_keys:
    b = benign_counts[key]
    m = malicious_counts[key]

    b_pct = 100 * b / benign_total if benign_total else 0
    m_pct = 100 * m / malicious_total if malicious_total else 0

    results.append((key, b_pct, m_pct, m_pct - b_pct))

# Most characteristic of malicious events
results.sort(key=lambda x: x[3], reverse=True)

print("\nFields much more common in MALICIOUS events:")
print(f"{'Field':45} {'Benign %':>10} {'Malicious %':>12} {'Difference':>12}")
print("-" * 82)

for key, b_pct, m_pct, diff in results[:100]:
    print(f"{key[:45]:45} {b_pct:9.2f}% {m_pct:11.2f}% {diff:+11.2f}%")

KeyboardInterrupt:

In [ ]:
import json

PATH = "/content/dataset/comiset_lab_subset.jsonl"

# For each field:
# first_values[key] = first value encountered
# non_constant[key] = True if a different value is later encountered

first_values = {}
non_constant = set()

with open(PATH, "r", encoding="utf-8") as f:
    for i, line in enumerate(f):
        event = json.loads(line)
        source = event["_source"]

        for key, value in source.items():
            # First occurrence of this field
            if key not in first_values:
                first_values[key] = value

            # If we already know it varies, no need to check further
            elif key not in non_constant and value != first_values[key]:
                non_constant.add(key)

        if (i + 1) % 1_000_000 == 0:
            print(f"Processed {i + 1:,} events")

constant_cols = [
    key for key in first_values
    if key not in non_constant
]

print(f"\nTotal fields:     {len(first_values)}")
print(f"Constant fields:  {len(constant_cols)}")
print(f"Remaining fields: {len(first_values) - len(constant_cols)}")

print("\nConstant fields:")
for key in constant_cols:
    print(f"{key}: {first_values[key]!r}")

Processed 1,000,000 events
Processed 2,000,000 events
Processed 3,000,000 events
Processed 4,000,000 events
Processed 5,000,000 events
Processed 6,000,000 events
Processed 7,000,000 events
Processed 8,000,000 events
Processed 9,000,000 events
Processed 10,000,000 events
Processed 11,000,000 events
Processed 12,000,000 events
Processed 13,000,000 events
Processed 14,000,000 events
Processed 15,000,000 events
Processed 16,000,000 events
Processed 17,000,000 events
Processed 18,000,000 events
Processed 19,000,000 events
Processed 20,000,000 events
Processed 21,000,000 events
Processed 22,000,000 events
Processed 23,000,000 events
Processed 24,000,000 events
Processed 25,000,000 events

Total fields:     1249
Constant fields:  459
Remaining fields: 790

Constant fields:
type: 'wineventlog'
etl_host_agent_type: 'winlogbeat'
ClientMachine: 'DESKTOP-4PVPS6E'
@version: '1'
beat_name: 'DESKTOP-4PVPS6E'
etl_host_agent_uid: 'f99bee41-708a-4aa2-ad36-b5a565e36b68'
etl_version: '2020.04.19.01'
beat_version: '8.5.0'
Current Engine Version: '1.1.19800.4'
Previous Engine Version: '1.1.19800.4'
HostProcess: 'wmiprvse.exe'
DomainName: 'PHOENIX'
TransportFlags: '0x1'
HasFlowUrl: 'false'
AuthRequired: '0'
RequestStatus: '0'
HasEndAuthUrl: 'false'
HasAuthUrl: 'false'
bytesTransferredFromPeer: '0'
fileCount: '1'
TaskEngineName: 'S-1-5-18:NT AUTHORITY\\System:Service:'
Origin: '1'
SettingValueSize: '4'
bandwidthLimit: '18446744073709551615'
PeerContextInfo: '0'
ignoreBandwidthLimitsOnLan: 'false'
peerProtocolFlags: '0'
AdditionalInfoHr: '0'
NetName: '*'
ChangeType: '0'
NetNameLength: '1'
ClientAddressLength: '128'
ErrorRecordFormat: '10'
ShimSource: '0'
AppliedGuids: '{434abafd-08fa-4c3d-a88d-d09a88e2ab17}'
ShimCount: '1'
LKeyGenerationStatus: '1'
SealingStatus: '1'
UnsealingCachedCopyStatus: '1'
CachedCopyStatus: '0'
Type ID: '0'
Remediation User: 'NT AUTHORITY\\SYSTEM'
Scan Parameters Index: '1'
Scan Time Hours: '0'
Scan Type Index: '1'
FileName: 'c:\\windows\\prefetch\\readyboot\\readyboot.etl'
MaxFileSize: '20971520'
Active: '1'
LocalOnlyMapped: '0'
RemoteAddresses: '*'
RuleStatus: '65536'
LooseSourceMapped: '0'
LocalAddresses: '*'
isRoaming: '1'
ConnType: 'TCP'
AvcEnabled: '1'
ClientMode: '2'
NumberOfGPOsApplicable: '0'
NumberOfGPOsDownloaded: '0'
PolicyProcessingMode: '0'
IsPolicyConfigured: 'false'
DidWaitTimeout: 'true'
ProfileType: 'Regular'
listenerName: 'RDP-Tcp'
IdleSeconds2: '0'
IPVersion: '0'
API: 'Plugin initialize'
Result: '3221521586'
NumMonitors: '1'
DUID: '000100012AF5BEB6000C29969221'
NewDUIDLength: '14'
DUIDLength: '14'
HWLength: '6'
NewHWLength: '6'
EffectiveSid: 'S-1-5-21-1311114680-1922563338-3976463898-1001'
MonitorX: '0'
MonitorHeight: '768'
MonitorY: '0'
MonitorWidth: '1024'
SettingValueString: 'No'
cid: 'NULL'
MachineEnvironment: 'production'
RequestType: '2'
Last full scan source: '0'
Last quick scan source: '2'
Last full scan age: '4294967295'
Engine version: '1.1.19800.4'
LeapSecondCount: '0'
RuntimeStateAndSettingsConsistent: '1'
CurrentUtcOffset: '0'
Enabled: '1'
Settings: '0x80000000'
Exemption: '1'
Arguments: '-o '
Parameter8Name: 'Parameter4'
Parameter8Value: '0'
Parameter6Name: 'Parameter2'
Parameter5Name: 'Parameter1'
Parameter6Value: '30'
Parameter7Value: '0'
Parameter7Name: 'Parameter3'
Parameter5Value: '0'
WaitDuration_ms: '0'
QueueDepth: '0'
AddSenseQ: '0'
Threshold_ms: '30000'
SerialNumber: 'VMWare NVME_0000'
NewUnitCount: '1'
DeleteUnitCount: '0'
TotalDeviceFailureErrors: '0'
LastError_QueueDepth: '0'
LastError_AddSenseQ: '0'
TotalImpendingDeviceFailureErrors: '0'
LastError_WaitDuration_ms: '0'
MaxUnmapLatency_100ns: '0'
BucketIoFailed7: '0'
DeviceQueueIoWaitExceededTimeoutCount: '0'
BucketIoFailed2: '0'
BucketIoFailed5: '0'
MaxFlushLatency_100ns: '0'
BucketIoFailed4: '0'
BucketIoFailed1: '0'
FirmwareRevision: '1.0'
IoLatencyBuckets: '256us, 1ms, 4ms, 16ms, 64ms, 128ms, 256ms, 2000ms, 6000ms, 10000ms, 20000ms, 20000+ms'
AdapterSerialNumber: 'VMWare NVME_0000'
BucketIoFailed12: '0'
BucketIoFailed3: '0'
IoTimeout_s: '10'
DeviceQueueIoPausedCount: '0'
ContainsRawVolumes: 'false'
TotalDisks: '1'
FileSystem: 'NTFS'
DiskNumber: '0'
ProductRevision: '1.0'
PartitionStyle: '1'
VolumeCount: '3'
Size: '64424509440'
ParentId: 'PCI\\VEN_15AD&DEV_07F0&SUBSYS_07F015AD&REV_00\\4&23F707FC&0&00B8'
DiskIndex: '0'
DeviceClass: 'USBXHCI'
FlagSource: '1'
CallingProcessProtection: '0'
ChildImagePathNameLength: '32'
queryid: '0'
CONSUMER: 'NTEventLogEventConsumer="SCM Event Log Consumer"'
ESS: 'SCM Event Log Filter'
DeviceGuid: '{7b6f1752-bd95-6e22-e3a5-6ee8419ecad7}'
Stage1DurationMs: '0'
VendorIdLength: '0'
VolumeSizeChangeOperation: '1'
DeviceSerialNumberLength: '16'
ProductRevisionLength: '3'
DeviceSerialNumber: 'VMWare NVME_0000'
ToSize: '60599'
Stage2DurationMs: '0'
AdapterSerialNumberLength: '16'
ProductIdLength: '24'
FromSize: '61109'
Position: '1'
NvmeHealthLog: '00002F0164000000000000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000050000000000000000000000000000007017000000000000000000000000000088130000000000000000000000000000050000000000000000000000000000000A0000000000000000000000000000003C00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
CriticalWarning: '0'
VendorSpecificLogPageCode: '0'
NvmeHealthLogLength: '216'
VendorSpecificLogLength: '0'
VendorSpecificLogPageVersion: '0'
DataVersion: '14'
LogFileFullReasonBucket10: '0'
NtfsFillStatInfoFromMftRecordCalledCount: '0'
LogFileReads: '8'
VolumeTrimSkippedCount: '0'
LogFileFullReasonBucket3: '0'
Mft2WriteBytes: '0'
AvgFileLevelTrimSize: '0'
FileLevelTrimTime: '0'
NtfsFillStatInfoFromMftRecordBailedBecauseOfNonResReparsePointCount: '0'
FileLevelTrimCount: '0'
LogFileFullReasonBucket13: '0'
LogFileFullReasonBucket9: '0'
RootIndexReads: '0'
LogFileReadBytes: '32768'
FileLevelTrimSize: '0'
LogFileFullReasonBucket11: '0'
LogFileFullReasonBucket12: '0'
Mft2Writes: '0'
VolumeTrimSkippedSize: '0'
RootIndexWriteBytes: '0'
LogFileFullReasonBucket15: '0'
LogFileFullReasonBucket5: '0'
DiskResourceFailure: '0'
LogFileFullReasonBucket7: '0'
LogFileFullReasonBucket1: '0'
RootIndexReadBytes: '0'
LogFileFullReasonBucket8: '0'
NtfsFillStatInfoFromMftRecordBailedBecauseOfAttributeListCount: '0'
AvgFileLevelTrimTime: '0'
LogFileFullReasonBucket6: '0'
RootIndexWrites: '0'
LogFileFullReasonBucket14: '0'
AvgVolumeTrimTime: '0'
TimeProviders: 'NtpClient (Local)\nDllName: C:\\WINDOWS\\system32\\w32time.dll (Local)\nEnabled: 1 (Local)\nInputProvider: 1 (Local)\nCrossSiteSyncFlags: 2 (Local)\nAllowNonstandardModeCombinations: 1 (Local)\nResolvePeerBackoffMinutes: 15 (Local)\nResolvePeerBackoffMaxTimes: 7 (Local)\nCompatibilityFlags: 2147483648 (Local)\nEventLogFlags: 1 (Local)\nLargeSampleSkew: 3 (Local)\nSpecialPollInterval: 3600 (Local)\nType: NT5DS (Local)\nNtpServer:  (Undefined or not used)\n\nVMICTimeProvider (Local)\nDllName: C:\\WINDOWS\\System32\\vmictimeprovider.dll (Local)\nEnabled: 1 (Local)\nInputProvider: 1 (Local)\n\nNtpServer (Local)\nDllName: C:\\WINDOWS\\system32\\w32time.dll (Local)\nEnabled: 0 (Local)\nInputProvider: 0 (Local)'
TimeSourceFlags: '0'
Stratum: '0'
StateMachine: '0'
ReferenceId: '0x00000000'
PhaseOffset: '0.0000000s'
PollInterval: '10'
LastSuccessfulSyncTime: '1601-01-01T00:00:00.0Z'
Precision: '-23'
RootDelay: '0.0000000s'
ServerRole: '0'
RootDispersion: '0.0000000s'
LeapIndicator: '3'
ClockRate: '156250'
LastSyncError: '1'
LocalizedText: '\nISA Bridge:\n\tPCI\\VEN_8086&DEV_7110 (PCI to ISA Bridge)\n\nPCI-to-PCI Bridge:\n\tPCI\\VEN_15AD&DEV_0790 (PCI-to-PCI Bridge)\n\tPCI\\VEN_8086&DEV_7191 (PCI-to-PCI Bridge)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)\n\tPCI\\VEN_15AD&DEV_07A0 (PCI Express Root Port)'
SchemaType: '2'
Failure reason: 'NULL'
NgcPostLogonProvisioningEnabled: 'Not Tested'
LogonCertRequired: 'Not Tested'
DeviceIsJoined: 'Not Tested'
MachinePolicySource: 'none'
NgcHardwarePolicyMet: 'Not Tested'
NgcPolicyEnabled: 'Not Tested'
ListenerName: 'RDP-Tcp'
IFTSTMP: '1'
AllNtpServers: ';'
Format: 'NameFullyQualifiedDN'
JoinType: 'undefined'
TenantType: 'undefined'
DriveId: '{7b6f1752-bd95-6e22-e3a5-6ee8419ecad7}'
DeviceNumber: '0'
DriveManufacturer: 'NULL'
DriveModel: 'VMware Virtual NVMe Disk'
PoolId: '{00000000-0000-0000-0000-000000000000}'
DriveSerial: 'VMWare NVME_0000'
InitState: '1'
IntendedPackageStateTextized: 'Installed'
number: '101.61'
Stage: 'Complete'
Kind: '0'
SrbFunction: '0'
SrbTimeout: '10'
CdbLength: '10'
AbortSupported: 'false'
InstanceNameLength: '24'
InstanceName: '\\Device\\LanmanRedirector'
ValidatedPolicy: '1'
ProcessNameLength: '71'
RequestedPolicy: '8'
ProcessNameBuffer: '\\Device\\HarddiskVolume3\\Program Files (x86)\\Mozilla Firefox\\firefox.exe'
IssuerName: 'DigiCert SHA2 Assured ID Code Signing CA'
CacheState: '3'
IssuerTBSHashSize: '32'
PublisherNameLength: '19'
PublisherTBSHashSize: '32'
ValidatedSigningLevel: '1'
IssuerTBSHash: 'E767799478F64A34B3F53FF3BB9057FE1768F4AB178041B0DCC0FF1E210CBA65'
NotValidAfter: '2024-06-19T23:59:59.0000000Z'
VerificationError: '7'
SignatureType: '1'
PageHash: 'false'
Hash Size: '32'
NotValidBefore: '2021-04-09T00:00:00.0000000Z'
PolicyBits: '1'
TotalSignatureCount: '1'
PublisherTBSHash: '60A465234130E42D01E1285D314256DD7FD709C4127EB9AE7CE3387DA1D4CD0A'
PublisherName: 'Mozilla Corporation'
IssuerNameLength: '40'
TargetThreadId: '7336'
SignatureLevel: '0'
ProcessSectionSignatureLevel: '8'
ImageName: '\\program files (x86)\\mozilla firefox\\mozavcodec.dll'
ProcessCreateTime: '2022-11-17T17:21:10.2732801Z'
ProcessProtection: '0'
TargetThreadCreateTime: '2022-11-17T17:21:10.2732854Z'
ImageNameLength: '51'
RequiredSignatureLevel: '8'
ProcessStartKey: '1688849860264565'
ProcessSignatureLevel: '8'
FailedIoCount: '0'
ResetType: '3'
ResetStatus: '0x0'
Feature Name: '%%886'
Feature ID: '9'
Engine up-to-date: '0'
Latest platform version: '4.18.2210.6'
Platform up-to-date: '1'
Latest engine version: '1.1.19800.4'
Folder: '\\Microsoft\\Windows\\Workplace Join'
Store Type: '12'
UseCloudTrust: 'Not Tested'
CloudTgt: 'Not Tested'
connection: 'WIN-GP7PPFBR2N1/wsman?PSVersion=5.0.10240.17146'
ShareName: '\\10.10.117.129\\c$'
ShareNameLength: '17'
ObjectNameLength: '0'
PolicyChange: '0'
shellId: '538F0F14-559B-4118-A7BA-2A4AF18ED5B8'
Update State: '%%852'
Update State Index: '1'
Address2: '0'
DetectionOnly: '0'
AutoTriggered: '1'
CallerId: '1'
param19: '0'
URL: 'winrt://{S-1-5-21-1311114680-1922563338-3976463898-1001}/'
EventProvider: 'wsp_sr'
param23: '0'
FilterHostProcessID: '6032'
ProtocolHostProcessID: '5900'
ProfsvcPID: '364'
InterferingPID: '4596'
InterferingImageName: 'C:\\Windows\\System32\\svchost.exe'
Library: 'C:\\WINDOWS\\system32\\msdtcuiu.DLL'
Win32Error: '2147944538'
PsmKey: 'Microsoft.Windows.ShellExperienceHost_10.0.10240.16384_neutral_neutral_cw5n1h2txyewy+App'
CorruptionId: '4810 - base\\appmodel\\search\\search\\ytrip\\tripoli\\inverted\\jetstoragelayer.cpp (647)'
z_logstash_pipeline: ['copy-8802-001', 'copy-8802-002']
PipelineId: '00000000-0000-0000-0000-000000000000'
MinRunspaces: '1'
MaxRunspaces: '1'
key_provider_name: 'Microsoft Software Key Storage Provider'
TokenElevationType: '%%1936'
MandatoryLabel: 'S-1-16-16384'
LmPackageName: 'NTLM V1'
KernelDebug: '%%1843'
ConfigAccessPolicy: '%%1846'
DisableIntegrityChecks: '%%1843'
AdvancedOptions: '%%1843'
HypervisorLoadOptions: '-'
HypervisorDebug: '%%1843'
FlightSigning: '%%1843'
VsmLaunchType: '%%1848'
TestSigning: '%%1843'
RemoteEventLogging: '%%1843'
HypervisorLaunchType: '%%1848'
PuaCount: '0'
Workstation: 'desktop-4pvps6e'
RestrictedAdminMode: '%%1843'
target_process_id_orig: '0x5c'
SamAccountName: 'wdagutilityaccount'
UserWorkstations: '%%1793'
ScriptPath: '%%1793'
ProfilePath: '%%1793'
HomeDirectory: '%%1793'
AccountExpires: '%%1794'
LogonHours: '%%1797'
PrimaryGroupId: '513'
UserParameters: '%%1793'
HomePath: '%%1793'
PasswordLastSet: '%%1794'
object_type: 'File'
Schema: '{1d4350a3-330d-4af9-b3ff-a927a45998ac}'
Resource: 'NGC Local Accoount Logon Vault Resource'
SchemaFriendlyName: 'NGC Local Accoount Logon Vault Resource Schema'
group_name: 'none'
meta_target_user_name_is_machine: 'false'
target_user_name: '-'
group_sid: 'S-1-5-21-1311114680-1922563338-3976463898-513'
group_domain: 'desktop-4pvps6e'
target_user_sid: 'S-1-5-21-1311114680-1922563338-3976463898-504'
PublisherID: 'Microsoft-Windows-Security-Auditing'
EventID: '0'
event_timezone: 'UTC'
rule_technique: 'T1053'
meta_src_ip_geo: {}
DomainPeer: 'phoenix.local'
SupportInfo1: '1'
HostName: 'desktop-4pvps6e'
AdapterSuffixName: 'phoenix.local'
AddServiceStatus: '0'
IsDriverOEM: 'false'
InstallStatus: '0x0'
RebootOption: 'false'
UpgradeDevice: 'false'
FinalStatus: '0x0'
DeviceVersionMinor: '0'
Group: '0'
MaximumPerformancePercent: '100'
MinimumThrottlePercent: '100'
PerformanceImplementation: '0'
MinimumPerformancePercent: '100'
IdleStateCount: '1'
IdleImplementation: '1'
Config: '0'
IsTestConfig: '0'
BootType: '0'
DwordVal: '1'
MinorVersion: '0'
MajorVersion: '10'
ServiceVersion: '0'
BootMode: '0'
UnsynchronizedTimeSeconds: '86400'
EntryCount: '1'
CorruptionActionState: '0'
BitlockerUserInputTime: '0'
SleepInProgress: '0'
PowerButtonTimestamp: '0'
BugcheckParameter4: '0x0'
BootAppStatus: '0'
BugcheckParameter3: '0x0'
BootMenuPolicy: '1'
ShutdownEventCode: '0'
ShutdownReason: '5'
EfiTimeZoneBias: '2047'
EfiDaylightFlags: '0'
Default SD String:: 'O:SYG:SYD:(A;;RC;;;BA)'
Host OS Build number: '10240'
Host OS Major version: '10'
Host OS Service pack minor number: '0'
Host OS Service pack major number: '0'
Host OS Minor version: '0'
Installation choice: '4'
OSservicepackminorversion: '0'
OSbuildversion: '19042'
OSEditionID: 'Enterprise'
OSservicepackmajorversion: '0'
OSmajorversion: '10'
OSminorversion: '0'
EnableDisableReason: '0'
VsmPolicy: '0'
CountNew: '0'
UpdateReason: '0'
CountOld: '0'
EnabledNew: 'true'
Title: 'PreSignInSettingsConfigJSON'
FileList: '    C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\BITB159.tmp'
FirstRefresh: '0'
TimeZoneInfoCacheUpdated: '0'
CurrentTimeZoneID: '1'
CurrentBias: '-60'
ExitReason: '0'
MinimumPasswordLengthAudit: '-1'
MinimumPasswordLength: '7'
RelaxMinimumPasswordLengthLimits: '0'
FriendlyName: 'Microsoft Remote Display Adapter'
RestartCount: '5'
Failure Reason: 'Invalid registry keys'
PublisherGuid: '{a70ff94f-570b-4979-ba5c-e59c9feab61b}'
AlertDesc: '40'
DetectedBy: '2'
ActiveOperation: '0'
IfLuid: '1689399632855040'
IfGuid: '{004B0C9B-A704-4F3A-835F-6CF30508816E}'
ResetReason: '1'
ResetCount: '1'
ErrorState: '1205'
NumAttempts: '1'
NumRootCauses: '0'
EndTime: '2022-11-22T19:33:45.8955779Z'
LaunchType: 'AutoFailover'
CsEntryScenarioInstanceId: '0'
CheckpointStatus: '0'
Checkpoint: '0'
LongPowerButtonPressDetected: 'false'
SystemSleepTransitionsToOn: '0'
BugcheckInfoFromEFI: 'false'
CsEntryScenarioInstanceIdV2: '0'
ConnectedStandbyInProgress: 'false'

In [ ]:
import json
from collections import defaultdict

PATH = "/content/dataset/comiset_lab_subset.jsonl"
N = 2_000_000

# Track values for non-constant fields
values = defaultdict(set)
counts = defaultdict(int)

with open(PATH, "r", encoding="utf-8") as f:
    for i, line in enumerate(f):
        if i >= N:
            break

        source = json.loads(line)["_source"]

        for key, value in source.items():
            if key in constant_cols:
                continue

            counts[key] += 1

            # Don't let pathological fields consume unlimited RAM
            if len(values[key]) <= 100_000:
                values[key].add(str(value))

        if (i + 1) % 100_000 == 0:
            print(f"Processed {i + 1:,}")

# Find extremely high-cardinality fields
candidates = []

for key in counts:
    unique = len(values[key])
    total = counts[key]

    # Only meaningful if we didn't hit the safety cap
    if unique <= 100_000:
        ratio = unique / total

        if ratio >= 0.99:
            candidates.append((key, total, unique, ratio))

candidates.sort(key=lambda x: x[3], reverse=True)

print("\nPotential pure-ID fields:")
print(f"{'Field':45} {'Count':>10} {'Unique':>10} {'Unique %':>10}")
print("-" * 80)

for key, total, unique, ratio in candidates:
    print(f"{key[:45]:45} {total:10,} {unique:10,} {ratio*100:9.2f}%")

Processed 100,000
Processed 200,000
Processed 300,000
Processed 400,000
Processed 500,000
Processed 600,000
Processed 700,000
Processed 800,000
Processed 900,000
Processed 1,000,000
Processed 1,100,000
Processed 1,200,000
Processed 1,300,000
Processed 1,400,000
Processed 1,500,000
Processed 1,600,000
Processed 1,700,000
Processed 1,800,000
Processed 1,900,000
Processed 2,000,000

Potential pure-ID fields:
Field                                              Count     Unique   Unique %
--------------------------------------------------------------------------------
PolicyActivityId                                     240        240    100.00%
ErrorSourceTable                                      70         70    100.00%
OperationParameter1                                  279        279    100.00%
GpsvcTimeElapsedInMilliseconds                        22         22    100.00%
PolicyDownloadTimeElapsedInMilliseconds               60         60    100.00%
NewDUID                                               16         16    100.00%
Srb                                                   53         53    100.00%
BucketIoSuccess2                                      94         94    100.00%
TotalIoCount                                          94         94    100.00%
BucketIoLatency3_100ns                                94         94    100.00%
MaxReadWriteLatency_100ns                             94         94    100.00%
BucketIoLatency1_100ns                                94         94    100.00%
BucketIoLatency2_100ns                                94         94    100.00%
BucketIoLatency4_100ns                                94         94    100.00%
TotalWriteBytes                                       94         94    100.00%
BucketIoSuccess4                                      94         94    100.00%
TotalReadBytes                                        94         94    100.00%
BucketIoSuccess1                                      94         94    100.00%
MetaDataDiskReads                                      2          2    100.00%
UserIndexWrites                                        2          2    100.00%
UserDiskWrites                                         2          2    100.00%
MftWrites                                              2          2    100.00%
MftReadBytes                                           2          2    100.00%
MftBitmapReadBytes                                     2          2    100.00%
LogFileFullReasonBucket2                               2          2    100.00%
LogFileWrites                                          2          2    100.00%
UserFileWrites                                         2          2    100.00%
BitmapWriteBytes                                       2          2    100.00%
LogFileFull                                            2          2    100.00%
UserDiskReads                                          2          2    100.00%
UserFileWriteBytes                                     2          2    100.00%
UserIndexReads                                         2          2    100.00%
UserIndexWriteBytes                                    2          2    100.00%
BitmapReadBytes                                        2          2    100.00%
VolumeTrimCount                                        2          2    100.00%
MftWriteBytes                                          2          2    100.00%
MetaDataWriteBytes                                     2          2    100.00%
MetaDataDiskWrites                                     2          2    100.00%
MetaDataReads                                          2          2    100.00%
BitmapReads                                            2          2    100.00%
MetaDataReadBytes                                      2          2    100.00%
MftReads                                               2          2    100.00%
LogFileFullReasonBucket4                               2          2    100.00%
UserFileReadBytes                                      2          2    100.00%
LogFileWriteBytes                                      2          2    100.00%
VolumeTrimSize                                         2          2    100.00%
UserFileReads                                          2          2    100.00%
MetaDataWrites                                         2          2    100.00%
MftBitmapWrites                                        2          2    100.00%
AvgVolumeTrimSize                                      2          2    100.00%
MftBitmapWriteBytes                                    2          2    100.00%
UserIndexReadBytes                                     2          2    100.00%
VolumeTrimTime                                         2          2    100.00%
MftBitmapReads                                         2          2    100.00%
BitmapWrites                                           2          2    100.00%
TimeSinceLastGoodSync                                 26         26    100.00%
ElapsedTimeMs                                          7          7    100.00%
CurrentTime(UTC)                                      26         26    100.00%
SystemTime                                             2          2    100.00%
Cdb                                                    2          2    100.00%
SuccessIoCount                                         2          2    100.00%
Timestamp                                             18         18    100.00%
SessionGUID                                            9          9    100.00%
ConnectionGUID                                         9          9    100.00%
Update Source                                          2          2    100.00%
Update Source Index                                    2          2    100.00%
Source Path                                            2          2    100.00%
Address1                                               2          2    100.00%
Detail                                                28         28    100.00%
Payload                                                4          4    100.00%
ContextInfo                                            4          4    100.00%
xml                                                   27         27    100.00%
PreviousTime                                          95         95    100.00%
NewTime                                               95         95    100.00%

In [ ]:
candidates = [
    x for x in candidates
    if x[1] >= 20
]

In [ ]:
print(f"{'Field':45} {'Count':>10} {'Unique':>10} {'Unique %':>10}")
print("-" * 80)

for key, total, unique, ratio in candidates:
    print(f"{key[:45]:45} {total:10,} {unique:10,} {ratio*100:9.2f}%")

Field                                              Count     Unique   Unique %
--------------------------------------------------------------------------------
PolicyActivityId                                     240        240    100.00%
ErrorSourceTable                                      70         70    100.00%
OperationParameter1                                  279        279    100.00%
GpsvcTimeElapsedInMilliseconds                        22         22    100.00%
PolicyDownloadTimeElapsedInMilliseconds               60         60    100.00%
Srb                                                   53         53    100.00%
BucketIoSuccess2                                      94         94    100.00%
TotalIoCount                                          94         94    100.00%
BucketIoLatency3_100ns                                94         94    100.00%
MaxReadWriteLatency_100ns                             94         94    100.00%
BucketIoLatency1_100ns                                94         94    100.00%
BucketIoLatency2_100ns                                94         94    100.00%
BucketIoLatency4_100ns                                94         94    100.00%
TotalWriteBytes                                       94         94    100.00%
BucketIoSuccess4                                      94         94    100.00%
TotalReadBytes                                        94         94    100.00%
BucketIoSuccess1                                      94         94    100.00%
TimeSinceLastGoodSync                                 26         26    100.00%
CurrentTime(UTC)                                      26         26    100.00%
Detail                                                28         28    100.00%
xml                                                   27         27    100.00%
PreviousTime                                          95         95    100.00%
NewTime                                               95         95    100.00%

In [ ]:
import gzip
import json
import os

INPUT = "/content/dataset/comiset_lab_subset.jsonl"
OUTPUT = "/content/dataset/comiset_lab_cleaned.jsonl.gz"

remove_cols = set(constant_cols)
remove_cols.update([
    "record_number",
    # add confirmed useless IDs here
])

with open(INPUT, "r", encoding="utf-8") as fin, \
     gzip.open(OUTPUT, "wt", encoding="utf-8") as fout:

    for i, line in enumerate(fin):
        event = json.loads(line)

        for col in remove_cols:
            event["_source"].pop(col, None)

        fout.write(json.dumps(event, separators=(",", ":")) + "\n")

        if (i + 1) % 1_000_000 == 0:
            print(f"Processed {i + 1:,}")

print("Finished.")
print(f"Output size: {os.path.getsize(OUTPUT) / 1024**3:.2f} GB")

Processed 1,000,000
Processed 2,000,000
Processed 3,000,000
Processed 4,000,000
Processed 5,000,000
Processed 6,000,000
Processed 7,000,000
Processed 8,000,000
Processed 9,000,000
Processed 10,000,000
Processed 11,000,000
Processed 12,000,000
Processed 13,000,000
Processed 14,000,000
Processed 15,000,000
Processed 16,000,000
Processed 17,000,000
Processed 18,000,000
Processed 19,000,000
Processed 20,000,000
Processed 21,000,000
Processed 22,000,000
Processed 23,000,000
Processed 24,000,000
Processed 25,000,000
Finished.
Output size: 2.41 GB

preprocessing continued

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!find /content/drive/MyDrive -iname "comiset_parquet_v11.zip" 2>/dev/null

/content/drive/MyDrive/comiset_parquet_v11.zip

In [ ]:
import zipfile

ZIP_PATH = "/content/drive/MyDrive/comiset_parquet_v11.zip"
OUTPUT_DIR = "/content/comiset_parquet_v11"

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    z.extractall(OUTPUT_DIR)

print("Extracted to:", OUTPUT_DIR)

Extracted to: /content/comiset_parquet_v11

In [ ]:
import glob
import polars as pl

FILES = glob.glob("/content/comiset_parquet/*.parquet")

# Read a small sample from every ~50th shard
sample_files = FILES[::max(1, len(FILES) // 20)]

df = pl.concat([
    pl.read_parquet(f).head(5000)
    for f in sample_files
], how="diagonal")

print("Sample shape:", df.shape)
print("Number of columns:", len(df.columns))

for col in df.columns:
    s = df[col]

    print(f"\n{'='*80}")
    print(f"FIELD: {col}")
    print(f"Non-null: {s.len() - s.null_count():,}")
    print("Examples:")

    for value in s.drop_nulls().unique().head(5).to_list():
        print(f"  {repr(value)}")

Sample shape: (105000, 42)
Number of columns: 42

================================================================================
FIELD: user_domain
Non-null: 75,112
Examples:
  'nt authority'
  'desktop-4pvps6e'

================================================================================
FIELD: event_id
Non-null: 105,000
Examples:
  '6'
  '12'
  '3'
  '26'
  '1'

================================================================================
FIELD: version
Non-null: 105,000
Examples:
  '1'
  '3'
  '2'
  '5'
  '4'

================================================================================
FIELD: opcode
Non-null: 105,000
Examples:
  'Info'

================================================================================
FIELD: level
Non-null: 105,000
Examples:
  'information'

================================================================================
FIELD: process_id
Non-null: 105,000
Examples:
  '4540'
  '2616'
  '504'
  '4872'
  '3868'

================================================================================
FIELD: EventType
Non-null: 69,548
Examples:
  'CreatePipe'
  'SetValue'
  'DeleteKey'
  'CreateKey'
  'DeleteValue'

================================================================================
FIELD: @timestamp
Non-null: 105,000
Examples:
  '2022-11-20T12:48:27.337Z'
  '2022-11-22T20:59:10.880Z'
  '2022-11-18T16:46:05.866Z'
  '2022-11-22T17:39:49.957Z'
  '2022-11-19T17:40:51.384Z'

================================================================================
FIELD: z_elastic_ecs
Non-null: 105,000
Examples:
  '{"agent":{},"event":{"created":"2022-11-18T16:57:00.690Z","code":"10","action":"Process accessed (rule: ProcessAccess)","kind":"event","provider":"Microsoft-Windows-Sysmon"},"host":{},"ecs":{"version":"8.0.0"},"log":{},"winlog":{"process":{"thread":{}}},"user":{"type":"User","domain":"NT AUTHORITY","name":"SYSTEM","identifier":"S-1-5-18"}}'
  '{"agent":{},"event":{"code":"11","created":"2022-11-17T12:49:11.560Z","provider":"Microsoft-Windows-Sysmon","kind":"event","action":"File created (rule: FileCreate)"},"host":{},"ecs":{"version":"8.0.0"},"log":{},"winlog":{"process":{"thread":{}}},"user":{"type":"User","domain":"NT AUTHORITY","name":"SYSTEM","identifier":"S-1-5-18"}}'
  '{"agent":{},"event":{"created":"2022-11-17T17:13:51.740Z","code":"12","provider":"Microsoft-Windows-Sysmon","action":"Registry object added or deleted (rule: RegistryEvent)","kind":"event"},"host":{},"ecs":{"version":"8.0.0"},"log":{},"winlog":{"process":{"thread":{}}},"user":{"type":"User","domain":"NT AUTHORITY","identifier":"S-1-5-18","name":"SYSTEM"}}'
  '{"agent":{},"event":{"created":"2022-11-17T12:48:23.549Z","code":"18","action":"Pipe Connected (rule: PipeEvent)","kind":"event","provider":"Microsoft-Windows-Sysmon"},"host":{},"ecs":{"version":"8.0.0"},"log":{},"winlog":{"process":{"thread":{}}},"user":{"type":"User","domain":"NT AUTHORITY","identifier":"S-1-5-18","name":"SYSTEM"}}'
  '{"agent":{},"event":{"code":"10","created":"2022-11-16T14:12:22.829Z","provider":"Microsoft-Windows-Sysmon","kind":"event","action":"Process accessed (rule: ProcessAccess)"},"host":{},"ecs":{"version":"8.0.0"},"log":{},"winlog":{"process":{"thread":{}}},"user":{"type":"User","domain":"NT AUTHORITY","identifier":"S-1-5-18","name":"SYSTEM"}}'

================================================================================
FIELD: event_original_message
Non-null: 105,000
Examples:
  'Process accessed:\nRuleName: -\nUtcTime: 2022-11-16 13:50:08.225\nSourceProcessGUID: {4FD6B357-E6CB-6374-2300-000000003100}\nSourceProcessId: 1980\nSourceThreadId: 3644\nSourceImage: C:\\Program Files\\Windows Defender\\MsMpEng.exe\nTargetProcessGUID: {4FD6B357-E6D0-6374-2800-000000003100}\nTargetProcessId: 2712\nTargetImage: C:\\Program Files (x86)\\Remote Mouse\\RemoteMouse.exe\nGrantedAccess: 0x1000\nCallTrace: C:\\Windows\\SYSTEM32\\ntdll.dll+93a8a|C:\\Windows\\system32\\KERNELBASE.dll+1f6fd|C:\\Program Files\\Windows Defender\\mprtp.dll+38f0|C:\\Program Files\\Windows Defender\\mprtp.dll+3a62|C:\\Program Files\\Windows Defender\\NisIpsPlugin.dll+72da|C:\\Program Files\\Windows Defender\\NisIpsPlugin.dll+524d|C:\\Program Files\\Windows Defender\\NisIpsPlugin.dll+3ba4|C:\\Program Files\\Windows Defender\\mpsvc.dll+1644f|C:\\Program Files\\Windows Defender\\mpsvc.dll+150bd|C:\\Windows\\system32\\RPCRT4.dll+7b0b3|C:\\Windows\\system32\\RPCRT4.dll+dd903|C:\\Windows\\system32\\RPCRT4.dll+1702c|C:\\Windows\\system32\\RPCRT4.dll+14e93|C:\\Windows\\system32\\RPCRT4.dll+13b1a|C:\\Windows\\system32\\RPCRT4.dll+1464f|C:\\Windows\\system32\\RPCRT4.dll+29cff|C:\\Windows\\system32\\RPCRT4.dll+2a91f|C:\\Windows\\system32\\RPCRT4.dll+58063|C:\\Windows\\system32\\RPCRT4.dll+568d9|C:\\Windows\\system32\\RPCRT4.dll+66ca2|C:\\Windows\\SYSTEM32\\ntdll.dll+3b9a9|C:\\Windows\\SYSTEM32\\ntdll.dll+399fe|C:\\Windows\\system32\\KERNEL32.DLL+12d92|C:\\Windows\\SYSTEM32\\ntdll.dll+9f64\nSourceUser: NT AUTHORITY\\SYSTEM\nTargetUser: NT AUTHORITY\\SYSTEM'
  'Registry object added or deleted:\nRuleName: -\nEventType: CreateKey\nUtcTime: 2022-11-22 20:54:53.944\nProcessGuid: {4FD6B357-E399-6378-2700-000000002900}\nProcessId: 2564\nImage: C:\\Program Files (x86)\\Remote Mouse\\RemoteMouse.exe\nTargetObject: HKLM\\System\\CurrentControlSet\\Services\\Tcpip\\Parameters\nUser: NT AUTHORITY\\SYSTEM'
  'Registry object added or deleted:\nRuleName: -\nEventType: CreateKey\nUtcTime: 2022-11-25 09:19:24.642\nProcessGuid: {4fd6b357-87d3-6380-2e00-000000000900}\nProcessId: 2532\nImage: C:\\Windows\\Sysmon64.exe\nTargetObject: HKU\\.DEFAULT\\Software\\Policies\\Microsoft\\SystemCertificates\\Disallowed\nUser: NT AUTHORITY\\SYSTEM'
  'Registry object added or deleted:\nRuleName: -\nEventType: CreateKey\nUtcTime: 2022-11-17 23:01:38.047\nProcessGuid: {4fd6b357-bbcf-6376-3700-000000000500}\nProcessId: 2224\nImage: C:\\Program Files (x86)\\Remote Mouse\\RemoteMouse.exe\nTargetObject: HKLM\\System\\CurrentControlSet\\Services\\Tcpip\\Parameters\nUser: NT AUTHORITY\\SYSTEM'
  'Registry object added or deleted:\nRuleName: -\nEventType: CreateKey\nUtcTime: 2022-11-16 13:52:36.886\nProcessGuid: {4FD6B357-E6D0-6374-2800-000000003100}\nProcessId: 2712\nImage: C:\\Program Files (x86)\\Remote Mouse\\RemoteMouse.exe\nTargetObject: HKLM\\System\\CurrentControlSet\\Services\\Tcpip\\Parameters\nUser: NT AUTHORITY\\SYSTEM'

================================================================================
FIELD: host_name
Non-null: 105,000
Examples:
  'desktop-4pvps6e.phoenix.local'

================================================================================
FIELD: event_recorded_time
Non-null: 105,000
Examples:
  '2022-11-23T13:31:36.455Z'
  '2022-11-25T02:46:08.407Z'
  '2022-11-19T17:43:19.245Z'
  '2022-11-24T12:50:58.453Z'
  '2022-11-25T12:43:46.463Z'

================================================================================
FIELD: process_path
Non-null: 104,996
Examples:
  'c:\\program files (x86)\\mozilla firefox\\firefox.exe'
  'c:\\programdata\\microsoft\\windows defender\\platform\\4.18.2210.6-0\\msmpeng.exe'
  'c:\\windows\\system32\\consent.exe'
  'c:\\windows\\system32\\spoolsv.exe'
  'c:\\users\\louis\\downloads\\beacon2.exe'

================================================================================
FIELD: event_original_time
Non-null: 105,000
Examples:
  '2022-11-25T12:42:26.747Z'
  '2022-11-17T12:49:11.922Z'
  '2022-11-18T10:02:18.268Z'
  '2022-11-22T21:00:09.597Z'
  '2022-11-17T16:37:41.017Z'

================================================================================
FIELD: provider_guid
Non-null: 105,000
Examples:
  '5770385F-C22A-43E0-BF4C-06F5698FFBD9'
  '5770385f-c22a-43e0-bf4c-06f5698ffbd9'

================================================================================
FIELD: TargetObject
Non-null: 64,561
Examples:
  'HKU\\S-1-5-21-1311114680-1922563338-3976463898-1001_Classes\\.bay\\OpenWithProgids'
  'HKU\\S-1-5-21-1311114680-1922563338-3976463898-1001_Classes\\AppXgtz62cfp9761w8h33sbaykyt1vkbm4vj\\Application\\AppUserModelID'
  '\\REGISTRY\\A\\{15FEE0AC-1644-C828-01BD-A3C01EC4CEE8}\\HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech_OneCore\\SpeechUXPlugins\\Tokens\\DebugPlugin'
  '\\REGISTRY\\A\\{25f9af19-e986-091b-50c8-d51d3d3a812c}\\LocalState\\ScheduledWorkItems\\ContentDeliveryManager.Background.RefreshCacheTask\\SubscribedContent-314559'
  '\\REGISTRY\\A\\{15FEE0AC-1644-C828-01BD-A3C01EC4CEE8}\\HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech_OneCore\\Voices\\Tokens\\MSTTS_V110_frFR_NathalieM'

================================================================================
FIELD: thread_id
Non-null: 105,000
Examples:
  '3280'
  '3312'
  '3856'
  '968'
  '2572'

================================================================================
FIELD: process_name
Non-null: 104,996
Examples:
  'vssvc.exe'
  'cmd.exe'
  'wsapphelper.exe'
  'services.exe'
  'microsoftedgeupdate.exe'

================================================================================
FIELD: user_name
Non-null: 75,112
Examples:
  'system'
  'louis'
  'network service'
  'local service'

================================================================================
FIELD: process_guid
Non-null: 104,996
Examples:
  '4fd6b357-2c4f-6380-1602-000000000400'
  '4fd6b357-0ad6-6378-3b00-000000000600'
  '4FD6B357-1D2B-637A-1100-000000002A00'
  '4fd6b357-d9d9-6380-0f00-000000000600'
  '4fd6b357-2d82-6376-da00-000000000500'

================================================================================
FIELD: RuleName
Non-null: 105,000
Examples:
  'technique_id=T1218.002,technique_name=rundll32.exe'
  'technique_id=T1021,technique_name=Remote Services'
  'other interesting files'
  'technique_id=T1027,technique_name=Obfuscated Files or Information'
  'technique_id=T1547.001,technique_name=Registry Run Keys / Start Folder'

================================================================================
FIELD: source_name
Non-null: 105,000
Examples:
  'Microsoft-Windows-Sysmon'

================================================================================
FIELD: meta_user_name_is_machine
Non-null: 75,112
Examples:
  'false'

================================================================================
FIELD: log_name
Non-null: 105,000
Examples:
  'Microsoft-Windows-Sysmon/Operational'

================================================================================
FIELD: etl_processed_time
Non-null: 105,000
Examples:
  '2022-11-25T09:19:41.319Z'
  '2022-11-25T02:45:47.083Z'
  '2022-11-18T10:02:21.997Z'
  '2022-11-16T14:01:51.922Z'
  '2022-11-17T22:47:13.324Z'

================================================================================
FIELD: etl_pipeline
Non-null: 105,000
Examples:
  '["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","winevent-sysmon-all-1531","general_rename-various_global_options","provider_guid-cleanup","winevent-hostname-cleanup","final-cleanup-message_field"]'
  '["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","winevent-sysmon-all-1531","general_rename-various_global_options","general_rename-SourceProcessGuid","general_rename-TargetProcessGuid","general_rename-SourceProcessId","general_rename-TargetProcessId","general_rename-SourceImage","general_rename-TargetImage","split-process_path-grok-process_name","split-target_process_path-grok-target_process_name","provider_guid-cleanup","process_guid-cleanup","target_process_guid-cleanup","winevent-hostname-cleanup","final-cleanup-message_field"]'
  '["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","winevent-ip_conversion-SourceIp_and_DestinationIp","1522","winevent-sysmon-all-1531","sysmon-all-extract_domain_and_user_name","general_rename-various_global_options","general_rename-ProcessGuid","general_rename-ProcessId","general_rename-Image","split-process_path-grok-process_name","provider_guid-cleanup","process_guid-cleanup","dst_ip_addr_clean_and_public","dst_ip_addr_geo_city","src_ip_addr_clean_and_public","winevent-hostname-cleanup","winevent-user_name-is-machine-account","final-cleanup-message_field"]'
  '["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","1522","winevent-sysmon-all-1531","general_rename-various_global_options","general_rename-SourceProcessGUID","general_rename-TargetProcessGUID","general_rename-SourceProcessId","general_rename-TargetProcessId","general_rename-SourceImage","general_rename-TargetImage","split-process_path-grok-process_name","split-target_process_path-grok-target_process_name","provider_guid-cleanup","process_guid-cleanup","target_process_guid-cleanup","winevent-hostname-cleanup","final-cleanup-message_field"]'
  '["all-filter-0098","all-add_processed_timestamp","fingerprint-winlogbeats7","winlogbeat_7_and_above-field_nest_cleanup","winlogbeat_7_and_above-field_cleanups","1500","winevent-ip_conversion-SourceIp_and_DestinationIp","1522","winevent-sysmon-all-1531","sysmon-all-extract_domain_and_user_name","general_rename-various_global_options","general_rename-ProcessGuid","general_rename-ProcessId","general_rename-Image","split-process_path-grok-process_name","provider_guid-cleanup","process_guid-cleanup","dst_ip_addr_clean_and_public","src_ip_addr_clean_and_public","winevent-hostname-cleanup","winevent-user_name-is-machine-account","final-cleanup-message_field"]'

================================================================================
FIELD: etl_host_agent_ephemeral_uid
Non-null: 105,000
Examples:
  'b3180cc3-b555-48e4-bf4a-2f1d515ae983'
  '5501ba76-5651-4f10-9097-29e3b3a3d401'
  'a295b349-de5f-4d13-a76f-7a7eedc435a3'
  'e0c5bf65-34ab-47f0-969f-2cf6a923d5af'
  '82bcb90a-ecef-4973-894a-23b9117904b2'

================================================================================
FIELD: user_account
Non-null: 75,112
Examples:
  'nt authority\\system'
  'desktop-4pvps6e\\louis'
  'nt authority\\network service'
  'nt authority\\local service'

================================================================================
FIELD: task
Non-null: 105,000
Examples:
  'Pipe Connected (rule: PipeEvent)'
  'Pipe Created (rule: PipeEvent)'
  'Process terminated (rule: ProcessTerminate)'
  'Driver loaded (rule: DriverLoad)'
  'File Delete logged (rule: FileDeleteDetected)'

================================================================================
FIELD: SourceUser
Non-null: 4,371
Examples:
  'NT AUTHORITY\\SYSTEM'
  'NT AUTHORITY\\LOCAL SERVICE'
  'NT AUTHORITY\\NETWORK SERVICE'
  'DESKTOP-4PVPS6E\\Louis'

================================================================================
FIELD: target_process_name
Non-null: 4,371
Examples:
  'searchindexer.exe'
  'svchost.exe'
  'system'
  'runtimebroker.exe'
  'beacon.exe'

================================================================================
FIELD: CallTrace
Non-null: 4,371
Examples:
  'C:\\Windows\\SYSTEM32\\ntdll.dll+9405a|C:\\Windows\\system32\\RPCRT4.dll+1bf3f|C:\\Windows\\system32\\lsasrv.dll+16fa1|C:\\Windows\\system32\\SspiSrv.dll+1cc4|C:\\Windows\\system32\\RPCRT4.dll+7b0b3|C:\\Windows\\system32\\RPCRT4.dll+dd903|C:\\Windows\\system32\\RPCRT4.dll+1702c|C:\\Windows\\system32\\RPCRT4.dll+14e93|C:\\Windows\\system32\\RPCRT4.dll+13b1a|C:\\Windows\\system32\\RPCRT4.dll+1464f|C:\\Windows\\system32\\RPCRT4.dll+29cff|C:\\Windows\\system32\\RPCRT4.dll+2a91f|C:\\Windows\\system32\\RPCRT4.dll+58063|C:\\Windows\\system32\\RPCRT4.dll+568d9|C:\\Windows\\system32\\RPCRT4.dll+66ca2|C:\\Windows\\SYSTEM32\\ntdll.dll+3b9a9|C:\\Windows\\SYSTEM32\\ntdll.dll+399fe|C:\\Windows\\system32\\KERNEL32.DLL+12d92|C:\\Windows\\SYSTEM32\\ntdll.dll+9f64'
  'C:\\WINDOWS\\SYSTEM32\\ntdll.dll+9e194|C:\\WINDOWS\\System32\\RPCRT4.dll+3c4f4|C:\\WINDOWS\\System32\\combase.dll+c8e8c|c:\\windows\\system32\\tokenbroker.dll+1da6e|c:\\windows\\system32\\tokenbroker.dll+1d208|c:\\windows\\system32\\tokenbroker.dll+22343|c:\\windows\\system32\\tokenbroker.dll+2a99b|C:\\WINDOWS\\System32\\RPCRT4.dll+796e3|C:\\WINDOWS\\System32\\RPCRT4.dll+dd77b|C:\\WINDOWS\\System32\\RPCRT4.dll+1b9e9|C:\\WINDOWS\\System32\\combase.dll+b63ec|C:\\WINDOWS\\System32\\RPCRT4.dll+5b70b|C:\\WINDOWS\\System32\\combase.dll+8bf33|C:\\WINDOWS\\System32\\combase.dll+8bcbe|C:\\WINDOWS\\System32\\combase.dll+96834|C:\\WINDOWS\\System32\\combase.dll+919a6|C:\\WINDOWS\\System32\\combase.dll+31293|C:\\WINDOWS\\System32\\combase.dll+c8534|C:\\WINDOWS\\System32\\combase.dll+b180d|C:\\WINDOWS\\System32\\combase.dll+25046|C:\\WINDOWS\\System32\\combase.dll+fbc4c|C:\\WINDOWS\\System32\\combase.dll+27009|C:\\WINDOWS\\System32\\RPCRT4.dll+5a278|C:\\WINDOWS\\System32\\RPCRT4.dll+3a416'
  'C:\\Windows\\SYSTEM32\\ntdll.dll+93a8a|C:\\Windows\\system32\\lsasrv.dll+96b3|C:\\Windows\\system32\\lsasrv.dll+71c1|C:\\Windows\\system32\\SspiSrv.dll+12ef|C:\\Windows\\system32\\RPCRT4.dll+7b0b3|C:\\Windows\\system32\\RPCRT4.dll+dd903|C:\\Windows\\system32\\RPCRT4.dll+1702c|C:\\Windows\\system32\\RPCRT4.dll+14e93|C:\\Windows\\system32\\RPCRT4.dll+13b1a|C:\\Windows\\system32\\RPCRT4.dll+1464f|C:\\Windows\\system32\\RPCRT4.dll+29cff|C:\\Windows\\system32\\RPCRT4.dll+2a91f|C:\\Windows\\system32\\RPCRT4.dll+58063|C:\\Windows\\system32\\RPCRT4.dll+568d9|C:\\Windows\\system32\\RPCRT4.dll+66ca2|C:\\Windows\\SYSTEM32\\ntdll.dll+3b9a9|C:\\Windows\\SYSTEM32\\ntdll.dll+399fe|C:\\Windows\\system32\\KERNEL32.DLL+12d92|C:\\Windows\\SYSTEM32\\ntdll.dll+9f64'
  'C:\\Windows\\SYSTEM32\\ntdll.dll+9405a|C:\\Windows\\system32\\RPCRT4.dll+1bf3f|C:\\Windows\\system32\\combase.dll+74f7f|C:\\Windows\\system32\\windows.cortana.Desktop.dll+3b94f|C:\\Windows\\system32\\windows.cortana.Desktop.dll+3c178|C:\\Windows\\system32\\windows.cortana.Desktop.dll+c798|C:\\Windows\\system32\\windows.cortana.Desktop.dll+1d827|C:\\Windows\\system32\\windows.cortana.Desktop.dll+155f|C:\\Windows\\system32\\windows.cortana.Desktop.dll+3d87|C:\\Windows\\system32\\combase.dll+a8017|C:\\Windows\\system32\\combase.dll+a6eef|C:\\Windows\\System32\\RuntimeBroker.exe+1673|C:\\Windows\\system32\\RPCRT4.dll+7b0b3|C:\\Windows\\system32\\RPCRT4.dll+dd903|C:\\Windows\\system32\\RPCRT4.dll+6aa8d|C:\\Windows\\system32\\combase.dll+4bfc|C:\\Windows\\system32\\combase.dll+b4ad2|C:\\Windows\\system32\\combase.dll+84805|C:\\Windows\\system32\\combase.dll+7398e|C:\\Windows\\system32\\combase.dll+75890|C:\\Windows\\system32\\combase.dll+7827f|C:\\Windows\\system32\\combase.dll+773b4|C:\\Windows\\system32\\RPCRT4.dll+14e93|C:\\Windows\\system32\\RPCRT4.dll+13b1a'

In [ ]:
import glob
import polars as pl

FILES = sorted(glob.glob("/content/comiset_parquet/*.parquet"))

schemas = {}

for f in FILES:
    schemas[f] = set(pl.read_parquet_schema(f).keys())

# Union of every column
all_columns = set().union(*schemas.values())

# Columns missing from at least one file
inconsistent = {
    col: [f for f, cols in schemas.items() if col not in cols]
    for col in all_columns
    if any(col not in cols for cols in schemas.values())
}

print(f"Parquet files: {len(FILES)}")
print(f"Total unique columns: {len(all_columns)}")
print(f"Columns present in EVERY file: "
      f"{len(all_columns) - len(inconsistent)}")
print(f"Columns missing from at least one file: {len(inconsistent)}")

if inconsistent:
    print("\n=== INCONSISTENT COLUMNS ===")
    for col, missing_files in sorted(inconsistent.items()):
        print(f"\n{col}")
        print(f"  Missing from: {len(missing_files)} files")
        print(f"  Example: {missing_files[:3]}")
else:
    print("\nAll files have exactly the same columns.")

Parquet files: 517
Total unique columns: 123
Columns present in EVERY file: 17
Columns missing from at least one file: 106

=== INCONSISTENT COLUMNS ===

AppID
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00002.parquet', '/content/comiset_parquet/part-00003.parquet']

Archived
  Missing from: 515 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

CallTrace
  Missing from: 413 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

ClientProcessId
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet', '/content/comiset_parquet/part-00003.parquet']

CommandLine
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

Company
  Missing from: 514 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

Component
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet', '/content/comiset_parquet/part-00003.parquet']

Current State
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

CurrentDirectory
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

Description
  Missing from: 514 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

DestinationHostname
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

DestinationIsIpv6
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

DestinationPort
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

DestinationPortName
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

Details
  Missing from: 505 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

Event Name
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

EventType
  Missing from: 141 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

FileVersion
  Missing from: 514 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

Flags
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00002.parquet', '/content/comiset_parquet/part-00003.parquet']

GrantedAccess
  Missing from: 413 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

Id
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet', '/content/comiset_parquet/part-00003.parquet']

ImageLoaded
  Missing from: 515 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

Initiated
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

IntegrityLevel
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

IsExecutable
  Missing from: 515 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

LogonGuid
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

LogonId
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

ModifyingUser
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00003.parquet']

Name
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00002.parquet', '/content/comiset_parquet/part-00003.parquet']

Operation
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet', '/content/comiset_parquet/part-00003.parquet']

OriginalFileName
  Missing from: 514 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

ParentCommandLine
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

ParentUser
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

PipeName
  Missing from: 509 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

PossibleCause
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet', '/content/comiset_parquet/part-00003.parquet']

Product
  Missing from: 514 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

Protocol
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

ResultCode
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet', '/content/comiset_parquet/part-00003.parquet']

RuleName
  Missing from: 6 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

SettingType
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00003.parquet']

SettingValue
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00003.parquet']

SettingValueDisplay
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00003.parquet']

Signature
  Missing from: 515 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

SignatureStatus
  Missing from: 515 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

Signed
  Missing from: 515 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

SourceHostname
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

SourceIsIpv6
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

SourcePort
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

SourcePortName
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

SourceThreadId
  Missing from: 413 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

SourceUser
  Missing from: 413 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

State Machine
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

State Machine Name
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

TargetFilename
  Missing from: 504 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

TargetObject
  Missing from: 149 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

TargetUser
  Missing from: 413 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

TerminalSessionId
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

Thread ID
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

User
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet', '/content/comiset_parquet/part-00003.parquet']

dst_ip_addr
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

dst_ip_public
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

dst_ip_rfc
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

dst_ip_type
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

dst_ip_version
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

dst_is_ipv6
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

event_recorded_time
  Missing from: 6 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

file_creation_time
  Missing from: 506 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

file_previous_creation_time
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

hash_imphash
  Missing from: 512 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

hash_md5
  Missing from: 512 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

hash_sha1
  Missing from: 512 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

hash_sha256
  Missing from: 512 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

keywords
  Missing from: 514 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00002.parquet', '/content/comiset_parquet/part-00005.parquet']

meta_user_name_is_machine
  Missing from: 108 files
  Example: ['/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet', '/content/comiset_parquet/part-00003.parquet']

object_handle_id
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

object_name
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

object_new_sd
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

object_old_sd
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

object_server
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

process_guid
  Missing from: 6 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

process_id_orig
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

process_name
  Missing from: 5 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

process_parent_guid
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

process_parent_id
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

process_parent_name
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

process_parent_path
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

process_path
  Missing from: 5 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

rule_technique_id
  Missing from: 487 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

rule_technique_name
  Missing from: 487 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

src_ip_addr
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

src_ip_public
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

src_ip_rfc
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

src_ip_type
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

src_ip_version
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

src_is_ipv6
  Missing from: 502 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

target_process_guid
  Missing from: 413 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

target_process_id
  Missing from: 413 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

target_process_name
  Missing from: 413 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

target_process_path
  Missing from: 413 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

user_account
  Missing from: 110 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

user_domain
  Missing from: 108 files
  Example: ['/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet', '/content/comiset_parquet/part-00003.parquet']

user_logon_id
  Missing from: 516 files
  Example: ['/content/comiset_parquet/part-00000.parquet', '/content/comiset_parquet/part-00001.parquet', '/content/comiset_parquet/part-00002.parquet']

user_name
  Missing from: 108 files

In [ ]:
common = set.intersection(*schemas.values())

print(f"Columns in EVERY file: {len(common)}\n")

for col in sorted(common):
    print(col)

Columns in EVERY file: 17

@timestamp
etl_host_agent_ephemeral_uid
etl_pipeline
etl_processed_time
event_id
event_original_message
event_original_time
host_name
level
log_name
opcode
process_id
provider_guid
source_name
task
thread_id
z_elastic_ecs

In [ ]:
from collections import Counter

column_counts = Counter()

for cols in schemas.values():
    column_counts.update(cols)

print(f"{'Column':40} {'Files':>7} {'Coverage':>10}")
print("-" * 60)

for col, count in sorted(column_counts.items(), key=lambda x: -x[1]):
    coverage = count / len(FILES) * 100
    print(f"{col:40} {count:7} {coverage:9.1f}%")

Column                                     Files   Coverage
------------------------------------------------------------
task                                         517     100.0%
etl_processed_time                           517     100.0%
level                                        517     100.0%
etl_host_agent_ephemeral_uid                 517     100.0%
process_id                                   517     100.0%
thread_id                                    517     100.0%
opcode                                       517     100.0%
log_name                                     517     100.0%
source_name                                  517     100.0%
z_elastic_ecs                                517     100.0%
event_id                                     517     100.0%
host_name                                    517     100.0%
event_original_time                          517     100.0%
etl_pipeline                                 517     100.0%
@timestamp                                   517     100.0%
event_original_message                       517     100.0%
provider_guid                                517     100.0%
process_name                                 512      99.0%
process_path                                 512      99.0%
version                                      511      98.8%
process_guid                                 511      98.8%
event_recorded_time                          511      98.8%
RuleName                                     511      98.8%
user_name                                    409      79.1%
user_domain                                  409      79.1%
meta_user_name_is_machine                    409      79.1%
user_account                                 407      78.7%
EventType                                    376      72.7%
TargetObject                                 368      71.2%
GrantedAccess                                104      20.1%
SourceThreadId                               104      20.1%
TargetUser                                   104      20.1%
target_process_name                          104      20.1%
CallTrace                                    104      20.1%
target_process_guid                          104      20.1%
SourceUser                                   104      20.1%
target_process_path                          104      20.1%
target_process_id                            104      20.1%
rule_technique_id                             30       5.8%
rule_technique_name                           30       5.8%
SourcePortName                                15       2.9%
dst_ip_rfc                                    15       2.9%
DestinationIsIpv6                             15       2.9%
SourcePort                                    15       2.9%
dst_ip_public                                 15       2.9%
DestinationPort                               15       2.9%
src_ip_public                                 15       2.9%
src_ip_type                                   15       2.9%
dst_ip_addr                                   15       2.9%
SourceIsIpv6                                  15       2.9%
dst_ip_version                                15       2.9%
src_ip_version                                15       2.9%
SourceHostname                                15       2.9%
src_is_ipv6                                   15       2.9%
dst_ip_type                                   15       2.9%
src_ip_addr                                   15       2.9%
DestinationHostname                           15       2.9%
Protocol                                      15       2.9%
DestinationPortName                           15       2.9%
src_ip_rfc                                    15       2.9%
dst_is_ipv6                                   15       2.9%
Initiated                                     15       2.9%
TargetFilename                                13       2.5%
Details                                       12       2.3%
file_creation_time                            11       2.1%
PipeName                                       8       1.5%
hash_imphash                                   5       1.0%
hash_sha256                                    5       1.0%
hash_md5                                       5       1.0%
hash_sha1                                      5       1.0%
keywords                                       3       0.6%
OriginalFileName                               3       0.6%
Company                                        3       0.6%
Product                                        3       0.6%
FileVersion                                    3       0.6%
Description                                    3       0.6%
SignatureStatus                                2       0.4%
ImageLoaded                                    2       0.4%
Signature                                      2       0.4%
Signed                                         2       0.4%
Archived                                       2       0.4%
IsExecutable                                   2       0.4%
ResultCode                                     1       0.2%
Component                                      1       0.2%
xml_name                                       1       0.2%
PossibleCause                                  1       0.2%
User                                           1       0.2%
Operation                                      1       0.2%
Id                                             1       0.2%
ClientProcessId                                1       0.2%
AppID                                          1       0.2%
Flags                                          1       0.2%
Name                                           1       0.2%
SettingValue                                   1       0.2%
ModifyingUser                                  1       0.2%
SettingType                                    1       0.2%
SettingValueDisplay                            1       0.2%
Thread ID                                      1       0.2%
Current State                                  1       0.2%
Event Name                                     1       0.2%
State Machine                                  1       0.2%
State Machine Name                             1       0.2%
object_name                                    1       0.2%
object_handle_id                               1       0.2%
user_sid                                       1       0.2%
object_server                                  1       0.2%
process_id_orig                                1       0.2%
user_logon_id                                  1       0.2%
object_old_sd                                  1       0.2%
object_new_sd                                  1       0.2%
process_parent_id                              1       0.2%
process_parent_guid                            1       0.2%
LogonId                                        1       0.2%
CurrentDirectory                               1       0.2%
ParentCommandLine                              1       0.2%
process_parent_path                            1       0.2%
IntegrityLevel                                 1       0.2%
process_parent_name                            1       0.2%
TerminalSessionId                              1       0.2%
ParentUser                                     1       0.2%
LogonGuid                                      1       0.2%
CommandLine                                    1       0.2%
file_previous_creation_time                    1       0.2%

so far the number of fields turned out to be 123 while the expected were 789 (before the parquet conversion) so i will have to repeat the conversion

In [ ]:
import os
import json
import shutil
import pyarrow as pa
import pyarrow.parquet as pq

JSONL_PATH = "./comiset_lab_cleaned.jsonl.gz"
OUT_DIR = "./comiset_parquet_v2"

BATCH_SIZE = 200_000

# PASS 1: Get the complete field set

print("Pass 1: finding all fields...")

all_fields = set()

with gzip.open(JSONL_PATH, "rt", encoding="utf-8") as f:
    for line in f:
        if not line.strip():
            continue

        event = json.loads(line)
        all_fields.update(event.get("_source", {}).keys())

all_fields = sorted(all_fields)

print(f"Total fields found: {len(all_fields)}")

# Fixed schema: EVERY Parquet shard will have every field

schema = pa.schema([(field, pa.string()) for field in all_fields])

# Convert values to strings consistently

def normalize_value(value):
    if value is None:
        return None

    if isinstance(value, (dict, list)):
        return json.dumps(
            value,
            ensure_ascii=False,
            separators=(",", ":")
        )

    if isinstance(value, bool):
        return str(value).lower()

    return str(value)

# PASS 2: Convert JSONL → Parquet

print("\nPass 2: converting to Parquet...")

if os.path.exists(OUT_DIR):
    shutil.rmtree(OUT_DIR)

os.makedirs(OUT_DIR)

batch = []
shard_number = 0
total_rows = 0

writer = None

with gzip.open(JSONL_PATH, "rt", encoding="utf-8") as f:

    for line in f:
        if not line.strip():
            continue

        event = json.loads(line)
        source = event.get("_source", {})

        # Only store fields that actually exist in this event.
        # The fixed Arrow schema will create nulls for missing fields.
        row = {
            field: normalize_value(source[field])
            for field in source
        }

        batch.append(row)

        if len(batch) >= BATCH_SIZE:

            table = pa.Table.from_pylist(
                batch,
                schema=schema
            )

            output_path = os.path.join(
                OUT_DIR,
                f"part-{shard_number:05d}.parquet"
            )

            pq.write_table(
                table,
                output_path,
                compression="zstd"
            )

            total_rows += len(batch)
            shard_number += 1
            batch.clear()

            print(
                f"Shard {shard_number:04d} | "
                f"Rows: {total_rows:,}")

# Final batch
if batch:
    table = pa.Table.from_pylist(batch, schema=schema)

    output_path = os.path.join(OUT_DIR, f"part-{shard_number:05d}.parquet")

    pq.write_table(table, output_path, compression="zstd")

    total_rows += len(batch)
    shard_number += 1

print("\nDONE")
print(f"Total rows:   {total_rows:,}")
print(f"Total fields: {len(all_fields)}")
print(f"Parquet files: {shard_number}")
print(f"Output: {OUT_DIR}")

this correctly gets the full 789 fields :)

spliting the 130 parquet files into finer 1300 files for better memory managment

In [ ]:
import gc
import glob, re, math
import polars as pl
import pandas as pd
import os
PARQUET_DIR = "/content/comiset_parquet_v11/content/comiset_parquet_v11"
FILES = sorted(glob.glob(f"{PARQUET_DIR}/*.parquet"))
OUTPUT_DIR = "/content/comiset_parquet_v12_split"
os.makedirs(OUTPUT_DIR, exist_ok=True)
for j, f in enumerate(FILES):
    df = pl.read_parquet(f)
    n = df.height // 10

    for i in range(10):
        part = df.slice(i * n, n if i < 9 else df.height - i * n)

        name = f"part-{j*10 + i}.parquet"
        part.write_parquet(os.path.join(OUTPUT_DIR, name))

        del part
        gc.collect()

    del df
    gc.collect()

splitting the 130-file folder into 5 folders of 26 file each instead so that memory doesnt crash

In [ ]:
import os
import glob
import shutil

INPUT_DIR = "/content/comiset_parquet_v11/content/comiset_parquet_v11"
FILES = sorted(glob.glob(f"{INPUT_DIR}/*.parquet"))

for i in range(5):
    folder = f"/content/comiset_parquet_v11_group_{i+1}"
    os.makedirs(folder, exist_ok=True)

    for f in FILES[i * 26:(i + 1) * 26]:
        shutil.copy2(f, folder)

print("Done.")

Done.

**the** **profiler**

In [ ]:
# @title
import glob, re, math
import polars as pl
import pandas as pd

PARQUET_DIR = "/content/comiset_parquet_v11/content/comiset_parquet_v11"
FILES = sorted(glob.glob(f"{PARQUET_DIR}/*.parquet"))
ROWS_PER_FILE = 2000
N_EXAMPLES = 5

print(f"Files: {len(FILES)}, rows/file: {ROWS_PER_FILE}")

INT_RE = re.compile(r"^[+-]?\d+$")
FLOAT_RE = re.compile(r"^[+-]?(?:\d+\.\d*|\.\d+|\d+\.?\d*[eE][+-]?\d+)$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}")
BOOLS = {"true", "false"}

def is_int(x): return bool(INT_RE.match(x))
def is_float(x): return bool(FLOAT_RE.match(x))
def is_date(x): return bool(DATE_RE.match(x))
def is_bool(x): return x.lower() in BOOLS

def is_identifier(name, values):
    name = name.lower()
    keywords = ["id", "guid", "uuid", "hash", "pid", "tid", "uid",
                "identifier", "session", "token"]
    return any(k in name for k in keywords) or (
        values and len(set(values)) / len(values) > 0.8
    )

# Sample without loading entire shards
samples = []
for i, f in enumerate(FILES):
    try:
        samples.append(pl.read_parquet(f, n_rows=ROWS_PER_FILE))
    except Exception as e:
        print(f"Failed: {f}\n{e}")
    if (i + 1) % 50 == 0:
        print(f"Read {i + 1}/{len(FILES)} files")

df = pl.concat(samples, how="diagonal_relaxed")
print("Sample shape:", df.shape)

results = []

for i, col in enumerate(df.columns):
    values = [str(x) for x in df[col].drop_nulls().to_list()]
    n = len(values)
    total = df.height

    if not n:
        results.append({
            "field": col, "sample_rows": total, "non_null": 0,
            "null_pct": 100, "unique_count": 0, "unique_ratio": 0,
            "integer_pct": 0, "float_pct": 0, "numeric_pct": 0,
            "datetime_pct": 0, "boolean_pct": 0,
            "identifier_candidate": False, "min_numeric": None,
            "max_numeric": None, "avg_string_length": None, "examples": []
        })
        continue

    ints = sum(is_int(x) for x in values)
    floats = sum(is_float(x) for x in values)
    nums = []
    for x in values:
        try: nums.append(float(x))
        except: pass

    date_candidates = [x for x in values if is_date(x)]
    dates = 0
    for x in date_candidates:
        try:
            pd.to_datetime(x, errors="raise", utc=True)
            dates += 1
        except: pass

    bools = sum(is_bool(x) for x in values)
    unique = set(values)

    results.append({
        "field": col,
        "sample_rows": total,
        "non_null": n,
        "null_pct": 100 * (total - n) / total,
        "unique_count": len(unique),
        "unique_ratio": len(unique) / n,
        "integer_pct": 100 * ints / n,
        "float_pct": 100 * floats / n,
        "numeric_pct": 100 * len(nums) / n,
        "datetime_pct": 100 * dates / n,
        "boolean_pct": 100 * bools / n,
        "identifier_candidate": is_identifier(col, values),
        "min_numeric": min(nums) if nums else None,
        "max_numeric": max(nums) if nums else None,
        "avg_string_length": sum(map(len, values)) / n,
        "examples": list(unique)[:N_EXAMPLES]
    })

    if (i + 1) % 100 == 0:
        print(f"Profiled {i + 1}/{len(df.columns)} columns")


profile = pd.DataFrame(results)
profile.to_parquet("comiset_column_profile.parquet", index=False)
profile.to_csv("comiset_column_profile.csv", index=False)

print("Profile shape:", profile.shape)
display(profile)

Files: 130, rows/file: 2000
Read 50/130 files
Read 100/130 files
Sample shape: (260000, 445)
Profiled 100/445 columns
Profiled 200/445 columns
Profiled 300/445 columns
Profiled 400/445 columns
Profile shape: (445, 16)

,field,sample_rows,non_null,null_pct,unique_count,unique_ratio,integer_pct,float_pct,numeric_pct,datetime_pct,boolean_pct,identifier_candidate,min_numeric,max_numeric,avg_string_length,examples
0,@timestamp,260000,260000,0.000000,163825,0.630096,0.0,0.0,0.0,100.0,0.0,False,NaN,NaN,31.990146,"[2022-11-20 20:36:36.151000+00:00, 2022-11-24 ..."
1,AccountName,260000,30,99.988462,2,0.066667,0.0,0.0,0.0,0.0,0.0,False,NaN,NaN,11.266667,"[device owners, localsystem]"
2,Action,260000,4,99.998462,1,0.250000,100.0,0.0,100.0,0.0,0.0,False,2.0,2.0,1.000000,[2]
3,Action ID,260000,1,99.999615,1,1.000000,100.0,0.0,100.0,0.0,0.0,True,2.0,2.0,1.000000,[2]
4,Action Name,260000,1,99.999615,1,1.000000,0.0,0.0,0.0,0.0,0.0,True,NaN,NaN,5.000000,[%%809]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,user_name,260000,202519,22.108077,9,0.000044,0.0,0.0,0.0,0.0,0.0,False,NaN,NaN,6.300298,"[dwm-2, umfd-1, louis, system, local service]"
441,user_sid,260000,1728,99.335385,2,0.001157,0.0,0.0,0.0,0.0,0.0,True,NaN,NaN,8.043981,[S-1-5-21-1311114680-1922563338-3976463898-100...
442,version,260000,254601,2.076538,5,0.000020,100.0,0.0,100.0,0.0,0.0,False,1.0,5.0,1.000000,"[4, 2, 1, 5, 3]"
443,xml_name,260000,155,99.940385,9,0.058065,0.0,0.0,0.0,0.0,0.0,False,NaN,NaN,19.380645,"[UMDFHostProblem, Operation_ClientFailure, Add..."
444,z_elastic_ecs,260000,260000,0.000000,168301,0.647312,0.0,0.0,0.0,0.0,0.0,False,NaN,NaN,351.421181,"[{""agent"":{},""ecs"":{""version"":""8.0.0""},""user"":..."

In [ ]:
import gc
del df
del samples
gc.collect()

0

save profiler

In [ ]:
profile.to_parquet("/content/comiset_column_profile.parquet", index=False)
profile.to_csv("/content/comiset_column_profile.csv", index=False)
# pd.DataFrame(results).to_parquet("/content/comiset_results.parquet", index=False)

read profiler from disk

In [ ]:
import pandas as pd

profile = pd.read_parquet("/content/comiset_column_profile.parquet")

=======================================================================================

deleting sparse fields (that have less than 100 occurances over the 25 M datapoint)

In [ ]:
# @title
empty_candidates = profile.loc[ profile.non_null == 0, "field"].tolist()

counts = {c: 0 for c in empty_candidates}

# for i, f in enumerate(FILES):
#     df = pl.read_parquet(f, columns=empty_candidates)

#     for col in empty_candidates:
#         counts[col] += df[col].is_not_null().sum()

#     del df

#     print(f"{i + 1}/{len(FILES)}")

sparsity = pd.DataFrame({ "field": list(counts.keys()), "non_null_count": list(counts.values()) })

total_rows = sum( pl.scan_parquet(f).select(pl.len()).collect().item() for f in FILES)

print("Total rows:", total_rows)

sparsity["non_null_pct"] = (
    sparsity["non_null_count"] / total_rows * 100
)

display(
    sparsity.sort_values("non_null_count", ascending=False)
)

Total rows: 25814017

Empty DataFrame
Columns: [field, non_null_count, non_null_pct]
Index: []

In [ ]:
# @title
ALL_COLS = pl.read_parquet(FILES[0], n_rows=0).columns

DROP_COLS = set(
    sparsity.loc[sparsity.non_null_count < 100, "field"]
)

KEEP_COLS = [c for c in ALL_COLS if c not in DROP_COLS]

print("Original:", len(ALL_COLS))
print("Dropped:", len(DROP_COLS))
print("Remaining:", len(KEEP_COLS))

Original: 552
Dropped: 0
Remaining: 552

In [ ]:
# @title
import os

OUT_DIR = "./comiset_parquet_v7"
os.makedirs(OUT_DIR, exist_ok=True)

for i, f in enumerate(FILES):
    df = pl.read_parquet(f, columns=KEEP_COLS)
    out = f"{OUT_DIR}/{os.path.basename(f)}"
    df.write_parquet(out, compression="zstd")
    del df

    print(f"{i+1}/{len(FILES)}")

1/130
2/130
3/130
4/130
5/130
6/130
7/130
8/130
9/130
10/130
11/130
12/130
13/130
14/130
15/130
16/130
17/130
18/130
19/130
20/130
21/130
22/130
23/130
24/130
25/130
26/130
27/130
28/130
29/130
30/130
31/130
32/130
33/130
34/130
35/130
36/130
37/130
38/130
39/130
40/130
41/130
42/130
43/130
44/130
45/130
46/130
47/130
48/130
49/130
50/130
51/130
52/130
53/130
54/130
55/130
56/130
57/130
58/130
59/130
60/130
61/130
62/130
63/130
64/130
65/130
66/130
67/130
68/130
69/130
70/130
71/130
72/130
73/130
74/130
75/130
76/130
77/130
78/130
79/130
80/130
81/130
82/130
83/130
84/130
85/130
86/130
87/130
88/130
89/130
90/130
91/130
92/130
93/130
94/130
95/130
96/130
97/130
98/130
99/130
100/130
101/130
102/130
103/130
104/130
105/130
106/130
107/130
108/130
109/130
110/130
111/130
112/130
113/130
114/130
115/130
116/130
117/130
118/130
119/130
120/130
121/130
122/130
123/130
124/130
125/130
126/130
127/130
128/130
129/130
130/130

In [ ]:
profile = profile[profile["field"].isin(KEEP_COLS)].copy()

In [ ]:
# @title
display(
    profile[
        (profile["numeric_pct"] >= 50) |
        (profile["datetime_pct"] >= 50) |
        (profile["boolean_pct"] >= 50)
    ][[
        "field",
        "null_pct",
        "unique_count",
        "unique_ratio",
        "integer_pct",
        "float_pct",
        "numeric_pct",
        "datetime_pct",
        "boolean_pct",
        "identifier_candidate",
        "min_numeric",
        "max_numeric",
        "examples"
    ]]
    .sort_values(
        ["numeric_pct", "datetime_pct"],
        ascending=False
    )
)

,field,null_pct,unique_count,unique_ratio,integer_pct,float_pct,numeric_pct,datetime_pct,boolean_pct,identifier_candidate,min_numeric,max_numeric,examples
2,Action,99.998462,1,0.250000,100.0,0.0,100.0,0.0,0.0,False,2.0,2.0,[2]
3,Action ID,99.999615,1,1.000000,100.0,0.0,100.0,0.0,0.0,True,2.0,2.0,[2]
9,Additional Actions ID,99.999615,1,1.000000,100.0,0.0,100.0,0.0,0.0,True,0.0,0.0,[0]
12,AddressLength,99.972692,2,0.028169,100.0,0.0,100.0,0.0,0.0,False,16.0,128.0,"[16, 128]"
20,BootStatusPolicy,99.996923,2,0.250000,100.0,0.0,100.0,0.0,0.0,False,1.0,2.0,"[1, 2]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
439,dst_ip_public,95.608077,2,0.000175,0.0,0.0,0.0,0.0,100.0,False,NaN,NaN,"[true, false]"
443,dst_is_ipv6,95.608077,1,0.000088,0.0,0.0,0.0,0.0,100.0,False,NaN,NaN,[false]
479,meta_user_name_is_machine,22.108077,2,0.000010,0.0,0.0,0.0,0.0,100.0,False,NaN,NaN,"[true, false]"
523,src_ip_public,95.602692,1,0.000087,0.0,0.0,0.0,0.0,100.0,False,NaN,NaN,[false]
527,src_is_ipv6,95.602692,2,0.000175,0.0,0.0,0.0,0.0,100.0,False,NaN,NaN,"[true, false]"

In [ ]:
display(profile[profile["unique_ratio"] <= 0.005].sort_values("non_null")[["field","non_null","null_pct", "numeric_pct", "unique_count", "unique_ratio", "examples"]])

,field,non_null,null_pct,numeric_pct,unique_count,unique_ratio,examples
411,object_old_sd,1231,99.526538,0.000000,2,0.001625,"[S:AI(AU;OICIIDSAFA;0x10d0000;;;WD), S:AINO_AC..."
410,object_new_sd,1725,99.336538,0.000000,4,0.002319,[S:ARAI(AU;SAFA;DCLCRPCRSDWDWO;;;WD)(AU;IDSAFA...
412,object_server,1725,99.336538,0.000000,1,0.000580,[Security]
467,user_sid,1728,99.335385,0.000000,2,0.001157,"[S-1-5-18, S-1-5-21-1311114680-1922563338-3976..."
465,user_logon_id,1728,99.335385,100.000000,2,0.001157,"[872838, 999]"
47,DestinationIsIpv6,11419,95.608077,0.000000,1,0.000088,[false]
123,Initiated,11419,95.608077,0.000000,2,0.000175,"[true, false]"
46,DestinationHostname,11419,95.608077,0.000000,1,0.000088,[-]
364,dst_ip_addr,11419,95.608077,0.000000,22,0.001927,"[192.168.21.1, 192.168.182.128, 192.168.235.12..."
365,dst_ip_public,11419,95.608077,0.000000,2,0.000175,"[true, false]"
367,dst_ip_type,11419,95.608077,0.000000,2,0.000175,"[public, private]"
368,dst_ip_version,11419,95.608077,100.000000,1,0.000088,[4]
366,dst_ip_rfc,11419,95.608077,0.000000,2,0.000175,"[RFC_1366, RFC_1918]"
290,SourcePortName,11419,95.608077,0.000000,1,0.000088,[-]
48,DestinationPort,11419,95.608077,100.000000,9,0.000788,"[5044, 80, 81, 4444, 88]"
49,DestinationPortName,11419,95.608077,0.000000,1,0.000088,[-]
369,dst_is_ipv6,11419,95.608077,0.000000,1,0.000088,[false]
287,SourceHostname,11419,95.608077,0.000000,1,0.000088,[-]
288,SourceIsIpv6,11419,95.608077,0.000000,1,0.000088,[false]
231,Protocol,11424,95.606154,0.043768,4,0.000350,"[6, 256, tcp, 17]"
442,src_ip_public,11433,95.602692,0.000000,1,0.000087,[false]
441,src_ip_addr,11433,95.602692,0.000000,30,0.002624,"[192.168.5.137, 192.168.232.150, 192.168.16.12..."
445,src_ip_version,11433,95.602692,100.000000,2,0.000175,"[6, 4]"
446,src_is_ipv6,11433,95.602692,0.000000,2,0.000175,"[true, false]"
443,src_ip_rfc,11433,95.602692,0.000000,2,0.000175,"[RFC_4291, RFC_1918]"
444,src_ip_type,11433,95.602692,0.000000,2,0.000175,"[loopback, private]"
437,rule_technique_id,16187,93.774231,0.006178,34,0.002100,"[T1021, T1546.001, T1123, T1218, 1210]"
438,rule_technique_name,16191,93.772692,0.000000,34,0.002100,"[Windows Scheduled Tasks, Signed Binary Proxy ..."
112,GrantedAccess,53128,79.566154,0.000000,9,0.000169,"[0x3600, 0x1fffff, 0x1410, 0x1400, 0x101000]"
292,SourceUser,53216,79.532308,0.000000,6,0.000113,"[NT AUTHORITY\SYSTEM, DESKTOP-4PVPS6E\Louis, N..."
326,TargetUser,53216,79.532308,0.000000,12,0.000225,"[Font Driver Host\UMFD-4, NT AUTHORITY\SYSTEM,..."
453,target_process_name,53217,79.531923,0.000000,158,0.002969,"[xwin_mobax.exe, vm3dservice.exe, mcbuilder.ex..."
454,target_process_path,53217,79.531923,0.000000,187,0.003514,"[c:\users\louis\downloads\a.exe, c:\windows\mi..."
93,EventType,184843,28.906538,0.000000,6,0.000032,"[DeleteValue, DeleteKey, SetValue, CreateKey, ..."
463,user_account,200762,22.783846,0.000000,8,0.000040,"[desktop-4pvps6e\louis, font driver host\umfd-..."
405,meta_user_name_is_machine,202519,22.108077,0.000000,2,0.000010,"[true, false]"
466,user_name,202519,22.108077,0.000000,9,0.000044,"[dwm-1, system, network service, dwm-2, louis]"
464,user_domain,202519,22.108077,0.000000,5,0.000025,"[nt authority, desktop-4pvps6e, font driver ho..."
250,RuleName,254007,2.305000,0.000000,43,0.000169,"[technique_id=T1218,technique_name=Signed Bina..."
468,version,254601,2.076538,100.000000,5,0.000020,"[3, 5, 1, 4, 2]"
430,process_name,255800,1.615385,0.000000,125,0.000489,"[mcbuilder.exe, wmiadap.exe, wuauclt.exe, fire..."
435,process_path,255800,1.615385,0.000000,144,0.000563,"[c:\users\louis\downloads\a.exe, c:\windows\mi..."
436,provider_guid,259816,0.070769,0.000000,79,0.000304,"[15A7A4F8-0072-4EAB-ABAD-F98A4D666AED, 5D89691..."
456,thread_id,259857,0.055000,100.000000,904,0.003479,"[316, 728, 1128, 1568, 356]"
428,process_id,259857,0.055000,100.000000,1246,0.004795,"[5660, 716, 896, 3920, 596]"
413,opcode,259938,0.023846,0.000000,30,0.000115,"[Start, Dispatch Event, Change State, Stop pum..."
371,etl_host_agent_ephemeral_uid,260000,0.000000,0.000000,96,0.000369,"[5d2525e9-5870-4d1c-a0f6-60c00f6d8925, b44ebe6..."
372,etl_pipeline,260000,0.000000,0.000000,38,0.000146,"[[""all-filter-0098"",""all-add_processed_timesta..."
401,log_name,260000,0.000000,0.000000,36,0.000138,"[Microsoft-Windows-AAD/Operational, Microsoft-..."
400,level,260000,0.000000,0.000000,5,0.000019,"[warning, error, information, critical, verbose]"
374,event_id,260000,0.000000,100.000000,260,0.001000,"[8000, 2024, 4126, 28125, 8013]"
387,host_name,260000,0.000000,0.000000,1,0.000004,[desktop-4pvps6e.phoenix.local]
455,task,260000,0.000000,0.000000,110,0.000423,"[LM, File created (rule: FileCreate), File cre..."
440,source_name,260000,0.000000,0.000000,66,0.000254,"[Microsoft-Windows-Kernel-EventTracing, BROWSE..."

classifing the cols using the profiler

In [ ]:
# @title
#classifing the cols using the profiler
NUMERIC = set()
CATEGORICAL = set()
DATETIME = set()
DROP = set()
numeric_candidates = profile[
    profile["numeric_pct"] >= 95
].sort_values("unique_count", ascending=False)

categorical_candidates = profile[
    (profile["numeric_pct"] < 95) &
    (profile["datetime_pct"] < 95)
].sort_values("unique_count")

datetime_candidates = profile[
    (profile["numeric_pct"] < 95) &
    (profile["datetime_pct"] >= 95)
].sort_values("unique_count")
datetime_candidates.field.to_list()

['Detection Time',
 'PreviousTime',
 'process_creation_time',
 'StopTime',
 'ProcessCreationTime',
 'Created',
 'Expires',
 'file_previous_creation_time',
 'OldTime',
 'NewTime',
 'StartTime',
 'DeviceTime',
 'file_creation_time',
 'etl_processed_time',
 'event_original_time',
 '@timestamp',
 'event_recorded_time']

======================================================================================================================================

handling the really high cardinality fields

In [ ]:
display(profile[profile["field"].isin(CATEGORICAL)& ~profile["field"].isin(FEATURE_ENGINEERING_COLUMNS) & ( profile["unique_count"] >=250)][["field", "examples","unique_count", "non_null"]])

,field,examples,unique_count,non_null
361,event_id,"[4017, 117, 18, 5322, 1501]",260,260000
444,z_elastic_ecs,"[{""agent"":{},""event"":{""created"":""2022-11-19T13...",168301,260000

In [ ]:
profile.loc[
    profile["field"].isin(CATEGORICAL)
    & ~profile["field"].isin(FEATURE_ENGINEERING_COLUMNS),
    "unique_count"
].sum()

np.int64(3035)

In [ ]:
display(profile[profile["field"] == "SourceThreadId" ])

Empty DataFrame
Columns: [field, sample_rows, non_null, null_pct, unique_count, unique_ratio, integer_pct, float_pct, numeric_pct, datetime_pct, boolean_pct, identifier_candidate, min_numeric, max_numeric, avg_string_length, examples]
Index: []

dividing the fields into numeric datetime and categorical

In [ ]:
# @title

NUMERIC = {
    "SourcePort","DestinationPort","Port","bytesTransferred","bytesTotal","fileLength",
    "HiveNameLength","NameLength","KeyLength","FileNameLength","AddressLength",
    "DeviceNameLength","DomainNameLength","ExtraInfoLength","TransportNameLength",
    "ProcessingTimeInMilliseconds","OperationElaspedTimeInMilliSeconds",
    "SessionTimeElapsedInMilliseconds","PolicyElaspedTimeInSeconds",
    "GpsvcTimeElapsedInMilliseconds","GpsvcInitTimeElapsedInMilliseconds",
    "PolicyDownloadTimeElapsedInMilliseconds","GPODownloadTimeElapsedInMilliseconds",
    "WinlogonReturnTimeElapsedInMilliseconds","TimeWaitedAtStartup",
    "Scan Time Minutes","Scan Time Seconds","IdleSeconds","IdleSeconds1",
    "NewSize","OriginalSize","DirtyPages","KeysUpdated","updateCount",
    "CountOfCredentialsReturned","ErrorSourceCount","RetryMinutes","MaxTimeToWait",
    "PrevAvgWaitTimeout","NewAvgWaitTimeout","LinkSpeed","TimezoneBiasHour","DeviceVersionMajor",
    "ErrorSourceTableLength","IfIndex","InterfaceIndex","IpPort",
    "Line Number",
    "NominalFrequency",
    "Number",
    "ServerNameLength",
    "updateRevisionNumber",
}

DATETIME = {
    "@timestamp", "DriverDate","LastRunDateTime","fileTime",
    "Created",
    "Detection Time",
    "DeviceTime",
    "Expires",
    "NewTime",
    "OldTime",
    "PreviousTime",
    "ProcessCreationTime",
    "StartTime",
    "StopTime",
    "etl_processed_time",
    "event_original_time",
    "event_recorded_time",
    "file_creation_time",
    "file_previous_creation_time",
    "process_creation_time",
}

CATEGORICAL = {
    "Action Name","DestinationPortName","Detection ID","Detection User","DriverInbox",
    "DisplayName","Domain","Category Name","Capability","Build Name","DriverProvider",
    "FWLink","FileNameBuffer","Execution Name","Error Description","EmbeddedContext",
    "Engine Version","LocalPath","key_name","key_type","key_return_code","key_file_path",
    "jobName","host_name","OSName","NewStateName","LoadOptions","LicenseId",
    "ModifyingApplication","PossibleCause","Origin Name","OutrankedDrivers",
    "ReadOperation","ReasonString","RemotePorts","object_server","Product Name",
    "PreviousStateName","PackageName","Product Version","LocalPorts","Location",
    "Scan ID","SID","Scan Type","Severity Name","SettingValueDisplay","SessionName",
    "param9","WorkstationName","Version","UserSid","UserId","UpdateService",
    "Update Type","Type Name","Additional Actions String","AssociateId",
    "DescriptionString","Signature Version","SourceHostname","Source Name",
    "StateTransition","TargetOutboundUserName","Threat Name",
    "TargetOutboundDomainName","TargetLogonGuid","StateName","StartFunction",
    "Signature Type","Scan Parameters","Component","Code","DestinationHostname",
    "ChannelPath","ImpersonationLevel","KeyName","MatchingDeviceId",
    "ErrorSourceTable","DriverSection","FailureReason","Problem",
    "OperationDescription","OldSchemeGuid","PrimaryService","NewSchemeGuid",
    "PrincipalSamName","FunctionName","InstancePath","EventName","AccountName",
    "AdapterName","ModifyingUser","ErrorDescription","TransportProtocolName",
    "TargetInfo","TargetServerName","StartModule","ServiceType","SetupClass",
    "AuthenticationPackageName","ApplicationPath","TransportType","DriverVersion",
    "InterfaceName","DriverDescription","ConnectionName","jobOwner",
    "PolicyActivityId","OperationParameter1","InterfaceGuid","Target","param8",
    "string2","Command","ClassGuid","object_new_sd","Protocol","TransportName",
    "SubjectDomainName","IntegrityLevel","param6","ServerName","ErrorMessage",
    "serviceGuid","ResourceURI","user_domain","Signature","User","ParentUser",
    "PrivilegeList","LogonProcessName","Process Name","string","src_original_value",
    "tags","Company","TargetDomainName","SourceUser","meta_dst_ip_geo","DriveName",
    "EventType","DriverFileName","param7","RuleId","SubjectUserSid",
    "SubjectUserName","name","InfoDescription","ExtraInfoString","DriverName",
    "StartAddress","Status","user_account","user_name","TargetUserSid",
    "ProviderName","UserContext","ProviderPath","xml_name","CallerProcessName",
    "DnsServerList","Value","Name","TargetName","Ipaddress","Address","TargetUser",
    "CurrentDirectory","DeviceName","State Machine Name","ChannelName","Source",
    "Path","Product","PipeName","process_parent_name","TargetUserName","ImagePath",
    "rule_technique_name","rule_technique_id","Operation","log_name",
    "process_parent_path","ServiceName","etl_pipeline","Function","QueryName",
    "ActionName","RuleName","keywords","Binary","updateTitle","QueryResults",
    "FileVersion","source_name","ParentCommandLine","provider_guid","Description",
    "LogonGuid","OriginalFileName","ImageLoaded","etl_host_agent_ephemeral_uid",
    "TaskName","TaskInstanceId","task","updateGuid","process_name",
    "process_parent_guid","process_path","target_process_name","CommandLine",
    "HiveName","target_process_path","hash_imphash","Message","hash_sha1",
    "hash_sha256","hash_md5","activity_id","Details","CallTrace","object_name",
    "process_guid","TargetFilename","target_process_guid","TargetObject",
    "z_elastic_ecs","event_original_message",

    "DestinationIsIpv6","src_ip_public","DeviceUpdated","IsConnectivityFailure",
    "LastBootGood","dst_is_ipv6","IsDomainJoined","Initiated","IsServiceRestart",
    "IsExecutable","IsMachineBoot","IsBackgroundProcessing","IsAsyncProcessing",
    "meta_user_name_is_machine","Signed","VirtualAccount","dst_ip_public","Archived",
    "IsMachine",

    "src_ip_type","dst_ip_type","src_is_ipv6","src_ip_rfc","dst_ip_rfc",
    "dst_ip_addr","src_ip_addr","not_ip_src",

    "BugcheckParameter1","BugcheckParameter2","DriverRank","GrantedAccess","Flags",
    "ErrorCode","errorCode","SubStatus","SignatureStatus","TokenType","ResultCode",
    "opcode","level","Current State","New State","State","Event Name",

    "param1","param2","param3","param4","param5","param6","param7","param8",
    "param9","param10","param11",

    "object_handle_id","jobId","Id","FilterID","transferId","InstanceId",
    "RunningTaskInstanceId","QueuedTaskInstanceId","LifetimeId","PolicyActivityId",
    "process_id_orig","CallerProcessId","Action",
    "Action ID","Additional Actions ID","AppID","BootStatusPolicy",
    "BugcheckCode","BuildVersion","Category ID","ClientProcessId",
    "Current Signature Version",
    "Direction","EdgeTraversal",
    "ElevatedToken",
    "EnginePID",
    "Error Code",
    "DeviceInstanceID",
    "DeviceInstanceId",
    "Event",
    "Execution ID",
    "ExitCode",
    "LastBootId",
    "LastShutdownGood",
    "LoggingMode",
    "InstanceID",
    "Module Name",
    "NewProfile",
    "NewState",
    "NewThreadId",
    "NotificationType",
    "OldProfile",
    "Origin ID",
    "PID",
    "Param1",
    "PolicyApplicationMode",
    "Post Clean Status",
    "Pre Execution Status",
    "Previous Signature Version",
    "PreviousState",
    "Priority",
    "ProcessID",
    "ProcessPid",
    "ProcessingMode",
    "ProfileIdNum",
    "Profiles",
    "QfeVersion",
    "QueryStatus",
    "Reason",
    "ReasonCode",
    "ReasonForSyncProcessing",
    "ReturnCode",
    "Scenario",
    "SchemaVersion",
    "SecurityOptions",
    "Sent UpdateServer",
    "Session",
    "SessionID",
    "SessionId",
    "SettingType",
    "SettingValue",
    "Severity ID",
    "ShutdownActionType",
    "Signature Type Index",
    "Source ID",
    "SourceIsIpv6",
    "SourcePortName",
    "SourceThreadId",
    "StartType",
    "State Machine",
    "Status Code",
    "SubjectLogonId",
    "SupportInfo2",
    "TSId",
    "TargetLinkedLogonId",
    "TargetLogonId",
    "TargetSid",
    "TerminalSessionId",
    "Thread ID",
    "ThreadID",
    "Threat ID",
    "TunnelID",
    "Turn",
    "Type",
    "Update Type Index",
    "Url",
    "UserName",
    "dst_ip_version",
    "event_id",
    "hc_stateid",
    "hr",
    "jobTitle",
    "key_algorithm_name",
    "key_operation",
    "logon_type",
    "messageName",
    "object_old_sd",
    "port_src",
    "process_id",
    "process_parent_id",
    "src_ip_version",
    "target_process_id",
    "thread_id",
    "url",
    "user_logon_id",
    "user_sid",
    "version",    "LogonId",
    "MajorType",
    "MinorType",
}

changing the fields datatype accroding to the above divison

In [ ]:
# @title
import glob, os
import polars as pl

FILES = sorted(glob.glob("/content/comiset_parquet_v7/*.parquet"))
OUT_DIR = "/content/comiset_parquet_v10"
os.makedirs(OUT_DIR, exist_ok=True)

for i, f in enumerate(FILES):
    if i < -1:
        continue
    df = pl.read_parquet(f)

    df = df.with_columns([
        pl.col(c).cast(pl.Float64, strict=False).alias(c)
        for c in NUMERIC if c in df.columns
    ])

    df = df.with_columns([
        pl.col(c).cast(pl.Categorical).alias(c)
        for c in CATEGORICAL if c in df.columns
    ])

    df = df.with_columns([
        pl.col(c).str.to_datetime("%Y-%m-%dT%H:%M:%S%.f%#z",strict=False).alias(c)
        if df.schema[c] == pl.String
        else pl.col(c)
        for c in DATETIME
        if c in df.columns
    ])

    df.write_parquet(os.path.join(OUT_DIR, os.path.basename(f)), compression="zstd")
    del df
    print(f"{i+1}/{len(FILES)}")

DROP_COLUMNS , ONE_HOT_MANUAL and FEATURE_ENGINEERING_COLUMNS

In [ ]:
# @title
#farha 1
DROP_COLUMNS = [
    "InstanceId", "SourceThreadId", "TaskInstanceId", "activity_id",
    "hash_imphash", "hash_md5", "hash_sha1", "hash_sha256",
    "process_guid", "process_id", "process_parent_guid", "process_parent_id",
    "target_process_guid", "target_process_id", "thread_id", "updateGuid",
    "EnginePID", "FilterID", "Id", "LogonGuid", "LogonId", "NewThreadId",
    "ProcessID", "Thread ID", "etl_host_agent_ephemeral_uid", "transferId"
]

# farha 2
ONE_HOT_MANUAL = {
    "TaskName", "event_id", "process_name", "target_process_name", "task",
    "Description", "FileVersion", "Function", "OriginalFileName", "QueryName",
    "RuleName", "ServiceName", "TargetUserName", "etl_pipeline", "log_name",
    "opcode", "param2", "process_parent_name", "provider_guid",
    "rule_technique_id", "rule_technique_name", "source_name", "updateTitle"
}
#farha 3
FEATURE_ENGINEERING_COLUMNS = [
    "CallTrace",
    "z_elastic_ecs",
    "Details",
    "TargetFilename",
    "TargetObject",
    "event_original_message",
    "object_name",

    "CommandLine",
    "HiveName",
    "Message",
    "process_path",
    "target_process_path",
    "ActionName",
    "ImagePath","ImageLoaded","Operation",
    "Binary","parentComandLine","QueryResults","etl_pipeline","Keywords","Param1",
    "process_parent_path","src_ip_addr",
]

In [ ]:
import glob, os
import polars as pl
from sklearn.preprocessing import OneHotEncoder

FILES = sorted(glob.glob("/content/comiset_parquet_v11/content/comiset_parquet_v11/*.parquet"))

AUTO_ONE_HOT = set(profile.loc[profile["field"].isin(CATEGORICAL) & (profile["unique_count"] < 30),"field"])
ONE_HOT_COLUMNS = sorted(ONE_HOT_MANUAL | AUTO_ONE_HOT)

categories = {}
for col in ONE_HOT_COLUMNS:
    values = set()
    for f in FILES:
        values.update(
            pl.read_parquet(f, columns=[col])[col]
            .drop_nulls()
            .cast(pl.String)
            .unique()
            .to_list()
        )
    categories[col] = sorted(values)

categories = {
    c: sorted(v)
    for c, v in categories.items()
    if v
}

ONE_HOT_COLUMNS = sorted(categories)

encoder = OneHotEncoder(
    categories=[categories[c] for c in ONE_HOT_COLUMNS],
    handle_unknown="ignore",
    sparse_output=False,
    dtype="uint8"
)

encoder.fit([[categories[c][0] for c in ONE_HOT_COLUMNS]])

OUTPUT_DIR = "/content/comiset_parquet_v12"
os.makedirs(OUTPUT_DIR, exist_ok=True)

In [ ]:
import os
import gc
import glob
import polars as pl
import pyarrow as pa
import pyarrow.parquet as pq

BATCH_SIZE = 100_000

for i, f in enumerate(FILES):
    output_path = os.path.join(OUTPUT_DIR, os.path.basename(f))

    if os.path.exists(output_path):
        continue

    print(f"Starting {i+1}/{len(FILES)}: {f}", flush=True)

    parquet_file = pq.ParquetFile(f)
    writer = None

    for batch in parquet_file.iter_batches(batch_size=BATCH_SIZE):
        df = pl.from_arrow(batch)

        X = df.select(ONE_HOT_COLUMNS).with_columns(
            pl.all().cast(pl.String)
        )

        encoded = encoder.transform(X.to_numpy())

        dummy = pl.DataFrame(
            encoded,
            schema=encoder.get_feature_names_out(ONE_HOT_COLUMNS).tolist()
        )

        result = df.drop(ONE_HOT_COLUMNS).hstack(dummy)
        table = result.to_arrow()

        if writer is None:
            writer = pq.ParquetWriter(output_path, table.schema)

        writer.write_table(table)

        del df, X, encoded, dummy, result, table
        gc.collect()

    if writer is not None:
        writer.close()

    print(f"Completed {i+1}/{len(FILES)}", flush=True)

Starting 92/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00091.parquet
Completed 92/130
Starting 93/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00092.parquet
Completed 93/130
Starting 94/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00093.parquet
Completed 94/130
Starting 95/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00094.parquet
Completed 95/130
Starting 96/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00095.parquet
Completed 96/130
Starting 97/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00096.parquet
Completed 97/130
Starting 98/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00097.parquet
Completed 98/130
Starting 99/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00098.parquet
Completed 99/130
Starting 100/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00099.parquet
Completed 100/130
Starting 101/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00100.parquet
Completed 101/130
Starting 102/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00101.parquet
Completed 102/130
Starting 103/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00102.parquet
Completed 103/130
Starting 104/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00103.parquet
Completed 104/130
Starting 105/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00104.parquet
Completed 105/130
Starting 106/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00105.parquet
Completed 106/130
Starting 107/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00106.parquet
Completed 107/130
Starting 108/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00107.parquet
Completed 108/130
Starting 109/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00108.parquet
Completed 109/130
Starting 110/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00109.parquet
Completed 110/130
Starting 111/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00110.parquet
Completed 111/130
Starting 112/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00111.parquet
Completed 112/130
Starting 113/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00112.parquet
Completed 113/130
Starting 114/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00113.parquet
Completed 114/130
Starting 115/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00114.parquet
Completed 115/130
Starting 116/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00115.parquet
Completed 116/130
Starting 117/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00116.parquet
Completed 117/130
Starting 118/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00117.parquet
Completed 118/130
Starting 119/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00118.parquet

In [ ]:

# @title
for i, f in enumerate(FILES):
    if os.path.exists(os.path.join(OUTPUT_DIR, os.path.basename(f))):
        continue
    print(f"Starting {i+1}/{len(FILES)}: {f}", flush=True)

    df = pl.read_parquet(f)

    X = df.select(ONE_HOT_COLUMNS).with_columns(
        pl.all().cast(pl.String)
    )

    encoded = encoder.transform(X.to_numpy())

    dummy = pl.DataFrame(
        encoded,
        schema=encoder.get_feature_names_out(ONE_HOT_COLUMNS).tolist()
    )

    df = df.drop(ONE_HOT_COLUMNS).hstack(dummy)

    df.write_parquet(
        os.path.join(OUTPUT_DIR, os.path.basename(f))
    )

    # Explicitly release everything from this iteration
    del X
    del encoded
    del dummy
    del df

    import gc
    gc.collect()

    print(f"{i+1}/{len(FILES)}", flush=True)

Starting 9/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00008.parquet
9/130
Starting 10/130: /content/comiset_parquet_v11/content/comiset_parquet_v11/part-00009.parquet

verifying if it worked

In [ ]:
FILES = sorted(glob.glob("/content/comiset_parquet_v11/*.parquet"))
for i in range(len(FILES)):
    if i%10 != 0:
      continue
    df = pl.read_parquet(FILES[i])
    print(i ,":", df.shape)
    del df

NameError: name 'glob' is not defined

In [ ]:
import shutil
import os

FOLDER = "/content/comiset_parquet_v11/content"

for item in os.listdir(FOLDER):
    path = os.path.join(FOLDER, item)
    if os.path.isdir(path):
        shutil.rmtree(path)
    else:
        os.remove(path)

one hot encoding

In [ ]:
# @title
for i, f in enumerate(FILES):
    df = pl.read_parquet(f)

    df = df.drop([c for c in DROP_COLUMNS if c in df.columns])

    expressions = []

    for col in ONE_HOT_COLUMNS:
        if col not in df.columns:
            continue

        expressions.extend(
            pl.col(col)
            .cast(pl.String)
            .eq(value)
            .cast(pl.UInt8)
            .alias(f"{col}__{value}")
            for value in categories[col]
        )

    df = df.with_columns(expressions)
    df = df.drop([c for c in ONE_HOT_COLUMNS if c in df.columns])

    df.write_parquet(
        os.path.join(OUTPUT_DIR, os.path.basename(f))
    )

    print(f"{i+1}/{len(FILES)}")

In [ ]:
categorical_candidates.field.to_list()

['Action Name',
 'DestinationIsIpv6',
 'DestinationPortName',
 'Detection ID',
 'Detection User',
 'src_ip_public',
 'BugcheckParameter2',
 'DriverInbox',
 'DeviceUpdated',
 'DisplayName',
 'Domain',
 'Category Name',
 'Capability',
 'Build Name',
 'BugcheckParameter1',
 'DriverProvider',
 'FWLink',
 'FileNameBuffer',
 'IsConnectivityFailure',
 'Execution Name',
 'Error Description',
 'EmbeddedContext',
 'Engine Version',
 'LocalPath',
 'LastBootGood',
 'key_name',
 'key_type',
 'key_return_code',
 'key_file_path',
 'jobName',
 'host_name',
 'dst_is_ipv6',
 'OSName',
 'NewStateName',
 'LoadOptions',
 'LicenseId',
 'ModifyingApplication',
 'PossibleCause',
 'Origin Name',
 'OutrankedDrivers',
 'ReadOperation',
 'ReasonString',
 'RemotePorts',
 'object_server',
 'Product Name',
 'PreviousStateName',
 'PackageName',
 'Product Version',
 'LocalPorts',
 'Location',
 'Scan ID',
 'SID',
 'Scan Type',
 'Severity Name',
 'SettingValueDisplay',
 'SessionName',
 'param9',
 'WorkstationName',
 'Version',
 'UserSid',
 'UserId',
 'UpdateService',
 'Update Type',
 'Type Name',
 'Additional Actions String',
 'AssociateId',
 'DescriptionString',
 'Signature Version',
 'SourceIsIpv6',
 'SourcePortName',
 'SourceHostname',
 'Source Name',
 'StateTransition',
 'TargetOutboundUserName',
 'Threat Name',
 'TimezoneBiasHour',
 'TargetOutboundDomainName',
 'TargetLogonGuid',
 'StateName',
 'StartFunction',
 'Signature Type',
 'Scan Parameters',
 'Component',
 'Code',
 'DestinationHostname',
 'ChannelPath',
 'ImpersonationLevel',
 'KeyName',
 'DriverRank',
 'MatchingDeviceId',
 'IsDomainJoined',
 'errorCode',
 'Initiated',
 'ErrorSourceTable',
 'DriverSection',
 'FailureReason',
 'param10',
 'object_old_sd',
 'param11',
 'Problem',
 'OperationDescription',
 'OldSchemeGuid',
 'PrimaryService',
 'LastShutdownGood',
 'IsServiceRestart',
 'IsExecutable',
 'key_algorithm_name',
 'key_operation',
 'IsMachineBoot',
 'Param1',
 'Previous Signature Version',
 'NewSchemeGuid',
 'PrincipalSamName',
 'ElevatedToken',
 'dst_ip_type',
 'FunctionName',
 'InstancePath',
 'IsBackgroundProcessing',
 'IsAsyncProcessing',
 'EventName',
 'AccountName',
 'DriverDate',
 'src_ip_type',
 'src_is_ipv6',
 'messageName',
 'meta_user_name_is_machine',
 'ErrorDescription',
 'src_ip_rfc',
 'AdapterName',
 'RunningTaskInstanceId',
 'user_sid',
 'ModifyingUser',
 'TransportProtocolName',
 'SubStatus',
 'SignatureStatus',
 'Signed',
 'Sent UpdateServer',
 'TokenType',
 'TargetInfo',
 'TargetServerName',
 'StartModule',
 'ServiceType',
 'SetupClass',
 'VirtualAccount',
 'dst_ip_rfc',
 'dst_ip_public',
 'AuthenticationPackageName',
 'Current Signature Version',
 'AppID',
 'ApplicationPath',
 'TransportType',
 'DriverVersion',
 'InterfaceName',
 'DriverDescription',
 'ConnectionName',
 'jobOwner',
 'PolicyActivityId',
 'LifetimeId',
 'OperationParameter1',
 'InterfaceGuid',
 'Target',
 'param8',
 'string2',
 'Command',
 'ClassGuid',
 'Archived',
 'object_new_sd',
 'Protocol',
 'IsMachine',
 'Module Name',
 'jobTitle',
 'TransportName',
 'SubjectDomainName',
 'IntegrityLevel',
 'param6',
 'ServerName',
 'level',
 'DeviceInstanceId',
 'Flags',
 'ErrorMessage',
 'serviceGuid',
 'ResourceURI',
 'StartType',
 'user_domain',
 'Signature',
 'User',
 'ParentUser',
 'PrivilegeList',
 'LogonProcessName',
 'Process Name',
 'not_ip_src',
 'DeviceInstanceID',
 'string',
 'src_original_value',
 'tags',
 'Company',
 'TargetDomainName',
 'SourceUser',
 'meta_dst_ip_geo',
 'DriveName',
 'EventType',
 'DriverFileName',
 'param7',
 'RuleId',
 'SubjectUserSid',
 'SubjectUserName',
 'name',
 'LastRunDateTime',
 'Url',
 'UserName',
 'New State',
 'InfoDescription',
 'ExtraInfoString',
 'DriverName',
 'StartAddress',
 'Status',
 'user_account',
 'user_name',
 'TargetUserSid',
 'ProviderName',
 'UserContext',
 'ProviderPath',
 'xml_name',
 'CallerProcessName',
 'DnsServerList',
 'GrantedAccess',
 'Value',
 'fileTime',
 'Name',
 'TargetName',
 'Ipaddress',
 'Address',
 'Current State',
 'Event Name',
 'TargetUser',
 'CallerProcessId',
 'CurrentDirectory',
 'DeviceName',
 'param3',
 'url',
 'State Machine Name',
 'QueuedTaskInstanceId',
 'ChannelName',
 'ResultCode',
 'object_handle_id',
 'jobId',
 'param5',
 'param4',
 'Source',
 'Path',
 'Product',
 'dst_ip_addr',
 'process_id_orig',
 'TargetSid',
 'State Machine',
 'PipeName',
 'opcode',
 'src_ip_addr',
 'Id',
 'param2',
 'process_parent_name',
 'TargetUserName',
 'ImagePath',
 'rule_technique_name',
 'rule_technique_id',
 'Operation',
 'log_name',
 'process_parent_path',
 'ServiceName',
 'etl_pipeline',
 'Function',
 'QueryName',
 'ActionName',
 'transferId',
 'RuleName',
 'keywords',
 'param1',
 'FilterID',
 'Binary',
 'updateTitle',
 'QueryResults',
 'FileVersion',
 'source_name',
 'ParentCommandLine',
 'provider_guid',
 'Description',
 'LogonGuid',
 'OriginalFileName',
 'ImageLoaded',
 'etl_host_agent_ephemeral_uid',
 'TaskName',
 'TaskInstanceId',
 'task',
 'updateGuid',
 'InstanceId',
 'process_name',
 'process_parent_guid',
 'process_path',
 'target_process_name',
 'CommandLine',
 'HiveName',
 'target_process_path',
 'hash_imphash',
 'Message',
 'hash_sha1',
 'hash_sha256',
 'hash_md5',
 'activity_id',
 'Details',
 'CallTrace',
 'object_name',
 'process_guid',
 'TargetFilename',
 'target_process_guid',
 'TargetObject',
 'z_elastic_ecs',
 'event_original_message']

In [ ]:
import glob
import polars as pl

FILES = sorted(glob.glob("/content/comiset_parquet_v10/*.parquet"))

for i, f in enumerate(FILES):
    schema = pl.read_parquet_schema(f)

    strings = [c for c, dtype in schema.items() if dtype == pl.String]

if strings:
    print(strings)

In [11]:
!zip -r /content/comiset_parquet_v12.zip /content/comiset_parquet_v12

  adding: content/comiset_parquet_v12/ (stored 0%)
  adding: content/comiset_parquet_v12/part-00057.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00079.parquet (deflated 82%)
  adding: content/comiset_parquet_v12/part-00005.parquet (deflated 80%)
  adding: content/comiset_parquet_v12/part-00020.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00069.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00087.parquet (deflated 81%)
  adding: content/comiset_parquet_v12/part-00064.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00018.parquet (deflated 77%)
  adding: content/comiset_parquet_v12/part-00054.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00067.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00043.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00073.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00061.parquet (deflated 80%)
  adding: content/comiset_parquet_v12/part-00000.parquet (deflated 70%)
  adding: content/comiset_parquet_v12/part-00045.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00008.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00039.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00090.parquet (deflated 80%)
  adding: content/comiset_parquet_v12/part-00041.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00011.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00026.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00063.parquet (deflated 80%)
  adding: content/comiset_parquet_v12/part-00032.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00034.parquet (deflated 76%)
  adding: content/comiset_parquet_v12/part-00031.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00037.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00028.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00078.parquet (deflated 81%)
  adding: content/comiset_parquet_v12/part-00029.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00074.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00014.parquet (deflated 77%)
  adding: content/comiset_parquet_v12/part-00047.parquet (deflated 76%)
  adding: content/comiset_parquet_v12/part-00081.parquet (deflated 81%)
  adding: content/comiset_parquet_v12/part-00044.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00072.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00077.parquet (deflated 81%)
  adding: content/comiset_parquet_v12/part-00085.parquet (deflated 81%)
  adding: content/comiset_parquet_v12/part-00004.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00003.parquet (deflated 80%)
  adding: content/comiset_parquet_v12/part-00051.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00033.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00024.parquet (deflated 77%)
  adding: content/comiset_parquet_v12/part-00013.parquet (deflated 77%)
  adding: content/comiset_parquet_v12/part-00083.parquet (deflated 80%)
  adding: content/comiset_parquet_v12/part-00055.parquet (deflated 77%)
  adding: content/comiset_parquet_v12/part-00019.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00065.parquet (deflated 80%)
  adding: content/comiset_parquet_v12/part-00001.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00062.parquet (deflated 81%)
  adding: content/comiset_parquet_v12/part-00021.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00082.parquet (deflated 82%)
  adding: content/comiset_parquet_v12/part-00086.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00052.parquet (deflated 80%)
  adding: content/comiset_parquet_v12/part-00068.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00070.parquet (deflated 81%)
  adding: content/comiset_parquet_v12/part-00059.parquet (deflated 77%)
  adding: content/comiset_parquet_v12/part-00088.parquet (deflated 80%)
  adding: content/comiset_parquet_v12/part-00002.parquet (deflated 81%)
  adding: content/comiset_parquet_v12/part-00066.parquet (deflated 80%)
  adding: content/comiset_parquet_v12/part-00027.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00009.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00038.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00080.parquet (deflated 82%)
  adding: content/comiset_parquet_v12/part-00040.parquet (deflated 81%)
  adding: content/comiset_parquet_v12/part-00025.parquet (deflated 77%)
  adding: content/comiset_parquet_v12/part-00060.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00016.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00012.parquet (deflated 77%)
  adding: content/comiset_parquet_v12/part-00022.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00006.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00091.parquet (deflated 69%)
  adding: content/comiset_parquet_v12/part-00089.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00050.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00058.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00049.parquet (deflated 80%)
  adding: content/comiset_parquet_v12/part-00084.parquet (deflated 82%)
  adding: content/comiset_parquet_v12/part-00046.parquet (deflated 77%)
  adding: content/comiset_parquet_v12/part-00036.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00071.parquet (deflated 80%)
  adding: content/comiset_parquet_v12/part-00017.parquet (deflated 77%)
  adding: content/comiset_parquet_v12/part-00042.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00023.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00075.parquet (deflated 80%)
  adding: content/comiset_parquet_v12/part-00035.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00010.parquet (deflated 76%)
  adding: content/comiset_parquet_v12/part-00015.parquet (deflated 77%)
  adding: content/comiset_parquet_v12/part-00056.parquet (deflated 79%)
  adding: content/comiset_parquet_v12/part-00076.parquet (deflated 80%)
  adding: content/comiset_parquet_v12/part-00048.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00053.parquet (deflated 80%)
  adding: content/comiset_parquet_v12/part-00007.parquet (deflated 78%)
  adding: content/comiset_parquet_v12/part-00030.parquet (deflated 80%)

In [12]:
from google.colab import files
files.download("/content/comiset_parquet_v12.zip")

handling fields that were directly mentioned in the comiset documtentation

In [ ]:
# @title
import pandas as pd

# Clearly documented semantic types
NUMERIC = {
    # genuine numeric quantities go here
}

CATEGORICAL = {
    "Task",
    "Description",
    "OriginalFileName",
    "Host_name",
    "ParentUser",
    "process_parent_name",
    "Process_name",
    "Process_path",
    "User_account",
    "Current_Directory",
}

IDENTIFIERS = {
    "Process_id",
    "Process_parent_id",
    "Thread_id",
    "Process_guid",
    "Process_parent_guid",
}

DATETIME = {
    "@timestamp",
    "Event_recorded_time",
    "Event_original_time",
}

DROP = {
    "Event_original_message",
    "Etl_host_agent_ephemeral_uid",
}

FILES = sorted(glob.glob("./comiset_parquet_v3/*.parquet"))

for i, f in enumerate(FILES):
    df = pl.read_parquet(f)

    # type conversions here
    for col in NUMERIC:
        if col in df.columns:
            df = df.with_columns(
                pl.col(col).cast(pl.Float64, strict=False)
            )

    for col in CATEGORICAL | IDENTIFIERS:
        if col in df.columns:
            df = df.with_columns(
                pl.col(col).cast(pl.Categorical)
            )

    for col in DATETIME:
        if col in df.columns:
            df = df.with_columns(
                pl.col(col).str.to_datetime(strict=False, time_zone="UTC")
            )

    # then write this processed shard
    df.write_parquet(
        f.replace("comiset_parquet_v3", "comiset_parquet_v4"),
        compression="zstd"
    )

    del df
    print(f"{i+1}/{len(FILES)}")

1/130
2/130
3/130
4/130
5/130
6/130
7/130
8/130
9/130
10/130
11/130
12/130
13/130
14/130
15/130
16/130
17/130
18/130
19/130
20/130
21/130
22/130
23/130
24/130
25/130
26/130
27/130
28/130
29/130
30/130
31/130
32/130
33/130
34/130
35/130
36/130
37/130
38/130
39/130
40/130
41/130
42/130
43/130
44/130
45/130
46/130
47/130
48/130
49/130
50/130
51/130
52/130
53/130
54/130
55/130
56/130
57/130
58/130
59/130
60/130
61/130
62/130
63/130
64/130
65/130
66/130
67/130
68/130
69/130
70/130
71/130
72/130
73/130
74/130
75/130
76/130
77/130
78/130
79/130
80/130
81/130
82/130
83/130
84/130
85/130
86/130
87/130
88/130
89/130
90/130
91/130
92/130
93/130
94/130
95/130
96/130
97/130
98/130
99/130
100/130
101/130
102/130
103/130
104/130
105/130
106/130
107/130
108/130
109/130
110/130
111/130
112/130
113/130
114/130
115/130
116/130
117/130
118/130
119/130
120/130
121/130
122/130
123/130
124/130
125/130
126/130
127/130
128/130
129/130
130/130

farha's training loop

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train:", X_train.shape)
print("Test:", X_test.shape)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1,
    class_weight='balanced'
)

rf_model.fit(X_train, y_train)

In [ ]:
y_pred_rf = rf_model.predict(X_test)

In [ ]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

print("Accuracy:", accuracy_score(y_test, y_pred_rf))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

In [ ]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
    eval_metric='logloss'
)

xgb_model.fit(X_train, y_train)

In [ ]:
y_pred_xgb = xgb_model.predict(X_test)

In [ ]:
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_xgb))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))